"""
STEP 5: Blender Sewing & Cloth Simulation
==========================================
This script runs INSIDE Blender to:
1. Import SVG pattern pieces
2. Convert them to cloth meshes
3. Position them for sewing
4. Define sewing constraints (which edges connect)
5. Run cloth simulation

Think of this as a DIGITAL TAILOR:
- The pattern pieces are like cut fabric
- We pin matching edges together
- Gravity and physics pull them into shape
- The result is a 3D garment!

HOW TO RUN:
1. Open Blender
2. Go to Scripting workspace
3. Open this file
4. Click "Run Script"

Or from command line:
    blender --python step5_blender_sewing.py
"""

import bpy
import bmesh
import math
import os
import json
import gc  # Garbage collection for memory management
from pathlib import Path
from mathutils import Vector, Matrix

def force_view_context():
    for window in bpy.context.window_manager.windows:
        for area in window.screen.areas:
            if area.type == 'VIEW_3D':
                for region in area.regions:
                    if region.type == 'WINDOW':
                        return {
                            "window": window,
                            "screen": window.screen,
                            "area": area,
                            "region": region,
                            "scene": bpy.context.scene,
                            "view_layer": bpy.context.view_layer
                        }
    raise RuntimeError("No VIEW_3D context found")
# ============================================================
# CONFIGURATION
# ============================================================

# Input directory (where pattern SVGs are)
PATTERN_DIR = Path(__file__).parent / "pattern_output"

# Scale factor: SVG is in cm, Blender uses meters
# 1 cm = 0.01 meters
CM_TO_M = 0.01

# Cloth simulation settings (OPTIMIZED for memory)
CLOTH_SETTINGS = {
    "quality": 8,            # Reduced from 12 to save memory
    "mass": 0.3,             # Fabric weight (kg/m²) - cotton is ~0.15-0.3
    "tension_stiffness": 15, # How much fabric resists stretching
    "compression_stiffness": 15,
    "bending_stiffness": 0.5,  # How easily fabric bends
    "air_damping": 1,        # Air resistance
}

# Sewing spring settings (TUNED FOR REAL SEWING)
# Force 20-30 is recommended for realistic sewing behavior
SEWING_SETTINGS = {
    "force": 25.0,           # Sewing spring strength (20-30 recommended)
    "max_dist": 0.15,        # Max distance for sewing (meters)
    "shrink_min": 0.0,       # Minimum shrink factor
    "shrink_max": 0.0,       # Maximum shrink factor
}

# Path to seam definitions (generated by step4)
SEAM_FILE = PATTERN_DIR / "seams.json"

# Global storage for loaded seam data (populated by load_seam_definitions)
SEAM_DATA = {
    "seams": [],           # Simple seam pairs: ["Panel:edge", "Panel:edge"]
    "seam_details": [],    # Detailed seam metadata
    "panels": {},          # Panel edge data with vertex coordinates
    "loaded": False        # Flag to track if data was loaded
}


# ============================================================
# SEAM LOADING AND PARSING
# ============================================================

def load_seam_definitions() -> dict:
    """
    Load seam definitions from seams.json (ENHANCED VERSION).
    
    The seams.json file contains:
    - seams: Simple pairs ["Panel:edge", "Panel:edge"] for quick matching
    - seam_details: Detailed metadata (name, type, priority)
    - panels: Edge vertex coordinates for each panel
    
    Returns:
        Full seam data dictionary, or empty dict if file not found
    """
    global SEAM_DATA
    
    if not SEAM_FILE.exists():
        print(f"  ⚠ No seam file found at {SEAM_FILE}")
        print("    Sewing will use default edge matching")
        return {}
    
    try:
        with open(SEAM_FILE, 'r') as f:
            data = json.load(f)
        
        # Store in global for access by other functions
        SEAM_DATA["seams"] = data.get("seams", [])
        SEAM_DATA["seam_details"] = data.get("seam_details", [])
        SEAM_DATA["panels"] = data.get("panels", {})
        SEAM_DATA["loaded"] = True
        
        print(f"  ✓ Loaded seams.json:")
        print(f"      - {len(SEAM_DATA['seams'])} seam pairs")
        print(f"      - {len(SEAM_DATA['panels'])} panel definitions")
        
        # Log panel edge counts
        for panel_name, panel_data in SEAM_DATA["panels"].items():
            edge_count = len(panel_data.get("edges", {}))
            print(f"      - {panel_name}: {edge_count} edges")
        
        return data
        
    except Exception as e:
        print(f"  ✗ Error loading seams.json: {e}")
        return {}


def parse_seam_pair(seam_pair: str) -> tuple:
    """
    Parse a seam pair string into (panel_name, edge_name).
    
    Format: "Panel_Name:edge_name" -> ("Panel_Name", "edge_name")
    
    Args:
        seam_pair: String like "Front_Panel:side_seam"
    
    Returns:
        Tuple of (panel_name, edge_name)
    """
    if ":" not in seam_pair:
        return (seam_pair, "unknown")
    
    parts = seam_pair.split(":", 1)
    return (parts[0].strip(), parts[1].strip())


def get_panel_edge_vertices(panel_name: str, edge_name: str) -> list:
    """
    Get vertex coordinates for a specific edge from loaded seam data.
    
    Args:
        panel_name: Name of the panel (e.g., "front", "back", "sleeve")
        edge_name: Name of the edge (e.g., "side_seam", "shoulder")
    
    Returns:
        List of [x, y] coordinates in cm, or empty list if not found
    """
    if not SEAM_DATA["loaded"]:
        return []
    
    # Try exact match first
    panel_data = SEAM_DATA["panels"].get(panel_name)
    
    # Try lowercase match
    if not panel_data:
        for key, data in SEAM_DATA["panels"].items():
            if key.lower() == panel_name.lower():
                panel_data = data
                break
    
    if not panel_data:
        return []
    
    edges = panel_data.get("edges", {})
    edge_data = edges.get(edge_name, {})
    
    return edge_data.get("vertices", [])


def resolve_panel_objects(panels: dict) -> dict:
    """
    Create a mapping from panel names (in seams.json) to Blender objects.
    
    This handles name variations between the pattern generator
    and the Blender mesh objects.
    
    Args:
        panels: Dictionary of Blender mesh objects created in the pipeline
    
    Returns:
        Dictionary mapping seam.json panel names to Blender objects
    """
    # Mapping from seams.json names to internal panel dict keys
    name_mapping = {
        # Pattern names -> Blender object keys
        "front": "front",
        "Front_Panel": "front",
        "front_panel": "front",
        
        "back": "back",
        "Back_Panel": "back",
        "back_panel": "back",
        
        "sleeve": "left_sleeve",
        "Left_Sleeve": "left_sleeve",
        "left_sleeve": "left_sleeve",
        
        "Right_Sleeve": "right_sleeve",
        "right_sleeve": "right_sleeve",
        "sleeve_left": "left_sleeve",
        "sleeve_right": "right_sleeve",
        
        # Neck band (XML Schema v1.1)
        "Neck_Band": "neck_band",
        "neck_band": "neck_band",
        "NeckBand": "neck_band",
    }
    
    resolved = {}
    
    for seam_name, panel_key in name_mapping.items():
        if panel_key in panels and panels[panel_key] is not None:
            resolved[seam_name] = panels[panel_key]
    
    print(f"  ✓ Resolved {len(resolved)} panel name mappings")
    
    return resolved


# ============================================================
# EDGE MARKING AND SEWING SPRINGS (NEW)
# ============================================================

def find_vertices_near_coordinates(mesh_obj: bpy.types.Object, 
                                    target_coords: list,
                                    tolerance: float = 0.05) -> list:
    """
    Find mesh vertices that are near the given target coordinates.
    
    This matches pattern edge vertices (from seams.json) to actual
    Blender mesh vertices after subdivision.
    
    Args:
        mesh_obj: The Blender mesh object
        target_coords: List of [x, y] coordinates in cm from seams.json
        tolerance: Distance tolerance in meters for matching
    
    Returns:
        List of vertex indices that match the target coordinates
    """
    mesh = mesh_obj.data
    matrix = mesh_obj.matrix_world
    
    matched_indices = []
    
    for i, vert in enumerate(mesh.vertices):
        world_co = matrix @ Vector(vert.co)
        
        # Check against each target coordinate
        for tx, ty in target_coords:
            # Convert cm to meters for comparison
            target_x = tx * CM_TO_M
            target_y = ty * CM_TO_M
            
            # Calculate distance (using x,y as mesh is initially flat in XY plane)
            # After rotation, we check in world space
            dist_xy = math.sqrt((world_co.x - target_x)**2 + (world_co.y - target_y)**2)
            dist_xz = math.sqrt((world_co.x - target_x)**2 + (world_co.z - target_y)**2)
            
            # Match if close to target in either XY or XZ plane (depending on rotation)
            if dist_xy < tolerance or dist_xz < tolerance:
                if i not in matched_indices:
                    matched_indices.append(i)
                break
    
    return matched_indices


def find_edge_indices_by_position(mesh_obj: bpy.types.Object,
                                   edge_vertices: list,
                                   tolerance: float = 0.03) -> list:
    """
    Find mesh edge indices that correspond to a pattern edge.
    
    After subdivision, we need to find which mesh edges
    lie along the original pattern edge path.
    
    Args:
        mesh_obj: The Blender mesh object
        edge_vertices: List of [x, y] coordinates defining the edge path
        tolerance: Distance tolerance for matching
    
    Returns:
        List of mesh edge indices
    """
    if not edge_vertices or len(edge_vertices) < 2:
        return []
    
    mesh = mesh_obj.data
    matrix = mesh_obj.matrix_world
    
    # Convert edge vertices to world space line segments
    edge_path = []
    for x, y in edge_vertices:
        edge_path.append(Vector((x * CM_TO_M, y * CM_TO_M, 0)))
    
    matched_edges = []
    
    for edge_idx, edge in enumerate(mesh.edges):
        v1 = matrix @ Vector(mesh.vertices[edge.vertices[0]].co)
        v2 = matrix @ Vector(mesh.vertices[edge.vertices[1]].co)
        midpoint = (v1 + v2) / 2
        
        # Check if edge midpoint is close to any segment of the path
        for i in range(len(edge_path) - 1):
            p1, p2 = edge_path[i], edge_path[i + 1]
            
            # Point-to-line-segment distance (simplified 2D)
            dist = point_to_segment_distance_2d(
                (midpoint.x, midpoint.z),  # Use X,Z after rotation
                (p1.x, p1.y), (p2.x, p2.y)
            )
            
            if dist < tolerance:
                matched_edges.append(edge_idx)
                break
    
    return matched_edges


def point_to_segment_distance_2d(point: tuple, seg_start: tuple, seg_end: tuple) -> float:
    """
    Calculate distance from a point to a line segment in 2D.
    
    Args:
        point: (x, y) point
        seg_start: (x, y) segment start
        seg_end: (x, y) segment end
    
    Returns:
        Distance from point to nearest point on segment
    """
    px, py = point
    x1, y1 = seg_start
    x2, y2 = seg_end
    
    # Vector from seg_start to seg_end
    dx = x2 - x1
    dy = y2 - y1
    
    # Handle zero-length segment
    seg_len_sq = dx * dx + dy * dy
    if seg_len_sq < 1e-10:
        return math.sqrt((px - x1)**2 + (py - y1)**2)
    
    # Project point onto line, clamped to segment
    t = max(0, min(1, ((px - x1) * dx + (py - y1) * dy) / seg_len_sq))
    
    # Nearest point on segment
    nearest_x = x1 + t * dx
    nearest_y = y1 + t * dy
    
    return math.sqrt((px - nearest_x)**2 + (py - nearest_y)**2)


def select_edges_by_indices(mesh_obj: bpy.types.Object, edge_indices: list):
    """
    Select specific edges in a mesh by their indices.
    
    Args:
        mesh_obj: The mesh object
        edge_indices: List of edge indices to select
    """
    # Ensure we're in object mode first
    if bpy.context.active_object and bpy.context.active_object.mode != 'OBJECT':
        bpy.ops.object.mode_set(mode='OBJECT')
    
    # Select the target object
    bpy.ops.object.select_all(action='DESELECT')
    mesh_obj.select_set(True)
    bpy.context.view_layer.objects.active = mesh_obj
    
    # Enter edit mode
    bpy.ops.object.mode_set(mode='EDIT')
    
    # Deselect all first
    bpy.ops.mesh.select_all(action='DESELECT')
    
    # Switch to edge select mode
    bpy.ops.mesh.select_mode(type='EDGE')
    
    # Return to object mode to manipulate selection data
    bpy.ops.object.mode_set(mode='OBJECT')
    
    # Select edges by index
    mesh = mesh_obj.data
    for idx in edge_indices:
        if 0 <= idx < len(mesh.edges):
            mesh.edges[idx].select = True
    
    # Back to edit mode to see selection
    bpy.ops.object.mode_set(mode='EDIT')


def mark_edges_as_seam(mesh_obj: bpy.types.Object, edge_indices: list, seam_name: str = ""):
    """
    Mark specific edges as seams in Blender.
    
    Seam marking tells Blender's cloth solver which edges
    should be pulled together during simulation.
    
    Args:
        mesh_obj: The mesh object
        edge_indices: List of edge indices to mark as seams
        seam_name: Optional name for logging
    """
    if not edge_indices:
        print(f"    ⚠ No edges to mark for seam {seam_name}")
        return
    
    # Ensure object mode
    if bpy.context.active_object and bpy.context.active_object.mode != 'OBJECT':
        bpy.ops.object.mode_set(mode='OBJECT')
    
    # Select object
    bpy.ops.object.select_all(action='DESELECT')
    mesh_obj.select_set(True)
    bpy.context.view_layer.objects.active = mesh_obj
    
    # Use BMesh for seam marking
    bpy.ops.object.mode_set(mode='EDIT')
    bm = bmesh.from_edit_mesh(mesh_obj.data)
    bm.edges.ensure_lookup_table()
    
    marked_count = 0
    for idx in edge_indices:
        if 0 <= idx < len(bm.edges):
            bm.edges[idx].seam = True
            marked_count += 1
    
    # Update mesh
    bmesh.update_edit_mesh(mesh_obj.data)
    bpy.ops.object.mode_set(mode='OBJECT')
    
    if seam_name:
        print(f"    ✓ Marked {marked_count} edges as seam: {seam_name}")


def mark_seams_from_vertex_group(mesh_obj: bpy.types.Object, vertex_group_name: str):
    """
    Mark edges as seams if both vertices are in the given vertex group.
    
    This uses the vertex groups created during seam setup.
    
    Args:
        mesh_obj: The mesh object with vertex groups
        vertex_group_name: Name of the vertex group
    """
    if vertex_group_name not in mesh_obj.vertex_groups:
        print(f"    ⚠ Vertex group not found: {vertex_group_name}")
        return
    
    vg = mesh_obj.vertex_groups[vertex_group_name]
    vg_index = vg.index
    
    # Get vertices in this group
    verts_in_group = set()
    for v in mesh_obj.data.vertices:
        for g in v.groups:
            if g.group == vg_index and g.weight > 0.5:
                verts_in_group.add(v.index)
                break
    
    if not verts_in_group:
        return
    
    # Find edges where both vertices are in the group
    edge_indices = []
    for edge in mesh_obj.data.edges:
        if edge.vertices[0] in verts_in_group and edge.vertices[1] in verts_in_group:
            edge_indices.append(edge.index)
    
    # Mark these edges as seams
    mark_edges_as_seam(mesh_obj, edge_indices, vertex_group_name)


def enable_sewing_springs_on_cloth(cloth_obj: bpy.types.Object, 
                                    sewing_force: float = 25.0,
                                    shrink_min: float = 0.0,
                                    max_sewing_dist: float = 0.15):
    """
    Enable and configure sewing springs on a cloth modifier.
    
    Sewing springs pull marked seam edges together during simulation.
    This is the key feature for realistic garment construction.
    
    Args:
        cloth_obj: Object with cloth modifier
        sewing_force: Strength of sewing pull (20-30 recommended)
        shrink_min: Minimum shrink factor (0.0 = no extra shrink)
        max_sewing_dist: Maximum distance for sewing to work (meters)
    
    Returns:
        True if sewing enabled, False if no cloth modifier found
    """
    print(f"→ Enabling sewing springs on {cloth_obj.name}...")
    
    # Find cloth modifier
    cloth_mod = None
    for mod in cloth_obj.modifiers:
        if mod.type == 'CLOTH':
            cloth_mod = mod
            break
    
    if not cloth_mod:
        print(f"  ✗ No cloth modifier found on {cloth_obj.name}")
        return False
    
    # Enable sewing springs
    cloth_settings = cloth_mod.settings
    cloth_settings.use_sewing_springs = True
    cloth_settings.sewing_force_max = sewing_force
    cloth_settings.shrink_min = shrink_min
    
    # Note: max_sewing_dist is not directly exposed in newer Blender versions
    # The sewing works based on vertex groups instead
    
    print(f"  ✓ Sewing springs ENABLED:")
    print(f"      - sewing_force_max: {sewing_force}")
    print(f"      - shrink_min: {shrink_min}")
    print(f"      - use_sewing_springs: True")
    
    return True


def mark_all_seam_edges(panels: dict):
    """
    Mark seam edges on all panels based on loaded seam data.
    
    This walks through all seam pairs and marks corresponding
    edges on the panel meshes.
    
    Args:
        panels: Dictionary of panel mesh objects
    """
    if not SEAM_DATA["loaded"]:
        print("  ⚠ No seam data loaded, skipping edge marking")
        return
    
    print("→ Marking seam edges on panel meshes...")
    
    # Resolve panel names to objects
    panel_map = resolve_panel_objects(panels)
    
    # Process each seam pair
    for seam_pair in SEAM_DATA["seams"]:
        if not isinstance(seam_pair, list) or len(seam_pair) != 2:
            continue
        
        # Parse both sides of the seam
        panel1_name, edge1_name = parse_seam_pair(seam_pair[0])
        panel2_name, edge2_name = parse_seam_pair(seam_pair[1])
        
        # Get panel objects
        obj1 = panel_map.get(panel1_name)
        obj2 = panel_map.get(panel2_name)
        
        if not obj1:
            # Try lowercase
            for key, obj in panel_map.items():
                if key.lower() == panel1_name.lower():
                    obj1 = obj
                    break
        
        if not obj2:
            for key, obj in panel_map.items():
                if key.lower() == panel2_name.lower():
                    obj2 = obj
                    break
        
        # Get edge vertex coordinates from seam data
        edge1_verts = get_panel_edge_vertices(panel1_name, edge1_name)
        edge2_verts = get_panel_edge_vertices(panel2_name, edge2_name)
        
        # Find and mark edges on each panel
        if obj1 and edge1_verts:
            edge_indices = find_edge_indices_by_position(obj1, edge1_verts)
            if edge_indices:
                mark_edges_as_seam(obj1, edge_indices, f"{panel1_name}:{edge1_name}")
        
        if obj2 and edge2_verts:
            edge_indices = find_edge_indices_by_position(obj2, edge2_verts)
            if edge_indices:
                mark_edges_as_seam(obj2, edge_indices, f"{panel2_name}:{edge2_name}")
    
    print(f"  ✓ Seam edge marking complete")


def get_edge_vertices_by_direction(mesh_obj: bpy.types.Object, 
                                    direction: str,
                                    tolerance: float = 0.02) -> list:
    """
    Robust vertex selector that handles CURVES (like armholes) using 
    Sector Logic instead of just Bounding Box Logic.
    """
    mesh = mesh_obj.data
    matrix = mesh_obj.matrix_world
    
    # Get Bounds
    coords = [matrix @ Vector(v.co) for v in mesh.vertices]
    if not coords: return []
    
    min_x, max_x = min(c.x for c in coords), max(c.x for c in coords)
    min_y, max_y = min(c.y for c in coords), max(c.y for c in coords)
    min_z, max_z = min(c.z for c in coords), max(c.z for c in coords)
    
    width = max_x - min_x
    height = max_z - min_z  # Assuming Z is up (standing) or Y is up (flat)
    
    edge_verts = []
    
    for i, v in enumerate(mesh.vertices):
        co = matrix @ Vector(v.co)
        
        # --- LOGIC UPGRADE: SECTORS ---
        # Instead of just "Left Edge", we define "Zones"
        
        match = False
        
        # 1. Straight Edges (Classic Bounding Box)
        if direction == "left" and abs(co.x - min_x) < tolerance: match = True
        elif direction == "right" and abs(co.x - max_x) < tolerance: match = True
        elif direction == "top" and abs(co.z - max_z) < tolerance: match = True
        elif direction == "bottom" and abs(co.z - min_z) < tolerance: match = True
        
        # 2. Curved Zones (The Fix for Armholes/Necks)
        # Armhole Left: Upper-Left Quadrant, but NOT the shoulder top or side straight
        elif direction == "armhole_left":
            # Check if vertex is in the top-left 30% of the mesh
            if (co.x < min_x + width * 0.3) and (co.z > max_z - height * 0.4):
                # Exclude the very top (shoulder) and very left (side seam)
                if abs(co.z - max_z) > tolerance and abs(co.x - min_x) > tolerance:
                    match = True

        # Armhole Right: Upper-Right Quadrant
        elif direction == "armhole_right":
            if (co.x > max_x - width * 0.3) and (co.z > max_z - height * 0.4):
                if abs(co.z - max_z) > tolerance and abs(co.x - max_x) > tolerance:
                    match = True

        if match:
            edge_verts.append(i)
            
    return edge_verts


def create_vertex_group_for_edge(obj: bpy.types.Object, 
                                  group_name: str,
                                  vertex_indices: list,
                                  weight: float = 1.0):
    """
    Create or update a vertex group with specified vertices.
    
    Vertex groups are how Blender marks which vertices should be sewn.
    Each sewing edge needs its own vertex group.
    
    Args:
        obj: The mesh object
        group_name: Name for the vertex group
        vertex_indices: List of vertex indices to add
        weight: Weight for the vertices (1.0 = fully included)
    """
    # Get or create vertex group
    if group_name in obj.vertex_groups:
        vg = obj.vertex_groups[group_name]
    else:
        vg = obj.vertex_groups.new(name=group_name)
    
    # Add vertices to group
    vg.add(vertex_indices, weight, 'ADD')
    
    return vg


def setup_seams_from_definitions(panels: dict, seam_defs: list):
    """
    Set up sewing vertex groups based on seam definitions.
    
    This maps the abstract seam definitions to actual vertices in the
    Blender meshes. After subdivision, we find edges by their position
    rather than vertex indices.
    
    Args:
        panels: Dictionary of pattern piece mesh objects
        seam_defs: List of seam definitions from seams.json
    """
    if not seam_defs:
        print("  No seam definitions - using default sewing setup")
        return
    
    print("→ Setting up seams from definitions...")
    
    # Map piece names to objects
    piece_map = {
        "front": panels.get("front"),
        "back": panels.get("back"),
        "sleeve": panels.get("left_sleeve"),  # We'll mirror for right
    }
    
    # Edge direction mapping based on seam names
    # This translates pattern edges to mesh positions
    edge_to_direction = {
        # Front panel edges
        "left_edge": "left",
        "right_edge": "right",
        "shoulder_left": "top",    # Approximation
        "shoulder_right": "top",
        "armhole_left": "left",    # Upper left area
        "armhole_right": "right",  # Upper right area
        
        # Back panel edges (mirror of front)
        
        # Sleeve edges
        "top": "top",
        "bottom": "bottom", 
        "cap": "top",              # Sleeve cap
        "underarm": "bottom",
    }
    
    seam_count = 0
    
    for seam in seam_defs:
        seam_name = seam.get("name", f"seam_{seam_count}")
        edge1 = seam.get("edge1", {})
        edge2 = seam.get("edge2", {})
        
        piece1_name = edge1.get("piece", "")
        piece2_name = edge2.get("piece", "")
        edge1_name = edge1.get("edge_name", "")
        edge2_name = edge2.get("edge_name", "")
        
        # Get mesh objects
        obj1 = piece_map.get(piece1_name)
        obj2 = piece_map.get(piece2_name)
        
        if not obj1 or not obj2:
            print(f"    ⚠ Skipping {seam_name}: piece not found")
            continue
        
        # Get edge directions
        dir1 = edge_to_direction.get(edge1_name, "left")
        dir2 = edge_to_direction.get(edge2_name, "left")
        
        # Find vertices on each edge
        verts1 = get_edge_vertices_by_direction(obj1, dir1)
        verts2 = get_edge_vertices_by_direction(obj2, dir2)
        
        if verts1 and verts2:
            # Create vertex groups
            group_name = f"sew_{seam_name}"
            create_vertex_group_for_edge(obj1, group_name, verts1)
            create_vertex_group_for_edge(obj2, group_name, verts2)
            print(f"    ✓ {seam_name}: {len(verts1)} ↔ {len(verts2)} vertices")
            seam_count += 1
        else:
            print(f"    ⚠ {seam_name}: no vertices found (v1={len(verts1)}, v2={len(verts2)})")
    
    print(f"  ✓ Created {seam_count} seam vertex groups")


def setup_default_seams(panels: dict):
    """
    Set up default sewing seams when no seam definitions are available.
    
    Creates sewing groups for:
    - Side seams (front left ↔ back left, front right ↔ back right)
    - Shoulder seams (front top ↔ back top)
    
    Args:
        panels: Dictionary of pattern piece mesh objects
    """
    print("→ Setting up default sewing seams...")
    
    front = panels.get("front")
    back = panels.get("back")
    
    if not front or not back:
        print("  ⚠ Cannot create seams: front or back panel missing")
        return
    
    # Side seams: connect left edges of front and back
    front_left = get_edge_vertices_by_direction(front, "left")
    back_left = get_edge_vertices_by_direction(back, "left")
    
    if front_left and back_left:
        create_vertex_group_for_edge(front, "sew_left_side", front_left)
        create_vertex_group_for_edge(back, "sew_left_side", back_left)
        print(f"  ✓ Left side seam: {len(front_left)} ↔ {len(back_left)} vertices")
    
    # Right side seam
    front_right = get_edge_vertices_by_direction(front, "right")
    back_right = get_edge_vertices_by_direction(back, "right")
    
    if front_right and back_right:
        create_vertex_group_for_edge(front, "sew_right_side", front_right)
        create_vertex_group_for_edge(back, "sew_right_side", back_right)
        print(f"  ✓ Right side seam: {len(front_right)} ↔ {len(back_right)} vertices")
    
    # Shoulder seams (top edge)
    front_top = get_edge_vertices_by_direction(front, "top")
    back_top = get_edge_vertices_by_direction(back, "top")
    
    if front_top and back_top:
        create_vertex_group_for_edge(front, "sew_shoulders", front_top)
        create_vertex_group_for_edge(back, "sew_shoulders", back_top)
        print(f"  ✓ Shoulder seam: {len(front_top)} ↔ {len(back_top)} vertices")


# ============================================================
# UTILITY FUNCTIONS
# ============================================================

def clear_scene():
    """
    Aggressively removes all objects AND data blocks to free RAM.
    """
    print("→ Clearing scene and purging memory...")
    
    # 1. Delete all objects in current scene
    bpy.ops.object.select_all(action='SELECT')
    bpy.ops.object.delete()
    
    # 2. Force remove all data blocks (Meshes, Materials, Curves, etc.)
    # Blender keeps these in memory ("Orphan Data") even after objects are deleted
    for block in bpy.data.meshes:
        bpy.data.meshes.remove(block)
        
    for block in bpy.data.materials:
        bpy.data.materials.remove(block)
        
    for block in bpy.data.curves:
        bpy.data.curves.remove(block)
        
    for block in bpy.data.images:
        bpy.data.images.remove(block)

    # 3. Explicitly call Python Garbage Collector
    gc.collect()
    
    print("  ✓ Scene cleared & RAM purged")


def setup_scene(simulation_frames: int = 60):
    """
    Set up the scene for cloth simulation with sewing.
    
    This includes:
    - Setting units to metric
    - Setting frame range for simulation (default: 60 frames)
    - Adding ground plane (for reference)
    - Configuring gravity
    
    60 frames is optimized for memory-constrained systems:
    - Frames 1-20: Initial sewing spring engagement
    - Frames 20-40: Edges pulling together, fabric draping
    - Frames 40-60: Final settling and stabilization
    
    Args:
        simulation_frames: Number of frames for simulation (default: 60)
    """
    print("→ Setting up scene for sewing simulation...")
    
    # Set units to metric (meters)
    bpy.context.scene.unit_settings.system = 'METRIC'
    bpy.context.scene.unit_settings.scale_length = 1.0
    
    # Set frame range for simulation
    bpy.context.scene.frame_start = 1
    bpy.context.scene.frame_end = simulation_frames
    bpy.context.scene.frame_current = 1
    
    # Configure gravity (standard Earth gravity)
    bpy.context.scene.gravity = (0, 0, -9.81)
    
    # Add ground plane for reference (not for collision in this setup)
    bpy.ops.mesh.primitive_plane_add(size=2, location=(0, 0, -0.5))
    ground = bpy.context.active_object
    ground.name = "Ground_Reference"
    
    print(f"  ✓ Scene configured:")
    print(f"      - Frame range: 1 to {simulation_frames}")
    print(f"      - Gravity: -9.81 m/s²")
    print(f"      - Units: Metric (meters)")
    
    return ground


def import_svg_as_curve(svg_path: Path, name: str) -> bpy.types.Object:
    """
    Import an SVG file as a curve object.
    
    Blender can directly import SVG files as curve objects.
    The curve represents the outline of the pattern piece.
    
    Args:
        svg_path: Path to the SVG file
        name: Name for the imported object
    
    Returns:
        The imported curve object
    """
    print(f"→ Importing {name} from {svg_path.name}...")
    
    # Import SVG
    bpy.ops.import_curve.svg(filepath=str(svg_path))
    
    # SVG import creates a collection, get the curves from it
    # The imported objects are selected after import
    imported_objects = bpy.context.selected_objects
    
    if not imported_objects:
        print(f"  ✗ Failed to import {svg_path}")
        return None
    
    # Usually SVG imports as multiple curves, join them
    curve_obj = imported_objects[0]
    curve_obj.name = f"{name}_curve"
    
    print(f"  ✓ Imported as curve: {curve_obj.name}")
    
    return curve_obj


def curve_to_mesh(curve_obj: bpy.types.Object, name: str) -> bpy.types.Object:
    """
    Convert a curve to a mesh.
    
    Cloth simulation needs a MESH (vertices, edges, faces).
    We convert the curve outline to a flat mesh with faces.
    
    Steps:
    1. Convert curve to mesh (just edges)
    2. Fill the outline to create a face
    3. Subdivide for smooth simulation
    
    Args:
        curve_obj: The curve object to convert
        name: Name for the new mesh
    
    Returns:
        The mesh object
    """
    print(f"→ Converting {curve_obj.name} to mesh...")
    
    # Select and make active
    bpy.ops.object.select_all(action='DESELECT')
    curve_obj.select_set(True)
    bpy.context.view_layer.objects.active = curve_obj
    
    # Convert curve to mesh
    bpy.ops.object.convert(target='MESH')
    
    mesh_obj = bpy.context.active_object
    mesh_obj.name = name
    
    # Enter edit mode to fill and subdivide
    bpy.ops.object.mode_set(mode='EDIT')
    
    # Select all vertices
    bpy.ops.mesh.select_all(action='SELECT')
    
    # Fill the outline to create a face
    # edge_fill creates an n-gon face from the boundary
    try:
        bpy.ops.mesh.edge_face_add()
    except:
        # If that fails, try fill
        bpy.ops.mesh.fill()
    
    # Subdivide for smoother simulation
    # More vertices = smoother cloth behavior
    bpy.ops.mesh.subdivide(number_cuts=3)
    
    # Triangulate for cloth simulation (works better with tris)
    bpy.ops.mesh.quads_convert_to_tris()
    
    # Exit edit mode
    bpy.ops.object.mode_set(mode='OBJECT')
    
    # Apply scale (important for physics)
    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
    
    # Force garbage collection after mesh operations
    gc.collect()
    
    vertex_count = len(mesh_obj.data.vertices)
    print(f"  ✓ Created mesh with {vertex_count} vertices")
    
    return mesh_obj


def create_neck_band_mesh(points: list, name: str, 
                          target_vertices: int = 48,
                          max_vertices: int = 64,
                          min_vertices: int = 24) -> bpy.types.Object:
    """
    Create a neck band mesh with CONTROLLED vertex count.
    
    XML Task: Fix_Neck_Band_Generation
    
    This function creates a mesh with strict vertex limits to prevent
    solver overload. Unlike regular pattern pieces, the neck band:
    - Has NO subdivision (AllowSubdivision=false)
    - Uses fixed vertex count (target=48)
    - Caps vertices at max (64)
    - Uses uniform spacing
    
    Args:
        points: List of (x, y) tuples defining rectangle outline
        name: Name for the mesh
        target_vertices: Target vertex count (default: 48)
        max_vertices: Maximum allowed vertices (default: 64)
        min_vertices: Minimum required vertices (default: 24)
    
    Returns:
        The mesh object with controlled vertex count
    """
    print(f"→ Creating neck band mesh for {name} (controlled vertices)...")
    
    # Validate input
    if len(points) < 4:
        raise ValueError(f"Neck band requires at least 4 points, got {len(points)}")
    
    # Get band dimensions from points
    min_x = min(p[0] for p in points)
    max_x = max(p[0] for p in points)
    min_y = min(p[1] for p in points)
    max_y = max(p[1] for p in points)
    
    band_length = max_x - min_x
    band_height = max_y - min_y
    
    # Calculate grid subdivision for target vertices
    # Rectangle: vertices = (nx + 1) * (ny + 1)
    # For a long thin band, we want more divisions along length
    aspect_ratio = band_length / band_height if band_height > 0 else 10
    
    # Distribute vertices proportionally
    ny = max(2, int(math.sqrt(target_vertices / aspect_ratio)))
    nx = max(4, int(target_vertices / (ny + 1)) - 1)
    
    # Calculate actual vertex count
    actual_vertices = (nx + 1) * (ny + 1)
    
    # Cap at max_vertices
    if actual_vertices > max_vertices:
        scale = math.sqrt(max_vertices / actual_vertices)
        nx = max(4, int(nx * scale))
        ny = max(2, int(ny * scale))
        actual_vertices = (nx + 1) * (ny + 1)
        print(f"    ⚠ Capping vertices from {(nx+1)*(ny+1)} to {actual_vertices} (max={max_vertices})")
    
    # Ensure minimum
    if actual_vertices < min_vertices:
        nx = max(nx, 6)
        ny = max(ny, 3)
        actual_vertices = (nx + 1) * (ny + 1)
        print(f"    ⚠ Boosting vertices to {actual_vertices} (min={min_vertices})")
    
    print(f"    Grid: {nx}x{ny} = {actual_vertices} vertices (target={target_vertices})")
    
    # Create new mesh
    mesh = bpy.data.meshes.new(f"{name}_mesh")
    obj = bpy.data.objects.new(name, mesh)
    
    # Link to scene
    bpy.context.collection.objects.link(obj)
    
    # Create BMesh for controlled mesh construction
    bm = bmesh.new()
    
    # Create grid of vertices with UNIFORM spacing
    # XML: <UniformSpacing enabled="true"/>
    vert_grid = []
    for j in range(ny + 1):
        row = []
        for i in range(nx + 1):
            x = min_x + (i / nx) * band_length
            y = min_y + (j / ny) * band_height
            v = bm.verts.new((x * CM_TO_M, y * CM_TO_M, 0))
            row.append(v)
        vert_grid.append(row)
    
    bm.verts.ensure_lookup_table()
    
    # Create faces (quads for uniform spacing)
    for j in range(ny):
        for i in range(nx):
            v1 = vert_grid[j][i]
            v2 = vert_grid[j][i+1]
            v3 = vert_grid[j+1][i+1]
            v4 = vert_grid[j+1][i]
            try:
                bm.faces.new([v1, v2, v3, v4])
            except:
                pass
    
    # Update mesh
    bm.to_mesh(mesh)
    bm.free()
    
    # Force garbage collection
    gc.collect()
    
    # NO SUBDIVISION for neck band
    # XML: <AllowSubdivision value="false"/>
    
    # Just triangulate for cloth simulation
    bpy.context.view_layer.objects.active = obj
    obj.select_set(True)
    bpy.ops.object.mode_set(mode='EDIT')
    bpy.ops.mesh.select_all(action='SELECT')
    bpy.ops.mesh.quads_convert_to_tris()
    bpy.ops.object.mode_set(mode='OBJECT')
    
    gc.collect()
    
    final_vertex_count = len(obj.data.vertices)
    print(f"  ✓ Created {name} with {final_vertex_count} vertices (NO subdivision)")
    
    return obj


def create_pattern_mesh_from_points(points: list, name: str) -> bpy.types.Object:
    """
    Create a mesh directly from pattern outline points.
    
    This is an alternative to SVG import - creates mesh directly
    from the coordinate data.
    
    Args:
        points: List of (x, y) tuples defining the outline
        name: Name for the mesh
    
    Returns:
        The mesh object
    """
    print(f"→ Creating mesh for {name}...")
    
    # Create new mesh
    mesh = bpy.data.meshes.new(f"{name}_mesh")
    obj = bpy.data.objects.new(name, mesh)
    
    # Link to scene
    bpy.context.collection.objects.link(obj)
    
    # Create BMesh for easier mesh construction
    bm = bmesh.new()
    
    # Add vertices (convert cm to meters, Z=0 for flat pattern)
    verts = []
    for x, y in points:
        v = bm.verts.new((x * CM_TO_M, y * CM_TO_M, 0))
        verts.append(v)
    
    bm.verts.ensure_lookup_table()
    
    # Create edges connecting consecutive vertices
    for i in range(len(verts)):
        bm.edges.new((verts[i], verts[(i + 1) % len(verts)]))
    
    # Create face from all vertices (the pattern piece)
    try:
        bm.faces.new(verts)
    except:
        print(f"  ⚠ Could not create face for {name}")
    
    # Update mesh
    bm.to_mesh(mesh)
    bm.free()
    
    # Force garbage collection after bmesh operations
    gc.collect()
    
    # Subdivide for simulation (REDUCED to save memory)
    # Original: 4 cuts = thousands of vertices = memory overflow
    # Fixed: 2 cuts = manageable vertex count
    bpy.context.view_layer.objects.active = obj
    obj.select_set(True)
    
    bpy.ops.object.mode_set(mode='EDIT')
    bpy.ops.mesh.select_all(action='SELECT')
    bpy.ops.mesh.subdivide(number_cuts=2)  # REDUCED from 4 to prevent OOM
    bpy.ops.mesh.quads_convert_to_tris()
    bpy.ops.object.mode_set(mode='OBJECT')
    
    # Aggressive garbage collection after subdivision
    gc.collect()
    
    vertex_count = len(obj.data.vertices)
    if vertex_count > 500:
        print(f"  ⚠ {name} has {vertex_count} vertices (consider reducing)")
    else:
        print(f"  ✓ Created {name} with {vertex_count} vertices")
    
    return obj


def position_pattern_pieces(front: bpy.types.Object, 
                           back: bpy.types.Object,
                           left_sleeve: bpy.types.Object,
                           right_sleeve: bpy.types.Object,
                           neck_band: bpy.types.Object = None,
                           lift_height: float = 0.6):
    """
    Position pattern pieces for sewing ABOVE the avatar.
    
    Like laying out fabric before sewing:
    - Front and back face each other (will be sewn at sides)
    - Sleeves positioned at armholes
    - Neck band positioned at neckline (XML Schema v1.1)
    - ALL pieces lifted above avatar for gravity drop
    
    The pieces start FLAT and ELEVATED. During simulation:
    1. Gravity pulls them down onto the avatar
    2. Sewing springs pull edges together
    3. Collision keeps fabric on body surface
    
    Layout (top view):
    
                 LEFT_SLEEVE
                      │
              ┌───NECK_BAND───┐
         ┌────────────┼────────────┐
         │            │            │
    FRONT│            │            │BACK
         │            │            │
         └────────────┼────────────┘
                      │
                RIGHT_SLEEVE
    
    Args:
        front: Front panel mesh
        back: Back panel mesh
        left_sleeve: Left sleeve mesh (optional)
        right_sleeve: Right sleeve mesh (optional)
        neck_band: Neck band mesh (optional, XML Schema v1.1)
        lift_height: Height to lift panels above origin (meters)
    """
    print("→ Positioning pattern pieces for sewing...")
    print(f"  Lift height: {lift_height}m above avatar")
    
    # Get dimensions of front panel for reference
    front_dims = front.dimensions
    panel_width = front_dims.x
    panel_height = front_dims.y
    
    # Position FRONT (left side, facing right, LIFTED)
    front.location = Vector((-panel_width * 0.6, 0, lift_height))
    front.rotation_euler = (math.radians(90), 0, 0)  # Stand up vertically
    print(f"  ✓ Front positioned at z={lift_height}m")
    
    # Position BACK (right side, facing left - mirror of front, LIFTED)
    back.location = Vector((panel_width * 0.6, 0, lift_height))
    back.rotation_euler = (math.radians(90), 0, math.radians(180))  # Rotated to face front
    print(f"  ✓ Back positioned at z={lift_height}m")
    
    # Position LEFT SLEEVE (top, LIFTED)
    if left_sleeve:
        sleeve_width = left_sleeve.dimensions.x
        left_sleeve.location = Vector((0, panel_width * 0.5, lift_height + panel_height * 0.2))
        left_sleeve.rotation_euler = (math.radians(90), 0, math.radians(-90))
        print(f"  ✓ Left sleeve positioned at z={lift_height + panel_height * 0.2:.2f}m")
    
    # Position RIGHT SLEEVE (bottom, mirror of left, LIFTED)
    if right_sleeve:
        right_sleeve.location = Vector((0, -panel_width * 0.5, lift_height + panel_height * 0.2))
        right_sleeve.rotation_euler = (math.radians(90), 0, math.radians(90))
        print(f"  ✓ Right sleeve positioned at z={lift_height + panel_height * 0.2:.2f}m")
    
    # Position NECK BAND (at top of front/back neckline area, LIFTED)
    if neck_band:
        neck_band.location = Vector((0, 0, lift_height + panel_height * 0.5))
        neck_band.rotation_euler = (math.radians(90), 0, 0)  # Horizontal orientation
        print(f"  ✓ Neck band positioned at z={lift_height + panel_height * 0.5:.2f}m")
    
    print(f"  ✓ All panels positioned {lift_height}m above avatar")
    print("    Panels will fall and sew together during simulation")


def add_cloth_modifier(obj: bpy.types.Object, enable_sewing: bool = True, 
                       disable_self_collision: bool = False):
    """
    Add cloth physics to a mesh object.
    
    The cloth modifier makes the mesh behave like fabric:
    - It responds to gravity
    - It can collide with other objects
    - It can be sewn to other cloth objects via sewing springs
    
    XML Task: For neck band, disable self-collision to prevent solver overload:
        <Cloth>
            <EnableSewingSprings value="true"/>
            <EnableSelfCollision value="false"/>
        </Cloth>
    
    Args:
        obj: The mesh object to add cloth to
        enable_sewing: Whether to enable sewing springs
        disable_self_collision: Whether to disable self-collision (for neck band)
    """
    print(f"→ Adding cloth physics to {obj.name}...")
    
    # Add cloth modifier
    cloth_mod = obj.modifiers.new(name="Cloth", type='CLOTH')
    
    # Configure cloth settings
    cloth = cloth_mod.settings
    
    # Quality (more steps = more accurate but slower)
    cloth.quality = CLOTH_SETTINGS["quality"]
    
    # Mass (kg per square meter)
    cloth.mass = CLOTH_SETTINGS["mass"]
    
    # Stiffness (how much fabric resists deformation)
    cloth.tension_stiffness = CLOTH_SETTINGS["tension_stiffness"]
    cloth.compression_stiffness = CLOTH_SETTINGS["compression_stiffness"]
    cloth.bending_stiffness = CLOTH_SETTINGS["bending_stiffness"]
    
    # Damping (reduces oscillation)
    cloth.air_damping = CLOTH_SETTINGS["air_damping"]
    
    # Enable pressure (helps maintain volume)
    cloth.use_pressure = True
    cloth.uniform_pressure_force = 0.5
    
    # ==========================================
    # SELF-COLLISION (XML Task: neck band = disabled)
    # ==========================================
    if disable_self_collision:
        cloth_mod.collision_settings.use_self_collision = False
        print(f"  ✓ Self-collision DISABLED (per XML Task)")
    else:
        cloth_mod.collision_settings.use_self_collision = True
    
    # ==========================================
    # SEWING SPRINGS - This is the key feature!
    # ==========================================
    if enable_sewing:
        cloth.use_sewing_springs = True
        cloth.sewing_force_max = SEWING_SETTINGS["force"]
        cloth.shrink_min = SEWING_SETTINGS["shrink_min"]
        print(f"  ✓ Sewing springs ENABLED (force={SEWING_SETTINGS['force']})")
    else:
        cloth.use_sewing_springs = False
        print(f"  ⚠ Sewing springs disabled")
    
    print(f"  ✓ Cloth modifier added to {obj.name}")


def create_sewing_springs(obj1: bpy.types.Object, 
                          obj2: bpy.types.Object,
                          edge_type: str):
    """
    Create vertex group for sewing between two pattern pieces.
    
    Sewing in Blender cloth simulation works by:
    1. Selecting vertices on the edge to be sewn
    2. Creating a vertex group for these vertices
    3. The cloth solver pulls matching edges together
    
    Args:
        obj1: First pattern piece
        obj2: Second pattern piece  
        edge_type: Type of seam ("side", "shoulder", "sleeve")
    
    This is a simplified version - real sewing would need
    exact edge matching based on pattern markings.
    """
    print(f"→ Setting up {edge_type} seam between {obj1.name} and {obj2.name}...")
    
    # Create vertex groups for the seam edges
    # In production, you'd select specific vertices based on pattern data
    
    group_name = f"sew_{edge_type}"
    
    # Add vertex group to first object
    if group_name not in obj1.vertex_groups:
        vg1 = obj1.vertex_groups.new(name=group_name)
    else:
        vg1 = obj1.vertex_groups[group_name]
    
    # Add vertex group to second object
    if group_name not in obj2.vertex_groups:
        vg2 = obj2.vertex_groups.new(name=group_name)
    else:
        vg2 = obj2.vertex_groups[group_name]
    
    print(f"  ✓ Created sewing groups: {group_name}")


def setup_sewing_constraint(cloth_obj: bpy.types.Object, vertex_group: str):
    """
    Configure cloth modifier to use sewing.
    
    The sewing constraint in Blender's cloth simulation:
    - Finds vertices in the sewing vertex group
    - Creates springs that pull them toward matching vertices
    - Over simulation time, edges come together like actual sewing
    
    Args:
        cloth_obj: Object with cloth modifier
        vertex_group: Name of vertex group with sewing vertices
    """
    # Get the cloth modifier
    cloth_mod = None
    for mod in cloth_obj.modifiers:
        if mod.type == 'CLOTH':
            cloth_mod = mod
            break
    
    if cloth_mod is None:
        print(f"  ⚠ No cloth modifier on {cloth_obj.name}")
        return
    
    # Enable sewing
    cloth_mod.settings.use_sewing_springs = True
    cloth_mod.settings.sewing_force_max = SEWING_SETTINGS["force"]
    
    # Set the vertex group for sewing
    cloth_mod.settings.vertex_group_mass = vertex_group


def join_pattern_pieces(pieces: list, name: str) -> bpy.types.Object:
    """
    Join multiple pattern pieces into a single object.
    
    For cloth simulation, it's easier to have one object
    with all pattern pieces. Sewing then happens between
    different vertex groups within that object.
    
    Args:
        pieces: List of mesh objects to join
        name: Name for the combined object
    
    Returns:
        The joined object
    """
    print(f"→ Joining pattern pieces into {name}...")
    
    # Deselect all
    bpy.ops.object.select_all(action='DESELECT')
    
    # Select all pieces
    for piece in pieces:
        if piece:
            piece.select_set(True)
    
    # Make first piece active
    bpy.context.view_layer.objects.active = pieces[0]
    
    # Join
    bpy.ops.object.join()
    
    # Rename and verify
    joined = bpy.context.active_object
    joined.name = name
    
    # Force exact naming (in case Blender adds .001 suffix)
    if joined.name != name:
        # Remove any existing object with this name
        existing = bpy.data.objects.get(name)
        if existing and existing != joined:
            bpy.data.objects.remove(existing, do_unlink=True)
        joined.name = name
    
    print(f"  ✓ Created combined garment: {joined.name}")
    print(f"  ✓ Garment object name confirmed: '{joined.name}'")
    
    return joined


# REMOVED: Avatar creation (simple mannequin)
# Reason: Garment-only mode — simulation runs in free space without any avatar.


# REMOVED: Anatomical avatar generation and collision setup
# Reason: Garment-only mode — no collision body used.


# ============================================================
# AVATAR IMPORT AND COLLISION (ENHANCED)
# ============================================================

# Default collision settings for realistic cloth behavior
COLLISION_SETTINGS = {
    "thickness_outer": 0.015,    # 1.5cm outer collision margin
    "thickness_inner": 0.01,     # 1cm inner collision margin
    "damping": 0.5,              # Velocity absorption (0-1)
    "cloth_friction": 1.5,       # How much cloth sticks (0-10)
    "use_culling": False,        # Check both sides of faces
}


# Avatar import (FBX) removed — garment-only mode


# Avatar import (GLB/GLTF) removed — garment-only mode


# Collision modifiers removed — garment-only mode (free-space simulation).


# Avatar import/setup removed — garment-only mode.


# REMOVED: Avatar-relative garment positioning — panels are positioned in free space.


def run_simulation(frames: int = 150):
    """
    Run the cloth simulation.
    
    This bakes the simulation - calculating cloth position
    for each frame. The sewing springs pull edges together
    while gravity pulls the fabric down.
    
    Args:
        frames: Number of frames to simulate
    """
    print(f"→ Running simulation for {frames} frames...")
    print("  (This may take a few minutes)")
    
    # Set frame range
    bpy.context.scene.frame_end = frames
    
    # Go to frame 1
    bpy.context.scene.frame_set(1)
    
    # Bake simulation
    # In Blender UI this would be: Physics > Cloth > Cache > Bake
    # Programmatically, we just step through frames
    
    for frame in range(1, frames + 1):
        bpy.context.scene.frame_set(frame)
        
        # Print progress every 30 frames
        if frame % 30 == 0:
            print(f"  Frame {frame}/{frames}...")
    
    print(f"  ✓ Simulation complete")


def bake_simulation(garment: bpy.types.Object, frames: int = 60):
    """
    Bake the cloth simulation to cache.
    
    Baking pre-calculates all simulation frames so playback is instant.
    This is more reliable than stepping through frames manually.
    
    60 frames is sufficient for memory-constrained systems:
    - Sewing springs to pull edges together (~20-30 frames)
    - Fabric settling (~30-50 frames)
    - Final stabilization (~50-60 frames)
    
    Args:
        garment: The garment object with cloth modifier
        frames: Number of frames to bake (default: 120)
    
    Returns:
        True if bake succeeded, False otherwise
    """
    print(f"\n→ Baking cloth simulation ({frames} frames)...")
    print("  This may take several minutes...")
    print("  Progress:")
    
    # Find the cloth modifier
    cloth_mod = None
    for mod in garment.modifiers:
        if mod.type == 'CLOTH':
            cloth_mod = mod
            break
    
    if not cloth_mod:
        print("  ✗ No cloth modifier found!")
        return False
    
    # Set frame range for scene
    bpy.context.scene.frame_start = 1
    bpy.context.scene.frame_end = frames
    
    # Configure cache for baking
    point_cache = cloth_mod.point_cache
    point_cache.frame_start = 1
    point_cache.frame_end = frames
    
    # Select the garment
    bpy.ops.object.select_all(action='DESELECT')
    garment.select_set(True)
    bpy.context.view_layer.objects.active = garment
    
    # Bake the simulation using Blender's built-in operator
    try:
        # Free any existing bake first
        bpy.ops.ptcache.free_bake_all()
        
        # Bake all physics caches
        bpy.ops.ptcache.bake_all(bake=True)
        
        print(f"  ✓ Simulation baked successfully ({frames} frames)")
        return True
        
    except Exception as e:
        print(f"  ⚠ Bake operator failed: {e}")
        print("  Falling back to frame-by-frame bake...")
        
        # Fallback: step through frames manually
        # This forces Blender to calculate each frame
        for frame in range(1, frames + 1):
            bpy.context.scene.frame_set(frame)
            
            # Print progress every 20 frames
            if frame % 20 == 0:
                progress = (frame / frames) * 100
                print(f"    Frame {frame}/{frames} ({progress:.0f}%)")
        
        print(f"  ✓ Frame-by-frame bake complete ({frames} frames)")
        return True


def setup_simulation_cache(garment: bpy.types.Object, 
                            frames: int = 60,
                            cache_step: int = 1):
    """
    Configure the simulation cache settings before baking.
    
    Args:
        garment: Garment with cloth modifier
        frames: Total simulation frames
        cache_step: Frame step for caching (1 = every frame)
    """
    # Find cloth modifier
    cloth_mod = None
    for mod in garment.modifiers:
        if mod.type == 'CLOTH':
            cloth_mod = mod
            break
    
    if not cloth_mod:
        return
    
    # Configure point cache
    cache = cloth_mod.point_cache
    cache.frame_start = 1
    cache.frame_end = frames
    if hasattr(cache, "step"):
        cache.step = cache_step
    cache.use_disk_cache = True
    
    # Use disk cache for large simulations
   
    
    print(f"  ✓ Cache configured: frames 1-{frames}, step={cache_step}")


def auto_bake_cloth_simulation(garment: bpy.types.Object,
                                frames: int = 60,
                                quality: int = 8) -> bool:
    """
    Automatically configure and bake cloth simulation.
    
    This is the "one-click" bake function that:
    1. Verifies cloth modifier exists
    2. Sets optimal simulation parameters
    3. Configures cache
    4. Bakes the simulation
    5. Jumps to final frame
    
    Args:
        garment: The garment mesh with cloth modifier
        frames: Number of frames to simulate (default: 120)
        quality: Simulation quality steps (default: 12)
    
    Returns:
        True if bake succeeded
    """
    print("\n" + "="*50)
    print("   AUTO-BAKE CLOTH SIMULATION")
    print("="*50)
    
    # Verify garment has cloth modifier
    cloth_mod = None
    for mod in garment.modifiers:
        if mod.type == 'CLOTH':
            cloth_mod = mod
            break
    
    if not cloth_mod:
        print("  ✗ ERROR: No cloth modifier found on garment")
        print("    Add cloth modifier first with add_cloth_modifier()")
        return False
    
    # Verify sewing springs are enabled
    if not cloth_mod.settings.use_sewing_springs:
        print("  ⚠ WARNING: Sewing springs not enabled!")
        print("    Enabling sewing springs...")
        cloth_mod.settings.use_sewing_springs = True
        cloth_mod.settings.sewing_force_max = SEWING_SETTINGS["force"]
    
    # Set quality
    cloth_mod.settings.quality = quality
    
    # Set scene frame range
    bpy.context.scene.frame_start = 1
    bpy.context.scene.frame_end = frames
    bpy.context.scene.frame_current = 1
    
    print(f"\n  Simulation settings:")
    print(f"    - Frames: 1 to {frames}")
    print(f"    - Quality: {quality}")
    print(f"    - Sewing force: {cloth_mod.settings.sewing_force_max}")
    print(f"    - Sewing springs: ENABLED")
    
    # Setup cache
    setup_simulation_cache(garment, frames)
    
    # Bake
    success = bake_simulation(garment, frames)
    
    if success:
        # Jump to final frame to see result
        bpy.context.scene.frame_set(frames)
        print(f"\n  ✓ Jumped to final frame ({frames})")
        print("  ✓ Garment should now be sewn and draped on avatar")
    
    print("="*50)
    
    return success


def apply_simulation_as_mesh(garment: bpy.types.Object, frame: int = None) -> bpy.types.Object:
    """
    Apply the simulated cloth state as a static mesh.
    
    This "freezes" the simulation at a specific frame,
    converting the dynamic cloth to a static mesh that can be exported.
    
    Args:
        garment: The garment with cloth simulation
        frame: Frame to freeze at (default: last frame)
    
    Returns:
        The static mesh object (original is preserved)
    """
    print("→ Applying simulation as static mesh...")
    
    # Go to the target frame
    if frame is None:
        frame = bpy.context.scene.frame_end
    
    bpy.context.scene.frame_set(frame)
    print(f"  Using frame {frame}")
    
    # Select the garment
    bpy.ops.object.select_all(action='DESELECT')
    garment.select_set(True)
    bpy.context.view_layer.objects.active = garment
    
    # Duplicate the object
    bpy.ops.object.duplicate()
    static_garment = bpy.context.active_object
    static_garment.name = f"{garment.name}_Static"
    
    # Apply the cloth modifier (converts to static mesh)
    for mod in static_garment.modifiers:
        if mod.type == 'CLOTH':
            try:
                bpy.ops.object.modifier_apply(modifier=mod.name)
                print(f"  ✓ Applied cloth modifier")
            except Exception as e:
                print(f"  ⚠ Could not apply modifier: {e}")
                # Alternative: convert to mesh
                bpy.ops.object.convert(target='MESH')
    
    # Hide the original animated version
    garment.hide_viewport = True
    garment.hide_render = True
    
    print(f"  ✓ Created static mesh: {static_garment.name}")
    
    return static_garment


def export_garment(garment: bpy.types.Object, 
                   output_dir: str,
                   formats: list = None):
    """
    Export the garment mesh in multiple formats.
    
    Supported formats:
    - OBJ: Universal, widely supported
    - FBX: Good for game engines
    - GLB/GLTF: Web-friendly, includes materials
    
    Args:
        garment: The mesh object to export
        output_dir: Directory to save exports
        formats: List of formats to export (default: all)
    """
    if formats is None:
        formats = ["obj", "fbx", "glb"]
    
    print(f"→ Exporting garment to {output_dir}...")
    
    # Create output directory if needed
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)
    
    # Select only the garment
    bpy.ops.object.select_all(action='DESELECT')
    garment.select_set(True)
    bpy.context.view_layer.objects.active = garment
    
    base_name = garment.name.replace(" ", "_")
    
    for fmt in formats:
        filepath = str(output_path / f"{base_name}.{fmt}")
        
        try:
            if fmt.lower() == "obj":
                bpy.ops.wm.obj_export(
                    filepath=filepath,
                    export_selected_objects=True,
                    export_materials=True
                )
                print(f"  ✓ Exported: {base_name}.obj")
                
            elif fmt.lower() == "fbx":
                bpy.ops.export_scene.fbx(
                    filepath=filepath,
                    use_selection=True,
                    mesh_smooth_type='FACE'
                )
                print(f"  ✓ Exported: {base_name}.fbx")
                
            elif fmt.lower() in ["glb", "gltf"]:
                bpy.ops.export_scene.gltf(
                    filepath=filepath,
                    use_selection=True,
                    export_format='GLB' if fmt.lower() == "glb" else 'GLTF_SEPARATE'
                )
                print(f"  ✓ Exported: {base_name}.{fmt}")
                
        except Exception as e:
            print(f"  ✗ Failed to export {fmt}: {e}")
    
    print(f"  ✓ Export complete")


def save_garment(output_path: str):
    """
    Save the simulated garment.
    
    Args:
        output_path: Path to save the .blend file
    """
    bpy.ops.wm.save_as_mainfile(filepath=output_path)
    print(f"✓ Saved to: {output_path}")


def run_full_simulation_pipeline(garment: bpy.types.Object,
                                  output_dir: str = None,
                                  frames: int = 60,
                                  auto_export: bool = True):
    """
    Run the complete sewing simulation and export pipeline.
    
    This is the "one-click" function that:
    1. Auto-bakes the cloth simulation with sewing springs
    2. Applies the result as a static mesh at final frame
    3. Exports in multiple formats (OBJ, FBX, GLB)
    
    Args:
        garment: The garment with cloth physics and sewing springs
        output_dir: Where to save exports (default: pattern_output/exports)
        frames: Simulation frames (default: 60)
        auto_export: Whether to auto-export after simulation
    
    Returns:
        The static garment mesh
    """
    print("\n" + "="*60)
    print("   RUNNING FULL SEWING SIMULATION PIPELINE")
    print("="*60)
    
    # Verify garment exists
    if garment is None:
        raise ValueError("No garment object provided to run_full_simulation_pipeline")
    
    print(f"  Garment: {garment.name}")
    print(f"  Frames: {frames}")
    
    # Step 1: Auto-bake simulation with sewing
    print("\n" + "-"*40)
    success = auto_bake_cloth_simulation(garment, frames=frames)
    
    if not success:
        print("  ✗ Bake failed, attempting fallback...")
        bake_simulation(garment, frames)
    
    # Step 2: Apply as static mesh at final frame
    print("\n" + "-"*40)
    static_garment = apply_simulation_as_mesh(garment, frame=frames)
    
    # Step 3: Export
    if auto_export:
        print("\n" + "-"*40)
        if output_dir is None:
            output_dir = str(PATTERN_DIR / "exports")
        export_garment(static_garment, output_dir)
    
    print("\n" + "="*60)
    print("   SEWING SIMULATION PIPELINE COMPLETE ✅")
    print("="*60)
    print(f"""
Results:
  ✓ Cloth simulation baked ({frames} frames)
  ✓ Seams sewn together via sewing springs
  ✓ Static mesh created from final frame
  ✓ Garment draped on avatar collision body
""")
    if auto_export:
        print(f"  ✓ Exported to: {output_dir}/")
    
    return static_garment

import sys

if "--save" in sys.argv:
    idx = sys.argv.index("--save")
    out_path = sys.argv[idx + 1]
    bpy.ops.wm.save_as_mainfile(filepath=out_path)
    print(f"✓ Saved garment to: {out_path}")
# ============================================================
# ALTERNATIVE: MANUAL MESH CREATION
# ============================================================

def create_tshirt_panels_manually(measurements: dict) -> dict:
    """
    Create T-shirt panels directly from measurements.
    
    This bypasses SVG import and creates meshes directly
    using the same geometry as step4_pattern_generation.
    
    XML Schema v1.1 panels:
    - front_bodice (Front Panel)
    - back_bodice (Back Panel)
    - sleeve (Left/Right)
    - neck_band (Collar)
    
    Args:
        measurements: Dictionary with measurements (v1.1 format)
    
    Returns:
        Dictionary of mesh objects
    """
    print("→ Creating pattern meshes from measurements (XML Schema v1.1)...")
    
    # Core measurements
    chest = measurements.get("chest_flat", 50.0)
    length = measurements.get("body_length", 70.0)
    shoulder = measurements.get("shoulder_width", 44.0)
    sleeve_len = measurements.get("sleeve_length", 22.0)
    armhole = measurements.get("armhole_depth", 22.0)
    
    # Additional v1.1 measurements
    neck_width = measurements.get("neck_width", 18.0)
    neck_depth_front = measurements.get("neck_depth_front", 9.0)
    neck_depth_back = measurements.get("neck_depth_back", 3.0)
    band_height = measurements.get("neck_band_height", 4.0)
    band_reduction = measurements.get("neck_band_reduction", 0.12)
    
    panels = {}
    
    # FRONT PANEL (front_bodice)
    front_width = chest
    front_points = [
        (-front_width/2, 0),           # Top left
        (front_width/2, 0),            # Top right
        (front_width/2, length),       # Bottom right
        (-front_width/2, length),      # Bottom left
    ]
    panels["front"] = create_pattern_mesh_from_points(front_points, "Front_Panel")
    
    # BACK PANEL (back_bodice)
    back_points = [
        (-front_width/2, 0),
        (front_width/2, 0),
        (front_width/2, length),
        (-front_width/2, length),
    ]
    panels["back"] = create_pattern_mesh_from_points(back_points, "Back_Panel")
    
    # SLEEVE
    sleeve_width = armhole * 1.4
    sleeve_points = [
        (-sleeve_width/2, 0),
        (sleeve_width/2, 0),
        (sleeve_width/2, sleeve_len),
        (-sleeve_width/2, sleeve_len),
    ]
    panels["left_sleeve"] = create_pattern_mesh_from_points(sleeve_points, "Left_Sleeve")
    panels["right_sleeve"] = create_pattern_mesh_from_points(sleeve_points, "Right_Sleeve")
    
    # ========================================
    # NECK BAND (collar) - XML Task: Fix_Neck_Band_Generation
    # ========================================
    # Calculate neckline length using arc_length method
    import math
    
    # Generate neckline curve points for accurate arc length
    samples = 32  # Adaptive sampling
    front_curve_points = []
    for i in range(samples + 1):
        t = i / samples
        x = neck_width/2 * math.cos(math.pi * t)
        y = neck_depth_front * math.sin(math.pi * t)
        front_curve_points.append((x, y))
    
    back_curve_points = []
    for i in range(samples + 1):
        t = i / samples
        x = neck_width/2 * math.cos(math.pi * t)
        y = neck_depth_back * math.sin(math.pi * t)
        back_curve_points.append((x, y))
    
    # Calculate arc lengths
    def arc_length(points):
        total = 0.0
        for i in range(len(points) - 1):
            dx = points[i+1][0] - points[i][0]
            dy = points[i+1][1] - points[i][1]
            total += math.sqrt(dx*dx + dy*dy)
        return total
    
    front_neckline = arc_length(front_curve_points)
    back_neckline = arc_length(back_curve_points)
    total_neckline = front_neckline + back_neckline
    
    # Safety validation
    if math.isnan(total_neckline) or total_neckline <= 0:
        print(f"  ✗ ERROR: Invalid neckline length. Using fallback.")
        total_neckline = 50.0  # Safe fallback
    
    # Apply 10% reduction per XML Task
    band_length = total_neckline * (1 - band_reduction)
    
    neck_band_points = [
        (0, 0),
        (band_length, 0),
        (band_length, band_height),
        (0, band_height),
    ]
    
    # Create neck band with controlled vertices (no subdivision)
    panels["neck_band"] = create_neck_band_mesh(neck_band_points, "Neck_Band", target_vertices=48)
    print(f"  ✓ Neck band: {band_length:.1f} x {band_height:.1f} cm ({band_reduction*100:.0f}% reduced)")
    
    return panels


# ============================================================
# MAIN PIPELINE
# ============================================================

def run_blender_sewing_pipeline(measurements: dict = None):
    """
    Main function to run the complete sewing pipeline.
    
    Steps:
    1. Clear scene
    2. Create/import pattern pieces
    3. Position pieces in free space
    4. Add cloth physics
    5. Set up sewing constraints
    6. Run simulation (garment-only)
    """
    print("\n" + "="*60)
    print("   STEP 5: BLENDER SEWING & SIMULATION")
    print("="*60)
    
    # Force garbage collection at pipeline start
    gc.collect()
    
    # Default measurements if not provided (XML Schema v1.1 + Task Fix)
    if measurements is None:
        measurements = {
            # Core measurements
            "chest_flat": 50.0,       # HalfChestWidth
            "body_length": 70.0,      # GarmentLength
            "shoulder_width": 44.0,   # ShoulderWidth
            "sleeve_length": 22.0,    # SleeveLength
            "armhole_depth": 22.0,    # ArmholeDepth
            # Additional v1.1 measurements
            "hem_width": 50.0,
            "neck_width": 18.0,
            "neck_depth_front": 9.0,
            "neck_depth_back": 3.0,
            "bicep_width": 36.0,
            "neck_band_height": 4.0,
            "neck_band_reduction": 0.10,  # 10% per XML Task Fix_Neck_Band_Generation
        }
    
    print("\n📏 Using measurements (XML Schema v1.1):")
    for k, v in measurements.items():
        if isinstance(v, float) and v < 1:
            print(f"  {k}: {v*100:.0f}%")
        else:
            print(f"  {k}: {v} cm")
    
    # Step 1: Clear and setup scene
    print("\n" + "-"*40)
    clear_scene()
    setup_scene()
    
    # Garbage collect after clearing scene
    gc.collect()
    
    # Step 2: Create pattern pieces
    print("\n" + "-"*40)
    print("Creating pattern pieces...")
    
    # For this minimal version, create meshes directly
    # (SVG import can be used but requires the SVG files)
    panels = create_tshirt_panels_manually(measurements)
    
    # Garbage collect after creating all panels
    gc.collect()
    
    # Step 3: Position pieces above origin for gravity drop
    print("\n" + "-"*40)
    position_pattern_pieces(
        panels["front"],
        panels["back"],
        panels.get("left_sleeve"),
        panels.get("right_sleeve"),
        panels.get("neck_band"),  # XML Schema v1.1: neck band
        lift_height=0.6  # 60cm above origin for drop simulation
    )
    
    # Step 3b: Mark seam edges BEFORE joining
    print("\n" + "-"*40)
    print("Marking seam edges on panels...")
    mark_all_seam_edges(panels)
    
    # Step 4: Load and setup sewing seams
    # This MUST happen BEFORE joining pieces
    print("\n" + "-"*40)
    print("Loading and parsing seam metadata...")
    seam_data = load_seam_definitions()
    
    # Resolve panel names to Blender objects
    panel_name_map = resolve_panel_objects(panels)
    
    if seam_data and SEAM_DATA["loaded"]:
        # Use seam definitions from step4 (new enhanced format)
        print(f"  Using {len(SEAM_DATA['seams'])} seam pairs from seams.json")
        setup_seams_from_definitions(panels, SEAM_DATA["seam_details"])
    else:
        # Fall back to default seam setup
        setup_default_seams(panels)
    
    # Step 5: Join into single garment object
    print("\n" + "-"*40)
    all_pieces = [p for p in panels.values() if p is not None]
    garment = join_pattern_pieces(all_pieces, "TShirt_Garment")
    
    # Step 6: Add cloth physics WITH SEWING SPRINGS
    print("\n" + "-"*40)
    add_cloth_modifier(garment, enable_sewing=True)
    
    # Enable sewing springs with tuned force
    enable_sewing_springs_on_cloth(garment, sewing_force=25.0)
    
    # Garment-only mode: no avatar — simulate in free space
    print("\n" + "-"*40)
    print("Garment-only mode: simulating in free space (no avatar)")
    
    # Summary
    print("\n" + "="*60)
    print("   BLENDER SEWING SETUP COMPLETE")
    print("="*60)
    print(f"""
✅ REAL SEWING ENABLED — Configuration Summary:

GARMENT SETUP:
  ✓ Pattern panels created and positioned
  ✓ Panels lifted 0.6m above origin for gravity drop
  ✓ Seam edges marked from seams.json metadata
  ✓ Cloth physics with sewing springs (force: 25.0)

SIMULATION SETTINGS:
  ✓ Frame range: 1 to 60 (optimized for memory)
  ✓ Sewing springs: ENABLED
  ✓ Gravity: -9.81 m/s²

TO RUN SIMULATION MANUALLY:
  1. Press SPACEBAR to play animation
  2. Watch sewing springs pull edges together
  3. Fabric will sew and drape in free space

TO AUTO-BAKE (RECOMMENDED):
  In Blender Python console, run:
    auto_bake_cloth_simulation(garment, frames=60)

  Or from command line:
    MIRRA_AUTO_BAKE=true blender -b --python step5_blender_sewing.py

TO EXPORT FINAL GARMENT:
  run_full_simulation_pipeline(garment)
""")
    
    return garment


# ============================================================
# SCRIPT ENTRY POINT
# ============================================================

# Flag to control auto-baking (set via command line or environment)
AUTO_BAKE = os.environ.get("MIRRA_AUTO_BAKE", "false").lower() == "true"
AUTO_EXPORT = os.environ.get("MIRRA_AUTO_EXPORT", "false").lower() == "true"

if __name__ == "__main__":
    """
    This script runs inside Blender.
    
    BASIC USAGE (interactive):
        blender --python step5_blender_sewing.py
    
    This will:
    - Set up the scene with cloth physics
    - Position garment pieces in free space
    - Wait for you to press SPACEBAR to simulate
    
    AUTOMATED USAGE (bake + export):
        MIRRA_AUTO_BAKE=true blender -b --python step5_blender_sewing.py
    
    This will:
    - Do all of the above
    - Auto-bake the simulation (60 frames - memory optimized)
    - Create static mesh from final frame
    - Export as OBJ, FBX, GLB
    
    Options:
        -b              Run in background (no UI)
        MIRRA_AUTO_BAKE Set to "true" to auto-bake simulation
        MIRRA_AUTO_EXPORT Set to "true" to export after baking
    """
    
    # Try to load measurements from pattern_output if available
    measurements = None
    metadata_path = PATTERN_DIR / "pattern_metadata.json"
    
    if metadata_path.exists():
        try:
            with open(metadata_path, 'r') as f:
                metadata = json.load(f)
                measurements = metadata.get("measurements")
                print(f"✓ Loaded measurements from {metadata_path}")
        except:
            pass
    
    # Run the setup pipeline
    garment = run_blender_sewing_pipeline(measurements)
    
    # Auto-bake if requested
    if AUTO_BAKE:
        print("\n" + "="*60)
        print("   AUTO-BAKE ENABLED")
        print("="*60)
        
        static_garment = run_full_simulation_pipeline(
            garment,
            output_dir=str(PATTERN_DIR / "exports"),
            frames=60,  # Reduced from 120 to prevent OOM
            auto_export=AUTO_EXPORT
        )
        
        # Save the blend file
        blend_output = str(PATTERN_DIR / "garment_simulated.blend")
        save_garment(blend_output)
        
        print("\n" + "="*60)
        print("   STEP 5 COMPLETE — SIMULATION BAKED ✅")
        print("="*60)
        print(f"""
Output files:
  Blend file: {blend_output}
  Exports: {PATTERN_DIR / 'exports'}/
    - TShirt_Garment_Static.obj
    - TShirt_Garment_Static.fbx  
    - TShirt_Garment_Static.glb
""")
    else:
        print("\n" + "="*60)
        print("   STEP 5 SETUP COMPLETE")
        print("="*60)
        print("""
Scene is ready! To complete:

OPTION A - Interactive:
  1. Press SPACEBAR to play simulation
  2. Watch garment sew itself together
  3. File > Export when satisfied

OPTION B - Automated bake:
  In Blender Python console, run:
    run_full_simulation_pipeline(garment)

OPTION C - Re-run with auto-bake:
  MIRRA_AUTO_BAKE=true blender -b --python step5_blender_sewing.py
""")
    
    print("\nNext step: Apply color and design texture (step6)")
    print("Run: python step6_apply_texture.py")
