"""
STEP 5: Blender Sewing & Cloth Simulation
==========================================
This script runs INSIDE Blender to:
1. Import SVG pattern pieces
2. Convert them to cloth meshes
3. Position them for sewing
4. Define sewing constraints (which edges connect)
5. Run cloth simulation

Think of this as a DIGITAL TAILOR:
- The pattern pieces are like cut fabric
- We pin matching edges together
- Gravity and physics pull them into shape
- The result is a 3D garment!

HOW TO RUN:
1. Open Blender
2. Go to Scripting workspace
3. Open this file
4. Click "Run Script"

Or from command line:
    blender --python step5_blender_sewing.py
"""

import bpy
import bmesh
import math
import os
import json
import gc  # Garbage collection for memory management
from pathlib import Path
from mathutils import Vector, Matrix

# ============================================================
# CONFIGURATION
# ============================================================

# Input directory (where pattern SVGs are)
PATTERN_DIR = Path(__file__).parent / "pattern_output"

# Scale factor: SVG is in cm, Blender uses meters
# 1 cm = 0.01 meters
CM_TO_M = 0.01

# Cloth simulation settings
CLOTH_SETTINGS = {
    "quality": 12,           # Simulation quality (higher = better but slower)
    "mass": 0.3,             # Fabric weight (kg/m²) - cotton is ~0.15-0.3
    "tension_stiffness": 15, # How much fabric resists stretching
    "compression_stiffness": 15,
    "bending_stiffness": 0.5,  # How easily fabric bends
    "air_damping": 1,        # Air resistance
}

# Sewing spring settings
SEWING_SETTINGS = {
    "force": 100,            # How strongly edges pull together
    "max_dist": 0.1,         # Max distance for sewing (meters)
    "shrink_min": 0.0,       # Minimum shrink factor
}

# Path to seam definitions (generated by step4)
SEAM_FILE = PATTERN_DIR / "seams.json"


# ============================================================
# SEAM LOADING AND PARSING
# ============================================================

def load_seam_definitions() -> list:
    """
    Load seam definitions from seams.json.
    
    The seams.json file contains pairs of edges that should be sewn together.
    Each seam has:
    - name: Descriptive name (e.g., "left_side_seam")
    - edge1: {piece, edge_name, vertices} for first edge
    - edge2: {piece, edge_name, vertices} for second edge
    
    Returns:
        List of seam definitions, or empty list if file not found
    """
    if not SEAM_FILE.exists():
        print(f"  ⚠ No seam file found at {SEAM_FILE}")
        print("    Sewing will use default edge matching")
        return []
    
    try:
        with open(SEAM_FILE, 'r') as f:
            data = json.load(f)
        seams = data.get("seams", [])
        print(f"  ✓ Loaded {len(seams)} seam definitions from seams.json")
        return seams
    except Exception as e:
        print(f"  ✗ Error loading seams.json: {e}")
        return []


def get_edge_vertices_by_direction(mesh_obj: bpy.types.Object, 
                                    direction: str,
                                    tolerance: float = 0.02) -> list:
    """
    Robust vertex selector that handles CURVES (like armholes) using 
    Sector Logic instead of just Bounding Box Logic.
    """
    mesh = mesh_obj.data
    matrix = mesh_obj.matrix_world
    
    # Get Bounds
    coords = [matrix @ Vector(v.co) for v in mesh.vertices]
    if not coords: return []
    
    min_x, max_x = min(c.x for c in coords), max(c.x for c in coords)
    min_y, max_y = min(c.y for c in coords), max(c.y for c in coords)
    min_z, max_z = min(c.z for c in coords), max(c.z for c in coords)
    
    width = max_x - min_x
    height = max_z - min_z # Assuming Z is up (standing) or Y is up (flat)
    
    edge_verts = []
    
    for i, v in enumerate(mesh.vertices):
        co = matrix @ Vector(v.co)
        
        # --- LOGIC UPGRADE: SECTORS ---
        # Instead of just "Left Edge", we define "Zones"
        
        match = False
        
        # 1. Straight Edges (Classic Bounding Box)
        if direction == "left" and abs(co.x - min_x) < tolerance: match = True
        elif direction == "right" and abs(co.x - max_x) < tolerance: match = True
        elif direction == "top" and abs(co.z - max_z) < tolerance: match = True
        elif direction == "bottom" and abs(co.z - min_z) < tolerance: match = True
        
        # 2. Curved Zones (The Fix for Armholes/Necks)
        # Armhole Left: Upper-Left Quadrant, but NOT the shoulder top or side straight
        elif direction == "armhole_left":
            # Check if vertex is in the top-left 30% of the mesh
            if (co.x < min_x + width * 0.3) and (co.z > max_z - height * 0.4):
                # Exclude the very top (shoulder) and very left (side seam)
                if abs(co.z - max_z) > tolerance and abs(co.x - min_x) > tolerance:
                    match = True

        # Armhole Right: Upper-Right Quadrant
        elif direction == "armhole_right":
            if (co.x > max_x - width * 0.3) and (co.z > max_z - height * 0.4):
                if abs(co.z - max_z) > tolerance and abs(co.x - max_x) > tolerance:
                    match = True

        if match:
            edge_verts.append(i)
            
    return edge_verts


def create_vertex_group_for_edge(obj: bpy.types.Object, 
                                  group_name: str,
                                  vertex_indices: list,
                                  weight: float = 1.0):
    """
    Create or update a vertex group with specified vertices.
    
    Vertex groups are how Blender marks which vertices should be sewn.
    Each sewing edge needs its own vertex group.
    
    Args:
        obj: The mesh object
        group_name: Name for the vertex group
        vertex_indices: List of vertex indices to add
        weight: Weight for the vertices (1.0 = fully included)
    """
    # Get or create vertex group
    if group_name in obj.vertex_groups:
        vg = obj.vertex_groups[group_name]
    else:
        vg = obj.vertex_groups.new(name=group_name)
    
    # Add vertices to group
    vg.add(vertex_indices, weight, 'ADD')
    
    return vg


def setup_seams_from_definitions(panels: dict, seam_defs: list):
    """
    Set up sewing vertex groups based on seam definitions.
    
    This maps the abstract seam definitions to actual vertices in the
    Blender meshes. After subdivision, we find edges by their position
    rather than vertex indices.
    
    Args:
        panels: Dictionary of pattern piece mesh objects
        seam_defs: List of seam definitions from seams.json
    """
    if not seam_defs:
        print("  No seam definitions - using default sewing setup")
        return
    
    print("→ Setting up seams from definitions...")
    
    # Map piece names to objects - use the panel dictionary keys directly
    piece_map = panels  # panels dict already has "Front_Panel", "Back_Panel", etc.
    
    # Edge direction mapping based on seam names
    # This translates pattern edges to mesh positions
    edge_to_direction = {
        # Front panel edges
        "left_edge": "left",
        "right_edge": "right",
        "shoulder_left": "top",    # Approximation
        "shoulder_right": "top",
        "armhole_left": "left",    # Upper left area
        "armhole_right": "right",  # Upper right area
        
        # Back panel edges (mirror of front)
        
        # Sleeve edges
        "top": "top",
        "bottom": "bottom", 
        "cap": "top",              # Sleeve cap
        "underarm": "bottom",
    }
    
    seam_count = 0
    
    for seam in seam_defs:
        seam_name = seam.get("name", f"seam_{seam_count}")
        
        # NEW FORMAT: panel_a, panel_b, edge_a, edge_b
        panel_a_name = seam.get("panel_a", "")
        panel_b_name = seam.get("panel_b", "")
        edge_a_name = seam.get("edge_a", "")
        edge_b_name = seam.get("edge_b", "")
        
        # Get mesh objects
        obj_a = piece_map.get(panel_a_name)
        obj_b = piece_map.get(panel_b_name)
        
        if not obj_a or not obj_b:
            print(f"    ⚠ Skipping {seam_name}: piece not found (panel_a={panel_a_name}, panel_b={panel_b_name})")
            continue
        
        # Get edge directions
        dir_a = edge_to_direction.get(edge_a_name, "left")
        dir_b = edge_to_direction.get(edge_b_name, "left")
        
        # Find vertices on each edge
        verts_a = get_edge_vertices_by_direction(obj_a, dir_a)
        verts_b = get_edge_vertices_by_direction(obj_b, dir_b)
        
        if verts_a and verts_b:
            # Create vertex groups
            group_name = f"sew_{seam_name}"
            create_vertex_group_for_edge(obj_a, group_name, verts_a)
            create_vertex_group_for_edge(obj_b, group_name, verts_b)
            print(f"    ✓ {seam_name}: {len(verts_a)} ↔ {len(verts_b)} vertices")
            seam_count += 1
        else:
            print(f"    ⚠ {seam_name}: no vertices found (v_a={len(verts_a)}, v_b={len(verts_b)})")
    
    print(f"  ✓ Created {seam_count} seam vertex groups")


def setup_default_seams(panels: dict):
    """
    Set up default sewing seams when no seam definitions are available.
    
    Creates sewing groups for:
    - Side seams (front left ↔ back left, front right ↔ back right)
    - Shoulder seams (front top ↔ back top)
    
    Args:
        panels: Dictionary of pattern piece mesh objects
    """
    print("→ Setting up default sewing seams...")
    
    front = panels.get("front")
    back = panels.get("back")
    
    if not front or not back:
        print("  ⚠ Cannot create seams: front or back panel missing")
        return
    
    # Side seams: connect left edges of front and back
    front_left = get_edge_vertices_by_direction(front, "left")
    back_left = get_edge_vertices_by_direction(back, "left")
    
    if front_left and back_left:
        create_vertex_group_for_edge(front, "sew_left_side", front_left)
        create_vertex_group_for_edge(back, "sew_left_side", back_left)
        print(f"  ✓ Left side seam: {len(front_left)} ↔ {len(back_left)} vertices")
    
    # Right side seam
    front_right = get_edge_vertices_by_direction(front, "right")
    back_right = get_edge_vertices_by_direction(back, "right")
    
    if front_right and back_right:
        create_vertex_group_for_edge(front, "sew_right_side", front_right)
        create_vertex_group_for_edge(back, "sew_right_side", back_right)
        print(f"  ✓ Right side seam: {len(front_right)} ↔ {len(back_right)} vertices")
    
    # Shoulder seams (top edge)
    front_top = get_edge_vertices_by_direction(front, "top")
    back_top = get_edge_vertices_by_direction(back, "top")
    
    if front_top and back_top:
        create_vertex_group_for_edge(front, "sew_shoulders", front_top)
        create_vertex_group_for_edge(back, "sew_shoulders", back_top)
        print(f"  ✓ Shoulder seam: {len(front_top)} ↔ {len(back_top)} vertices")


# ============================================================
# UTILITY FUNCTIONS
# ============================================================

def clear_scene():
    """
    Aggressively removes all objects AND data blocks to free RAM.
    """
    print("→ Clearing scene and purging memory...")
    
    # 1. Delete all objects in current scene
    bpy.ops.object.select_all(action='SELECT')
    bpy.ops.object.delete()
    
    # 2. Force remove all data blocks (Meshes, Materials, Curves, etc.)
    # Blender keeps these in memory ("Orphan Data") even after objects are deleted
    for block in bpy.data.meshes:
        bpy.data.meshes.remove(block)
        
    for block in bpy.data.materials:
        bpy.data.materials.remove(block)
        
    for block in bpy.data.curves:
        bpy.data.curves.remove(block)
        
    for block in bpy.data.images:
        bpy.data.images.remove(block)

    # 3. Explicitly call Python Garbage Collector
    gc.collect()
    
    print("  ✓ Scene cleared & RAM purged")


def setup_scene():
    """
    Set up the scene for cloth simulation.
    
    This includes:
    - Setting units to metric
    - Adding ground plane (for collision)
    - Adding a mannequin/avatar (optional collision body)
    - Setting up lighting for preview
    """
    print("→ Setting up scene...")
    
    # Set units to metric (meters)
    bpy.context.scene.unit_settings.system = 'METRIC'
    bpy.context.scene.unit_settings.scale_length = 1.0
    
    # Set frame range for simulation
    bpy.context.scene.frame_start = 1
    bpy.context.scene.frame_end = 150  # 150 frames of simulation
    bpy.context.scene.frame_current = 1
    
    # Add ground plane for reference (not for collision in this setup)
    bpy.ops.mesh.primitive_plane_add(size=2, location=(0, 0, -0.5))
    ground = bpy.context.active_object
    ground.name = "Ground_Reference"
    
    print("  ✓ Scene configured")
    
    return ground


def import_svg_as_curve(svg_path: Path, name: str) -> bpy.types.Object:
    """
    Import an SVG file as a curve object.
    
    Blender can directly import SVG files as curve objects.
    The curve represents the outline of the pattern piece.
    
    Args:
        svg_path: Path to the SVG file
        name: Name for the imported object
    
    Returns:
        The imported curve object
    """
    print(f"→ Importing {name} from {svg_path.name}...")
    
    # Import SVG
    bpy.ops.import_curve.svg(filepath=str(svg_path))
    
    # SVG import creates a collection, get the curves from it
    # The imported objects are selected after import
    imported_objects = bpy.context.selected_objects
    
    if not imported_objects:
        print(f"  ✗ Failed to import {svg_path}")
        return None
    
    # Usually SVG imports as multiple curves, join them
    curve_obj = imported_objects[0]
    curve_obj.name = f"{name}_curve"
    
    print(f"  ✓ Imported as curve: {curve_obj.name}")
    
    return curve_obj


def curve_to_mesh(curve_obj: bpy.types.Object, name: str) -> bpy.types.Object:
    """
    Convert a curve to a mesh.
    
    Cloth simulation needs a MESH (vertices, edges, faces).
    We convert the curve outline to a flat mesh with faces.
    
    Steps:
    1. Convert curve to mesh (just edges)
    2. Fill the outline to create a face
    3. Subdivide for smooth simulation
    
    Args:
        curve_obj: The curve object to convert
        name: Name for the new mesh
    
    Returns:
        The mesh object
    """
    print(f"→ Converting {curve_obj.name} to mesh...")
    
    # Select and make active
    bpy.ops.object.select_all(action='DESELECT')
    curve_obj.select_set(True)
    bpy.context.view_layer.objects.active = curve_obj
    
    # Convert curve to mesh
    bpy.ops.object.convert(target='MESH')
    
    mesh_obj = bpy.context.active_object
    mesh_obj.name = name
    
    # Enter edit mode to fill and subdivide
    bpy.ops.object.mode_set(mode='EDIT')
    
    # Select all vertices
    bpy.ops.mesh.select_all(action='SELECT')
    
    # Fill the outline to create a face
    # edge_fill creates an n-gon face from the boundary
    try:
        bpy.ops.mesh.edge_face_add()
    except:
        # If that fails, try fill
        bpy.ops.mesh.fill()
    
    # Subdivide for smoother simulation
    # More vertices = smoother cloth behavior
    bpy.ops.mesh.subdivide(number_cuts=3)
    
    # Triangulate for cloth simulation (works better with tris)
    bpy.ops.mesh.quads_convert_to_tris()
    
    # Exit edit mode
    bpy.ops.object.mode_set(mode='OBJECT')
    
    # Apply scale (important for physics)
    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
    
    # Force garbage collection after mesh operations
    gc.collect()
    
    vertex_count = len(mesh_obj.data.vertices)
    print(f"  ✓ Created mesh with {vertex_count} vertices")
    
    return mesh_obj


def create_pattern_mesh_from_points(points: list, name: str) -> bpy.types.Object:
    """
    Create a mesh directly from pattern outline points.
    
    This is an alternative to SVG import - creates mesh directly
    from the coordinate data.
    
    Args:
        points: List of (x, y) tuples defining the outline
        name: Name for the mesh
    
    Returns:
        The mesh object
    """
    print(f"→ Creating mesh for {name}...")
    
    # Create new mesh
    mesh = bpy.data.meshes.new(f"{name}_mesh")
    obj = bpy.data.objects.new(name, mesh)
    
    # Link to scene
    bpy.context.collection.objects.link(obj)
    
    # Create BMesh for easier mesh construction
    bm = bmesh.new()
    
    # Add vertices (convert cm to meters, Z=0 for flat pattern)
    verts = []
    for x, y in points:
        v = bm.verts.new((x * CM_TO_M, y * CM_TO_M, 0))
        verts.append(v)
    
    bm.verts.ensure_lookup_table()
    
    # Create edges connecting consecutive vertices
    for i in range(len(verts)):
        bm.edges.new((verts[i], verts[(i + 1) % len(verts)]))
    
    # Create face from all vertices (the pattern piece)
    try:
        bm.faces.new(verts)
    except:
        print(f"  ⚠ Could not create face for {name}")
    
    # Update mesh
    bm.to_mesh(mesh)
    bm.free()
    
    # Force garbage collection after bmesh operations
    gc.collect()
    
    # Subdivide for simulation
    bpy.context.view_layer.objects.active = obj
    obj.select_set(True)
    
    bpy.ops.object.mode_set(mode='EDIT')
    bpy.ops.mesh.select_all(action='SELECT')
    bpy.ops.mesh.subdivide(number_cuts=4)
    bpy.ops.mesh.quads_convert_to_tris()
    bpy.ops.object.mode_set(mode='OBJECT')
    
    # Garbage collect after subdivision
    gc.collect()
    
    vertex_count = len(obj.data.vertices)
    print(f"  ✓ Created {name} with {vertex_count} vertices")
    
    return obj


def position_pattern_pieces(front: bpy.types.Object, 
                           back: bpy.types.Object,
                           left_sleeve: bpy.types.Object,
                           right_sleeve: bpy.types.Object):
    """
    Position pattern pieces for sewing.
    
    Like laying out fabric before sewing:
    - Front and back face each other (will be sewn at sides)
    - Sleeves positioned at armholes
    
    The pieces start FLAT and will be pulled into 3D shape
    by the sewing forces during simulation.
    
    Layout (top view):
    
                 LEFT_SLEEVE
                      │
         ┌────────────┼────────────┐
         │            │            │
    FRONT│            │            │BACK
         │            │            │
         └────────────┼────────────┘
                      │
                RIGHT_SLEEVE
    """
    print("→ Positioning pattern pieces...")
    
    # Get dimensions of front panel for reference
    front_dims = front.dimensions
    panel_width = front_dims.x
    panel_height = front_dims.y
    
    # Position FRONT (left side, facing right)
    front.location = Vector((-panel_width * 0.6, 0, 0))
    front.rotation_euler = (math.radians(90), 0, 0)  # Stand up vertically
    print(f"  ✓ Front positioned at {front.location}")
    
    # Position BACK (right side, facing left - mirror of front)
    back.location = Vector((panel_width * 0.6, 0, 0))
    back.rotation_euler = (math.radians(90), 0, math.radians(180))  # Rotated to face front
    print(f"  ✓ Back positioned at {back.location}")
    
    # Position LEFT SLEEVE (top)
    if left_sleeve:
        sleeve_width = left_sleeve.dimensions.x
        left_sleeve.location = Vector((0, panel_width * 0.5, panel_height * 0.4))
        left_sleeve.rotation_euler = (math.radians(90), 0, math.radians(-90))
        print(f"  ✓ Left sleeve positioned")
    
    # Position RIGHT SLEEVE (bottom, mirror of left)
    if right_sleeve:
        right_sleeve.location = Vector((0, -panel_width * 0.5, panel_height * 0.4))
        right_sleeve.rotation_euler = (math.radians(90), 0, math.radians(90))
        print(f"  ✓ Right sleeve positioned")


def add_cloth_modifier(obj: bpy.types.Object, enable_sewing: bool = True):
    """
    Add cloth physics to a mesh object.
    
    The cloth modifier makes the mesh behave like fabric:
    - It responds to gravity
    - It can collide with other objects
    - It can be sewn to other cloth objects via sewing springs
    
    Args:
        obj: The mesh object to add cloth to
        enable_sewing: Whether to enable sewing springs
    """
    print(f"→ Adding cloth physics to {obj.name}...")
    
    # Add cloth modifier
    cloth_mod = obj.modifiers.new(name="Cloth", type='CLOTH')
    
    # Configure cloth settings
    cloth = cloth_mod.settings
    
    # Quality (more steps = more accurate but slower)
    cloth.quality = CLOTH_SETTINGS["quality"]
    
    # Mass (kg per square meter)
    cloth.mass = CLOTH_SETTINGS["mass"]
    
    # Stiffness (how much fabric resists deformation)
    cloth.tension_stiffness = CLOTH_SETTINGS["tension_stiffness"]
    cloth.compression_stiffness = CLOTH_SETTINGS["compression_stiffness"]
    cloth.bending_stiffness = CLOTH_SETTINGS["bending_stiffness"]
    
    # Damping (reduces oscillation)
    cloth.air_damping = CLOTH_SETTINGS["air_damping"]
    
    # Enable pressure (helps maintain volume)
    cloth.use_pressure = True
    cloth.uniform_pressure_force = 0.5
    
    # ==========================================
    # SEWING SPRINGS - This is the key feature!
    # ==========================================
    if enable_sewing:
        cloth.use_sewing_springs = True
        cloth.sewing_force_max = SEWING_SETTINGS["force"]
        cloth.shrink_min = SEWING_SETTINGS["shrink_min"]
        print(f"  ✓ Sewing springs ENABLED (force={SEWING_SETTINGS['force']})")
    else:
        cloth.use_sewing_springs = False
        print(f"  ⚠ Sewing springs disabled")
    
    print(f"  ✓ Cloth modifier added to {obj.name}")


def create_sewing_springs(obj1: bpy.types.Object, 
                          obj2: bpy.types.Object,
                          edge_type: str):
    """
    Create vertex group for sewing between two pattern pieces.
    
    Sewing in Blender cloth simulation works by:
    1. Selecting vertices on the edge to be sewn
    2. Creating a vertex group for these vertices
    3. The cloth solver pulls matching edges together
    
    Args:
        obj1: First pattern piece
        obj2: Second pattern piece  
        edge_type: Type of seam ("side", "shoulder", "sleeve")
    
    This is a simplified version - real sewing would need
    exact edge matching based on pattern markings.
    """
    print(f"→ Setting up {edge_type} seam between {obj1.name} and {obj2.name}...")
    
    # Create vertex groups for the seam edges
    # In production, you'd select specific vertices based on pattern data
    
    group_name = f"sew_{edge_type}"
    
    # Add vertex group to first object
    if group_name not in obj1.vertex_groups:
        vg1 = obj1.vertex_groups.new(name=group_name)
    else:
        vg1 = obj1.vertex_groups[group_name]
    
    # Add vertex group to second object
    if group_name not in obj2.vertex_groups:
        vg2 = obj2.vertex_groups.new(name=group_name)
    else:
        vg2 = obj2.vertex_groups[group_name]
    
    print(f"  ✓ Created sewing groups: {group_name}")


def setup_sewing_constraint(cloth_obj: bpy.types.Object, vertex_group: str):
    """
    Configure cloth modifier to use sewing.
    
    The sewing constraint in Blender's cloth simulation:
    - Finds vertices in the sewing vertex group
    - Creates springs that pull them toward matching vertices
    - Over simulation time, edges come together like actual sewing
    
    Args:
        cloth_obj: Object with cloth modifier
        vertex_group: Name of vertex group with sewing vertices
    """
    # Get the cloth modifier
    cloth_mod = None
    for mod in cloth_obj.modifiers:
        if mod.type == 'CLOTH':
            cloth_mod = mod
            break
    
    if cloth_mod is None:
        print(f"  ⚠ No cloth modifier on {cloth_obj.name}")
        return
    
    # Enable sewing
    cloth_mod.settings.use_sewing_springs = True
    cloth_mod.settings.sewing_force_max = SEWING_SETTINGS["force"]
    
    # Set the vertex group for sewing
    cloth_mod.settings.vertex_group_mass = vertex_group


def join_pattern_pieces(pieces: list, name: str) -> bpy.types.Object:
    """
    Join multiple pattern pieces into a single object.
    
    For cloth simulation, it's easier to have one object
    with all pattern pieces. Sewing then happens between
    different vertex groups within that object.
    
    Args:
        pieces: List of mesh objects to join
        name: Name for the combined object
    
    Returns:
        The joined object
    """
    print(f"→ Joining pattern pieces into {name}...")
    
    # Deselect all
    bpy.ops.object.select_all(action='DESELECT')
    
    # Select all pieces
    for piece in pieces:
        if piece:
            piece.select_set(True)
    
    # Make first piece active
    bpy.context.view_layer.objects.active = pieces[0]
    
    # Join
    bpy.ops.object.join()
    
    # Rename
    joined = bpy.context.active_object
    joined.name = name
    
    print(f"  ✓ Created combined garment: {name}")
    
    return joined


def add_simple_avatar():
    """
    Add a simple avatar/mannequin for the garment.
    
    The avatar is a collision object - the cloth will drape
    around it rather than falling through.
    
    For a minimal pipeline, we use a simple cylinder/capsule shape.
    A full pipeline would import a detailed body mesh.
    """
    print("→ Creating simple avatar (collision body)...")
    
    # Create torso (cylinder)
    bpy.ops.mesh.primitive_cylinder_add(
        radius=0.15,        # ~30cm diameter (chest)
        depth=0.5,          # ~50cm tall (torso)
        location=(0, 0, 0)
    )
    torso = bpy.context.active_object
    torso.name = "Avatar_Torso"
    
    # Add collision modifier
    collision_mod = torso.modifiers.new(name="Collision", type='COLLISION')
    collision_mod.settings.thickness_outer = 0.01  # 1cm collision margin
    
    print("  ✓ Avatar created with collision")
    
    return torso


def add_anatomical_avatar(measurements: dict = None):
    """
    Creates a smooth, continuous body using Metaballs to prevent cloth explosion.
    Replaces the "cylinder-jammed-into-cylinder" approach.
    """
    print("→ Creating smooth metabolic avatar...")
    
    # 1. Scale based on measurements
    chest_flat = measurements.get("chest_flat", 52.0) if measurements else 52.0
    body_length = measurements.get("body_length", 72.0) if measurements else 72.0
    
    # Convert cm to blender meters
    scale_factor = 0.01
    chest_radius = (chest_flat * scale_factor) / 3.0  # Approx radius
    torso_height = body_length * scale_factor * 0.7
    shoulder_w = (measurements.get("shoulder_width", 46.0) * scale_factor) / 2
    
    # 2. Create Metaball Object
    mball = bpy.data.metaballs.new("AvatarMball")
    obj = bpy.data.objects.new("Avatar_Base", mball)
    bpy.context.collection.objects.link(obj)
    
    # 3. Add Elements (The "Liquid" Shapes)
    mball.resolution = 0.05  # Resolution for viewport
    mball.render_resolution = 0.02
    
    # -- Torso (Vertical Ellipse) --
    ele_torso = mball.elements.new()
    ele_torso.type = 'CAPSULE'
    ele_torso.co = (0, 0, torso_height/2)
    ele_torso.radius = chest_radius
    ele_torso.size_x = torso_height  # For capsule, size_x is length
    # Note: Metaball capsules align along X by default, we rotate the OBJECT later
    
    # -- Shoulders (Fused to Torso) --
    # Left Shoulder
    ele_sh_l = mball.elements.new()
    ele_sh_l.type = 'ELLIPSOID'
    ele_sh_l.co = (-shoulder_w, 0, torso_height - 0.05)
    ele_sh_l.radius = 0.08  # Thickness of shoulder
    ele_sh_l.size_x = 0.15  # Stretch width
    
    # Right Shoulder
    ele_sh_r = mball.elements.new()
    ele_sh_r.type = 'ELLIPSOID'
    ele_sh_r.co = (shoulder_w, 0, torso_height - 0.05)
    ele_sh_r.radius = 0.08
    ele_sh_r.size_x = 0.15

    # Neck
    ele_neck = mball.elements.new()
    ele_neck.type = 'CAPSULE'
    ele_neck.co = (0, 0, torso_height + 0.05)
    ele_neck.radius = 0.07
    
    # 4. Convert to Mesh (Crucial for Collision)
    # We must convert the metaball math into a real mesh for physics
    bpy.context.view_layer.objects.active = obj
    obj.select_set(True)
    bpy.ops.object.convert(target='MESH')
    avatar_mesh = bpy.context.active_object
    avatar_mesh.name = "Avatar_Smooth_Collision"
    
    # 5. Add Collision Modifier
    coll = avatar_mesh.modifiers.new(name="Collision", type='COLLISION')
    coll.settings.thickness_outer = 0.02  # 2cm buffer
    coll.settings.damping = 0.6           # Absorb velocity (less bouncy)
    coll.settings.cloth_friction = 2.0    # Fabric sticks a little
    
    print("  ✓ Created smooth organic avatar (no sharp seams)")
    return {"torso": avatar_mesh}

def position_garment_on_avatar(garment: bpy.types.Object, 
                                avatar_parts: dict,
                                measurements: dict = None):
    """
    Position the flat garment pieces around the avatar.
    
    The garment starts positioned ABOVE and AROUND the avatar.
    During simulation:
    1. Gravity pulls the fabric down
    2. Collision prevents it from passing through the body
    3. Sewing springs pull edges together
    
    Result: Garment drapes naturally on the avatar.
    
    Args:
        garment: The joined garment mesh
        avatar_parts: Dictionary of avatar body parts
        measurements: Optional measurements for positioning
    """
    print("→ Positioning garment on avatar...")
    
    torso = avatar_parts.get("torso")
    if not torso:
        print("  ⚠ No torso found, using default position")
        garment.location.z = 0.25
        return
    
    # Get torso dimensions
    torso_height = torso.dimensions.z
    torso_top = torso.location.z + torso_height / 2
    
    # Position garment at shoulder height, slightly above
    # This allows it to fall and drape during simulation
    garment.location.z = torso_top - 0.05  # Just below shoulders
    
    # Center on avatar
    garment.location.x = 0
    garment.location.y = 0
    
    print(f"  ✓ Garment positioned at z={garment.location.z:.2f}m")
    print("    During simulation, fabric will fall and drape on avatar")


def run_simulation(frames: int = 150):
    """
    Run the cloth simulation.
    
    This bakes the simulation - calculating cloth position
    for each frame. The sewing springs pull edges together
    while gravity pulls the fabric down.
    
    Args:
        frames: Number of frames to simulate
    """
    print(f"→ Running simulation for {frames} frames...")
    print("  (This may take a few minutes)")
    
    # Set frame range
    bpy.context.scene.frame_end = frames
    
    # Go to frame 1
    bpy.context.scene.frame_set(1)
    
    # Bake simulation
    # In Blender UI this would be: Physics > Cloth > Cache > Bake
    # Programmatically, we just step through frames
    
    for frame in range(1, frames + 1):
        bpy.context.scene.frame_set(frame)
        
        # Print progress every 30 frames
        if frame % 30 == 0:
            print(f"  Frame {frame}/{frames}...")
    
    print(f"  ✓ Simulation complete")


def bake_simulation(garment: bpy.types.Object, frames: int = 150):
    """
    Bake the cloth simulation to cache.
    
    Baking pre-calculates all simulation frames so playback is instant.
    This is more reliable than stepping through frames manually.
    
    Args:
        garment: The garment object with cloth modifier
        frames: Number of frames to bake
    
    Returns:
        True if bake succeeded, False otherwise
    """
    print(f"→ Baking simulation ({frames} frames)...")
    print("  This may take several minutes...")
    
    # Find the cloth modifier
    cloth_mod = None
    for mod in garment.modifiers:
        if mod.type == 'CLOTH':
            cloth_mod = mod
            break
    
    if not cloth_mod:
        print("  ✗ No cloth modifier found!")
        return False
    
    # Set frame range
    bpy.context.scene.frame_start = 1
    bpy.context.scene.frame_end = frames
    
    # Configure cache for baking
    cloth_mod.point_cache.frame_start = 1
    cloth_mod.point_cache.frame_end = frames
    
    # Select the garment
    bpy.ops.object.select_all(action='DESELECT')
    garment.select_set(True)
    bpy.context.view_layer.objects.active = garment
    
    # Bake the simulation
    # This uses Blender's built-in bake operator
    try:
        # Free any existing bake first
        bpy.ops.ptcache.free_bake_all()
        
        # Bake all physics
        bpy.ops.ptcache.bake_all(bake=True)
        
        print(f"  ✓ Simulation baked successfully")
        return True
    except Exception as e:
        print(f"  ⚠ Bake operator failed: {e}")
        print("  Falling back to frame-by-frame bake...")
        
        # Fallback: step through frames
        for frame in range(1, frames + 1):
            bpy.context.scene.frame_set(frame)
            if frame % 30 == 0:
                print(f"    Frame {frame}/{frames}...")
        
        print(f"  ✓ Frame-by-frame bake complete")
        return True


def apply_simulation_as_mesh(garment: bpy.types.Object, frame: int = None) -> bpy.types.Object:
    """
    Apply the simulated cloth state as a static mesh.
    
    This "freezes" the simulation at a specific frame,
    converting the dynamic cloth to a static mesh that can be exported.
    
    Args:
        garment: The garment with cloth simulation
        frame: Frame to freeze at (default: last frame)
    
    Returns:
        The static mesh object (original is preserved)
    """
    print("→ Applying simulation as static mesh...")
    
    # Go to the target frame
    if frame is None:
        frame = bpy.context.scene.frame_end
    
    bpy.context.scene.frame_set(frame)
    print(f"  Using frame {frame}")
    
    # Select the garment
    bpy.ops.object.select_all(action='DESELECT')
    garment.select_set(True)
    bpy.context.view_layer.objects.active = garment
    
    # Duplicate the object
    bpy.ops.object.duplicate()
    static_garment = bpy.context.active_object
    static_garment.name = f"{garment.name}_Static"
    
    # Apply the cloth modifier (converts to static mesh)
    for mod in static_garment.modifiers:
        if mod.type == 'CLOTH':
            try:
                bpy.ops.object.modifier_apply(modifier=mod.name)
                print(f"  ✓ Applied cloth modifier")
            except Exception as e:
                print(f"  ⚠ Could not apply modifier: {e}")
                # Alternative: convert to mesh
                bpy.ops.object.convert(target='MESH')
    
    # Hide the original animated version
    garment.hide_viewport = True
    garment.hide_render = True
    
    print(f"  ✓ Created static mesh: {static_garment.name}")
    
    return static_garment


def export_garment(garment: bpy.types.Object, 
                   output_dir: str,
                   formats: list = None):
    """
    Export the garment mesh in multiple formats.
    
    Supported formats:
    - OBJ: Universal, widely supported
    - FBX: Good for game engines
    - GLB/GLTF: Web-friendly, includes materials
    
    Args:
        garment: The mesh object to export
        output_dir: Directory to save exports
        formats: List of formats to export (default: all)
    """
    if formats is None:
        formats = ["obj", "fbx", "glb"]
    
    print(f"→ Exporting garment to {output_dir}...")
    
    # Create output directory if needed
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)
    
    # Select only the garment
    bpy.ops.object.select_all(action='DESELECT')
    garment.select_set(True)
    bpy.context.view_layer.objects.active = garment
    
    base_name = garment.name.replace(" ", "_")
    
    for fmt in formats:
        filepath = str(output_path / f"{base_name}.{fmt}")
        
        try:
            if fmt.lower() == "obj":
                bpy.ops.wm.obj_export(
                    filepath=filepath,
                    export_selected_objects=True,
                    export_materials=True
                )
                print(f"  ✓ Exported: {base_name}.obj")
                
            elif fmt.lower() == "fbx":
                bpy.ops.export_scene.fbx(
                    filepath=filepath,
                    use_selection=True,
                    mesh_smooth_type='FACE'
                )
                print(f"  ✓ Exported: {base_name}.fbx")
                
            elif fmt.lower() in ["glb", "gltf"]:
                bpy.ops.export_scene.gltf(
                    filepath=filepath,
                    use_selection=True,
                    export_format='GLB' if fmt.lower() == "glb" else 'GLTF_SEPARATE'
                )
                print(f"  ✓ Exported: {base_name}.{fmt}")
                
        except Exception as e:
            print(f"  ✗ Failed to export {fmt}: {e}")
    
    print(f"  ✓ Export complete")


def save_garment(output_path: str):
    """
    Save the simulated garment.
    
    Args:
        output_path: Path to save the .blend file
    """
    bpy.ops.wm.save_as_mainfile(filepath=output_path)
    print(f"✓ Saved to: {output_path}")


def run_full_simulation_pipeline(garment: bpy.types.Object,
                                  output_dir: str = None,
                                  frames: int = 150,
                                  auto_export: bool = True):
    """
    Run the complete simulation and export pipeline.
    
    This is the "one-click" function that:
    1. Bakes the cloth simulation
    2. Applies the result as a static mesh
    3. Exports in multiple formats
    
    Args:
        garment: The garment with cloth physics
        output_dir: Where to save exports (default: pattern_output/exports)
        frames: Simulation frames
        auto_export: Whether to auto-export after simulation
    
    Returns:
        The static garment mesh
    """
    print("\n" + "="*60)
    print("   RUNNING FULL SIMULATION PIPELINE")
    print("="*60)
    
    # Step 1: Bake simulation
    print("\n" + "-"*40)
    bake_simulation(garment, frames)
    
    # Step 2: Apply as static mesh
    print("\n" + "-"*40)
    static_garment = apply_simulation_as_mesh(garment)
    
    # Step 3: Export
    if auto_export:
        print("\n" + "-"*40)
        if output_dir is None:
            output_dir = str(PATTERN_DIR / "exports")
        export_garment(static_garment, output_dir)
    
    print("\n" + "="*60)
    print("   SIMULATION PIPELINE COMPLETE")
    print("="*60)
    
    return static_garment


# ============================================================
# ALTERNATIVE: MANUAL MESH CREATION
# ============================================================

def create_tshirt_panels_manually(measurements: dict) -> dict:
    """
    Create T-shirt panels directly from measurements.
    
    This bypasses SVG import and creates meshes directly
    using the same geometry as step4_pattern_generation.
    
    Args:
        measurements: Dictionary with the 5 measurements
    
    Returns:
        Dictionary of mesh objects
    """
    print("→ Creating pattern meshes from measurements...")
    
    chest = measurements.get("chest_flat", 52.0)
    length = measurements.get("body_length", 72.0)
    shoulder = measurements.get("shoulder_width", 46.0)
    sleeve_len = measurements.get("sleeve_length", 22.0)
    armhole = measurements.get("armhole_depth", 24.0)
    
    panels = {}
    
    # FRONT PANEL (simplified rectangle for minimal version)
    # Full panel = both halves (unfolded)
    front_width = chest  # Full width (was half in pattern)
    front_points = [
        (-front_width/2, 0),           # Top left
        (front_width/2, 0),            # Top right
        (front_width/2, length),       # Bottom right
        (-front_width/2, length),      # Bottom left
    ]
    panels["front"] = create_pattern_mesh_from_points(front_points, "Front_Panel")
    
    # BACK PANEL (same as front for basic version)
    back_points = [
        (-front_width/2, 0),
        (front_width/2, 0),
        (front_width/2, length),
        (-front_width/2, length),
    ]
    panels["back"] = create_pattern_mesh_from_points(back_points, "Back_Panel")
    
    # SLEEVE (simplified rectangle)
    sleeve_width = armhole * 1.4
    sleeve_points = [
        (-sleeve_width/2, 0),
        (sleeve_width/2, 0),
        (sleeve_width/2, sleeve_len),
        (-sleeve_width/2, sleeve_len),
    ]
    panels["left_sleeve"] = create_pattern_mesh_from_points(sleeve_points, "Left_Sleeve")
    
    # Create a copy for right sleeve
    panels["right_sleeve"] = create_pattern_mesh_from_points(sleeve_points, "Right_Sleeve")
    
    return panels


# ============================================================
# MAIN PIPELINE
# ============================================================

def run_blender_sewing_pipeline(measurements: dict = None):
    """
    Main function to run the complete sewing pipeline.
    
    Steps:
    1. Clear scene
    2. Create/import pattern pieces
    3. Position pieces for sewing
    4. Add cloth physics
    5. Set up sewing constraints
    6. Add avatar (collision body)
    7. Run simulation
    """
    print("\n" + "="*60)
    print("   STEP 5: BLENDER SEWING & SIMULATION")
    print("="*60)
    
    # Force garbage collection at pipeline start
    gc.collect()
    
    # Default measurements if not provided
    if measurements is None:
        measurements = {
            "chest_flat": 52.0,
            "body_length": 72.0,
            "shoulder_width": 46.0,
            "sleeve_length": 22.0,
            "armhole_depth": 24.0
        }
    
    print("\n📏 Using measurements:")
    for k, v in measurements.items():
        print(f"  {k}: {v} cm")
    
    # Step 1: Clear and setup scene
    print("\n" + "-"*40)
    clear_scene()
    setup_scene()
    
    # Garbage collect after clearing scene
    gc.collect()
    
    # Step 2: Create pattern pieces
    print("\n" + "-"*40)
    print("Creating pattern pieces...")
    
    # For this minimal version, create meshes directly
    # (SVG import can be used but requires the SVG files)
    panels = create_tshirt_panels_manually(measurements)
    
    # Garbage collect after creating all panels
    gc.collect()
    
    # Step 3: Position pieces
    print("\n" + "-"*40)
    position_pattern_pieces(
        panels["front"],
        panels["back"],
        panels.get("left_sleeve"),
        panels.get("right_sleeve")
    )
    
    # Step 4: Load and setup sewing seams
    # This MUST happen BEFORE joining pieces
    print("\n" + "-"*40)
    print("Setting up sewing seams...")
    seam_defs = load_seam_definitions()
    
    if seam_defs:
        # Use seam definitions from step4
        setup_seams_from_definitions(panels, seam_defs)
    else:
        # Fall back to default seam setup
        setup_default_seams(panels)
    
    # Step 5: Join into single garment object
    print("\n" + "-"*40)
    all_pieces = [p for p in panels.values() if p is not None]
    garment = join_pattern_pieces(all_pieces, "TShirt_Garment")
    
    # Step 6: Add cloth physics WITH SEWING SPRINGS
    print("\n" + "-"*40)
    add_cloth_modifier(garment, enable_sewing=True)
    
    # Step 7: Add anatomical avatar for collision
    print("\n" + "-"*40)
    avatar_parts = add_anatomical_avatar(measurements)
    
    # Step 8: Auto-position garment around avatar
    print("\n" + "-"*40)
    position_garment_on_avatar(garment, avatar_parts, measurements)
    
    # Summary
    print("\n" + "="*60)
    print("   BLENDER SETUP COMPLETE")
    print("="*60)
    print(f"""
✓ Created garment with cloth physics
✓ Sewing springs ENABLED
✓ Anatomical avatar with collision (torso + shoulders + neck)
✓ Garment auto-positioned on avatar

AVATAR COLLISION SETUP:
- Torso: tapered cylinder (chest → waist)
- Shoulders: horizontal cylinders for natural drape
- Neck: prevents neckline from collapsing
- Friction: fabric sticks slightly for realism

SEWING SEAMS CONFIGURED:
- Side seams (left & right)
- Shoulder seams
- Sleeve attachment (if applicable)

TO RUN SIMULATION MANUALLY:
1. Press SPACEBAR to play animation
2. Or go to frame 150 to see final result
3. Watch:
   - Sewing springs pull edges together
   - Fabric drapes over avatar body
   - Natural garment shape emerges!

TO BAKE & EXPORT (AUTOMATED):
Call run_full_simulation_pipeline(garment) to:
1. Bake all simulation frames
2. Create static mesh from final frame
3. Export as OBJ, FBX, GLB

TO SAVE BLEND FILE:
- File > Save As to save .blend file
""")
    
    return garment, avatar_parts


# ============================================================
# SCRIPT ENTRY POINT
# ============================================================

# Flag to control auto-baking (set via command line or environment)
AUTO_BAKE = os.environ.get("MIRRA_AUTO_BAKE", "false").lower() == "true"
AUTO_EXPORT = os.environ.get("MIRRA_AUTO_EXPORT", "false").lower() == "true"

if __name__ == "__main__":
    """
    This script runs inside Blender.
    
    BASIC USAGE (interactive):
        blender --python step5_blender_sewing.py
    
    This will:
    - Set up the scene with cloth physics
    - Create avatar with collision
    - Position garment
    - Wait for you to press SPACEBAR to simulate
    
    AUTOMATED USAGE (bake + export):
        MIRRA_AUTO_BAKE=true blender -b --python step5_blender_sewing.py
    
    This will:
    - Do all of the above
    - Auto-bake the simulation (150 frames)
    - Create static mesh from final frame
    - Export as OBJ, FBX, GLB
    
    Options:
        -b              Run in background (no UI)
        MIRRA_AUTO_BAKE Set to "true" to auto-bake simulation
        MIRRA_AUTO_EXPORT Set to "true" to export after baking
    """
    
    # Try to load measurements from pattern_output if available
    measurements = None
    metadata_path = PATTERN_DIR / "pattern_metadata.json"
    
    if metadata_path.exists():
        try:
            with open(metadata_path, 'r') as f:
                metadata = json.load(f)
                measurements = metadata.get("measurements")
                print(f"✓ Loaded measurements from {metadata_path}")
        except:
            pass
    
    # Run the setup pipeline
    garment, avatar_parts = run_blender_sewing_pipeline(measurements)
    
    # Auto-bake if requested
    if AUTO_BAKE:
        print("\n" + "="*60)
        print("   AUTO-BAKE ENABLED")
        print("="*60)
        
        static_garment = run_full_simulation_pipeline(
            garment,
            output_dir=str(PATTERN_DIR / "exports"),
            frames=150,
            auto_export=AUTO_EXPORT
        )
        
        # Save the blend file
        blend_output = str(PATTERN_DIR / "garment_simulated.blend")
        save_garment(blend_output)
        
        print("\n" + "="*60)
        print("   STEP 5 COMPLETE — SIMULATION BAKED ✅")
        print("="*60)
        print(f"""
Output files:
  Blend file: {blend_output}
  Exports: {PATTERN_DIR / 'exports'}/
    - TShirt_Garment_Static.obj
    - TShirt_Garment_Static.fbx  
    - TShirt_Garment_Static.glb
""")
    else:
        print("\n" + "="*60)
        print("   STEP 5 SETUP COMPLETE")
        print("="*60)
        print("""
Scene is ready! To complete:

OPTION A - Interactive:
  1. Press SPACEBAR to play simulation
  2. Watch garment sew itself together
  3. File > Export when satisfied

OPTION B - Automated bake:
  In Blender Python console, run:
    run_full_simulation_pipeline(garment)

OPTION C - Re-run with auto-bake:
  MIRRA_AUTO_BAKE=true blender -b --python step5_blender_sewing.py
""")
    
    print("\nNext step: Apply color and design texture (step6)")
    print("Run: python step6_apply_texture.py")
