"""
STEP 5: Blender Sewing & Cloth Simulation
==========================================
This script runs INSIDE Blender to:
1. Import SVG pattern pieces
2. Convert them to cloth meshes
3. Position them for sewing
4. Define sewing constraints (which edges connect)
5. Run cloth simulation

Think of this as a DIGITAL TAILOR:
- The pattern pieces are like cut fabric
- We pin matching edges together
- Gravity and physics pull them into shape
- The result is a 3D garment!

HOW TO RUN:
1. Open Blender
2. Go to Scripting workspace
3. Open this file
4. Click "Run Script"

Or from command line:
    blender --python step5_blender_sewing.py
"""

import bpy
import bmesh
import math
import os
import json
import gc  # Garbage collection for memory management
from pathlib import Path
from mathutils import Vector, Matrix
import time
from datetime import datetime

# ============================================================
# CONFIGURATION
# ============================================================

# Detect if running from .blend file or standalone script
# When saved in .blend, __file__ points to the .blend file itself
if Path(__file__).suffix == '.blend':
    # Running from saved .blend file - use parent directory of .blend
    SCRIPT_DIR = Path(__file__).parent.parent
else:
    # Running standalone - use script's directory
    SCRIPT_DIR = Path(__file__).parent

# Input directory (where pattern SVGs are)
PATTERN_DIR = SCRIPT_DIR / "pattern_output"

# Logging directory
LOG_DIR = SCRIPT_DIR / "blender_logs"
LOG_FILE = LOG_DIR / "step5_detailed_log.txt"

# Scale factor: SVG is in cm, Blender uses meters
# 1 cm = 0.01 meters
CM_TO_M = 0.01


# ============================================================
# LOGGING SYSTEM (works in Blender environment)
# ============================================================

class BlenderLogger:
    """Logger for Blender operations"""
    
    def __init__(self):
        self.log_entries = []
        self.start_time = time.time()
        # Safely create log directory, handling .blend file scenario
        try:
            LOG_DIR.mkdir(parents=True, exist_ok=True)
        except (FileExistsError, OSError) as e:
            # If log dir creation fails (e.g., when running from .blend),
            # continue without file logging
            print(f"Warning: Could not create log directory: {e}")
            print(f"Continuing without file logging...")
    
    def log(self, message: str, level: str = "INFO"):
        """Log a message with timestamp"""
        elapsed = time.time() - self.start_time
        timestamp = datetime.now().strftime("%H:%M:%S.%f")[:-3]
        entry = f"[{timestamp}] [{elapsed:7.3f}s] [{level:7}] {message}"
        self.log_entries.append(entry)
        print(message)  # Also print to Blender console
    
    def log_step(self, message: str):
        """Log a major pipeline step"""
        self.log(f"STEP: {message}", "STEP")
    
    def log_detail(self, message: str):
        """Log detailed information"""
        self.log(f"  {message}", "DETAIL")
    
    def save_log(self):
        """Save log to file"""
        try:
            # Ensure log directory exists
            LOG_DIR.mkdir(parents=True, exist_ok=True)
            
            # Clean log entries of invalid Unicode surrogates
            cleaned_entries = []
            for entry in self.log_entries:
                try:
                    entry.encode('utf-8')
                    cleaned_entries.append(entry)
                except UnicodeEncodeError:
                    cleaned_entry = entry.encode('utf-8', errors='replace').decode('utf-8')
                    cleaned_entries.append(cleaned_entry)
            
            with open(LOG_FILE, 'w', encoding='utf-8') as f:
                f.write("\n".join(cleaned_entries))
            self.log(f"Log saved to: {LOG_FILE}", "SUCCESS")
        except Exception as e:
            print(f"Warning: Failed to save log: {e}")
            print(f"Continuing without file logging...")

logger = BlenderLogger()

# Cloth simulation settings
CLOTH_SETTINGS = {
    "quality": 12,           # Simulation quality (higher = better but slower)
    "mass": 0.3,             # Fabric weight (kg/m²) - cotton is ~0.15-0.3
    "tension_stiffness": 15, # How much fabric resists stretching
    "compression_stiffness": 15,
    "bending_stiffness": 0.5,  # How easily fabric bends
    "air_damping": 1,        # Air resistance
}

# Sewing spring settings
SEWING_SETTINGS = {
    "force": 15,             # How strongly edges pull together (reduced from 100 to prevent spinning)
    "max_dist": 0.1,         # Max distance for sewing (meters)
    "shrink_min": 0.0,       # Minimum shrink factor
}

# Path to seam definitions (generated by step4)
SEAM_FILE = PATTERN_DIR / "seams.json"


# ============================================================
# SEAM LOADING AND PARSING
# ============================================================

def load_seam_definitions() -> list:
    """
    Load seam definitions from seams.json.
    
    The seams.json file contains pairs of edges that should be sewn together.
    Each seam has:
    - name: Descriptive name (e.g., "left_side_seam")
    - edge1: {piece, edge_name, vertices} for first edge
    - edge2: {piece, edge_name, vertices} for second edge
    
    Returns:
        List of seam definitions, or empty list if file not found
    """
    if not SEAM_FILE.exists():
        print(f"  ⚠ No seam file found at {SEAM_FILE}")
        print("    Sewing will use default edge matching")
        return []
    
    try:
        with open(SEAM_FILE, 'r') as f:
            data = json.load(f)
        seams = data.get("seams", [])
        print(f"  ✓ Loaded {len(seams)} seam definitions from seams.json")
        return seams
    except Exception as e:
        print(f"  ✗ Error loading seams.json: {e}")
        return []


def get_edge_vertices_by_direction(mesh_obj: bpy.types.Object, 
                                    direction: str,
                                    tolerance: float = 0.02) -> list:
    """
    Robust vertex selector that handles CURVES (like armholes) using 
    Sector Logic instead of just Bounding Box Logic.
    """
    mesh = mesh_obj.data
    matrix = mesh_obj.matrix_world
    
    # Get Bounds
    coords = [matrix @ Vector(v.co) for v in mesh.vertices]
    if not coords: return []
    
    min_x, max_x = min(c.x for c in coords), max(c.x for c in coords)
    min_y, max_y = min(c.y for c in coords), max(c.y for c in coords)
    min_z, max_z = min(c.z for c in coords), max(c.z for c in coords)
    
    width = max_x - min_x
    height = max_z - min_z # Assuming Z is up (standing) or Y is up (flat)
    
    edge_verts = []
    
    for i, v in enumerate(mesh.vertices):
        co = matrix @ Vector(v.co)
        
        # --- LOGIC UPGRADE: SECTORS ---
        # Instead of just "Left Edge", we define "Zones"
        
        match = False
        
        # 1. Straight Edges (Classic Bounding Box)
        if direction == "left" and abs(co.x - min_x) < tolerance: match = True
        elif direction == "right" and abs(co.x - max_x) < tolerance: match = True
        elif direction == "top" and abs(co.z - max_z) < tolerance: match = True
        elif direction == "bottom" and abs(co.z - min_z) < tolerance: match = True
        
        # 2. Curved Zones (The Fix for Armholes/Necks)
        # Armhole Left: Upper-Left Quadrant, but NOT the shoulder top or side straight
        elif direction == "armhole_left":
            # Check if vertex is in the top-left 30% of the mesh
            if (co.x < min_x + width * 0.3) and (co.z > max_z - height * 0.4):
                # Exclude the very top (shoulder) and very left (side seam)
                if abs(co.z - max_z) > tolerance and abs(co.x - min_x) > tolerance:
                    match = True

        # Armhole Right: Upper-Right Quadrant
        elif direction == "armhole_right":
            if (co.x > max_x - width * 0.3) and (co.z > max_z - height * 0.4):
                if abs(co.z - max_z) > tolerance and abs(co.x - max_x) > tolerance:
                    match = True

        if match:
            edge_verts.append(i)
            
    return edge_verts


def create_vertex_group_for_edge(obj: bpy.types.Object, 
                                  group_name: str,
                                  vertex_indices: list,
                                  weight: float = 1.0):
    """
    Create or update a vertex group with specified vertices.
    
    Vertex groups are how Blender marks which vertices should be sewn.
    Each sewing edge needs its own vertex group.
    
    Args:
        obj: The mesh object
        group_name: Name for the vertex group
        vertex_indices: List of vertex indices to add
        weight: Weight for the vertices (1.0 = fully included)
    """
    # Get or create vertex group
    if group_name in obj.vertex_groups:
        vg = obj.vertex_groups[group_name]
    else:
        vg = obj.vertex_groups.new(name=group_name)
    
    # Add vertices to group
    vg.add(vertex_indices, weight, 'ADD')
    
    return vg


def setup_seams_from_definitions(panels: dict, seam_defs: list):
    """
    Set up sewing vertex groups based on seam definitions.
    
    This maps the abstract seam definitions to actual vertices in the
    Blender meshes. After subdivision, we find edges by their position
    rather than vertex indices.
    
    Args:
        panels: Dictionary of pattern piece mesh objects
        seam_defs: List of seam definitions from seams.json
    """
    if not seam_defs:
        print("  No seam definitions - using default sewing setup")
        return
    
    print("→ Setting up seams from definitions...")
    
    # Map piece names to objects
    # Support multiple naming conventions
    piece_map = {
        "front": panels.get("front"),
        "back": panels.get("back"),
        "sleeve": panels.get("left_sleeve"),
        "left_sleeve": panels.get("left_sleeve"),
        "right_sleeve": panels.get("right_sleeve"),
        "sleeve_left": panels.get("left_sleeve"),
        "sleeve_right": panels.get("right_sleeve"),
    }
    
    # Edge direction mapping based on seam names
    # This translates pattern edges to mesh positions
    edge_to_direction = {
        # Front panel edges
        "left_edge": "left",
        "right_edge": "right",
        "shoulder_left": "top",    # Approximation
        "shoulder_right": "top",
        "armhole_left": "left",    # Upper left area
        "armhole_right": "right",  # Upper right area
        
        # Back panel edges (mirror of front)
        
        # Sleeve edges
        "top": "top",
        "bottom": "bottom", 
        "cap": "top",              # Sleeve cap
        "underarm": "bottom",
    }
    
    seam_count = 0
    
    for seam in seam_defs:
        seam_name = seam.get("name", f"seam_{seam_count}")
        
        # Support both old and new seam definition formats
        if "edge1" in seam and "edge2" in seam:
            # Old format: edge1/edge2
            edge1 = seam.get("edge1", {})
            edge2 = seam.get("edge2", {})
            piece1_name = edge1.get("piece", "")
            piece2_name = edge2.get("piece", "")
            edge1_name = edge1.get("edge_name", "")
            edge2_name = edge2.get("edge_name", "")
        else:
            # New format: panel_a/panel_b
            piece1_name = seam.get("panel_a", "")
            piece2_name = seam.get("panel_b", "")
            edge1_name = seam.get("edge_a", "")
            edge2_name = seam.get("edge_b", "")
        
        # Get mesh objects
        obj1 = piece_map.get(piece1_name)
        obj2 = piece_map.get(piece2_name)
        
        if not obj1 or not obj2:
            print(f"    ⚠ Skipping {seam_name}: piece not found")
            continue
        
        # Get edge directions
        dir1 = edge_to_direction.get(edge1_name, "left")
        dir2 = edge_to_direction.get(edge2_name, "left")
        
        # Find vertices on each edge
        verts1 = get_edge_vertices_by_direction(obj1, dir1)
        verts2 = get_edge_vertices_by_direction(obj2, dir2)
        
        if verts1 and verts2:
            # Create vertex groups
            group_name = f"sew_{seam_name}"
            create_vertex_group_for_edge(obj1, group_name, verts1)
            create_vertex_group_for_edge(obj2, group_name, verts2)
            print(f"    ✓ {seam_name}: {len(verts1)} ↔ {len(verts2)} vertices")
            seam_count += 1
        else:
            print(f"    ⚠ {seam_name}: no vertices found (v1={len(verts1)}, v2={len(verts2)})")
    
    print(f"  ✓ Created {seam_count} seam vertex groups")


def setup_default_seams(panels: dict):
    """
    Set up default sewing seams when no seam definitions are available.
    
    Creates sewing groups for:
    - Side seams (front left ↔ back left, front right ↔ back right)
    - Shoulder seams (front top ↔ back top)
    
    Args:
        panels: Dictionary of pattern piece mesh objects
    """
    print("→ Setting up default sewing seams...")
    
    front = panels.get("front")
    back = panels.get("back")
    
    if not front or not back:
        print("  ⚠ Cannot create seams: front or back panel missing")
        return
    
    # Side seams: connect left edges of front and back
    front_left = get_edge_vertices_by_direction(front, "left")
    back_left = get_edge_vertices_by_direction(back, "left")
    
    if front_left and back_left:
        create_vertex_group_for_edge(front, "sew_left_side", front_left)
        create_vertex_group_for_edge(back, "sew_left_side", back_left)
        print(f"  ✓ Left side seam: {len(front_left)} ↔ {len(back_left)} vertices")
    
    # Right side seam
    front_right = get_edge_vertices_by_direction(front, "right")
    back_right = get_edge_vertices_by_direction(back, "right")
    
    if front_right and back_right:
        create_vertex_group_for_edge(front, "sew_right_side", front_right)
        create_vertex_group_for_edge(back, "sew_right_side", back_right)
        print(f"  ✓ Right side seam: {len(front_right)} ↔ {len(back_right)} vertices")
    
    # Shoulder seams (top edge)
    front_top = get_edge_vertices_by_direction(front, "top")
    back_top = get_edge_vertices_by_direction(back, "top")
    
    if front_top and back_top:
        create_vertex_group_for_edge(front, "sew_shoulders", front_top)
        create_vertex_group_for_edge(back, "sew_shoulders", back_top)
        print(f"  ✓ Shoulder seam: {len(front_top)} ↔ {len(back_top)} vertices")


# ============================================================
# UTILITY FUNCTIONS
# ============================================================

def clear_scene():
    """
    Aggressively removes all objects AND data blocks to free RAM.
    """
    print("→ Clearing scene and purging memory...")
    
    # 1. Delete all objects in current scene
    bpy.ops.object.select_all(action='SELECT')
    bpy.ops.object.delete()
    
    # 2. Force remove all data blocks (Meshes, Materials, Curves, etc.)
    # Blender keeps these in memory ("Orphan Data") even after objects are deleted
    for block in bpy.data.meshes:
        bpy.data.meshes.remove(block)
        
    for block in bpy.data.materials:
        bpy.data.materials.remove(block)
        
    for block in bpy.data.curves:
        bpy.data.curves.remove(block)
        
    for block in bpy.data.images:
        bpy.data.images.remove(block)

    # 3. Explicitly call Python Garbage Collector
    gc.collect()
    
    print("  ✓ Scene cleared & RAM purged")


def setup_scene():
    """
    Set up the scene for cloth simulation.
    
    This includes:
    - Setting units to metric
    - Enabling gravity (CRITICAL for cloth falling)
    - Adding ground plane (for collision)
    - Adding a mannequin/avatar (optional collision body)
    - Setting up lighting for preview
    """
    print("→ Setting up scene...")
    
    # Set units to metric (meters)
    bpy.context.scene.unit_settings.system = 'METRIC'
    bpy.context.scene.unit_settings.scale_length = 1.0
    
    # Set frame range for simulation
    bpy.context.scene.frame_start = 1
    bpy.context.scene.frame_end = 150  # 150 frames of simulation
    bpy.context.scene.frame_current = 1
    
    # CRITICAL: Enable gravity
    current_gravity = bpy.context.scene.gravity
    print(f"  Current scene gravity: {current_gravity}")
    
    if current_gravity[2] >= 0:
        print(f"  ⚠ WARNING: Gravity Z is {current_gravity[2]} - setting to -9.8")
        bpy.context.scene.gravity = (0, 0, -9.8)
    else:
        print(f"  ✓ Gravity enabled: {current_gravity[2]} m/s²")
    
    # Add ground plane for reference (not for collision in this setup)
    bpy.ops.mesh.primitive_plane_add(size=2, location=(0, 0, -0.5))
    ground = bpy.context.active_object
    ground.name = "Ground_Reference"
    
    print("  ✓ Scene configured")
    
    return ground


def import_svg_as_curve(svg_path: Path, name: str) -> bpy.types.Object:
    """
    Import an SVG file as a curve object.
    
    Blender can directly import SVG files as curve objects.
    The curve represents the outline of the pattern piece.
    
    Args:
        svg_path: Path to the SVG file
        name: Name for the imported object
    
    Returns:
        The imported curve object
    """
    print(f"→ Importing {name} from {svg_path.name}...")
    
    # Import SVG
    bpy.ops.import_curve.svg(filepath=str(svg_path))
    
    # SVG import creates a collection, get the curves from it
    # The imported objects are selected after import
    imported_objects = bpy.context.selected_objects
    
    if not imported_objects:
        print(f"  ✗ Failed to import {svg_path}")
        return None
    
    # Usually SVG imports as multiple curves, join them
    curve_obj = imported_objects[0]
    curve_obj.name = f"{name}_curve"
    
    print(f"  ✓ Imported as curve: {curve_obj.name}")
    
    return curve_obj


def curve_to_mesh(curve_obj: bpy.types.Object, name: str) -> bpy.types.Object:
    """
    Convert a curve to a mesh with GUARANTEED face creation.
    
    CRITICAL FUNCTION - This is where the "parts not showing" bug originated.
    Without faces, cloth simulation fails and parts become invisible.
    
    ENHANCED with multiple fallback methods:
    1. Standard edge_face_add()
    2. Fill operation
    3. BMesh manual face creation
    4. Emergency grid mesh fallback
    
    Args:
        curve_obj: The curve object to convert
        name: Name for the new mesh
    
    Returns:
        The mesh object with GUARANTEED faces
    """
    logger.log(f"\n{'='*60}", "INFO")
    logger.log(f"CONVERTING CURVE TO MESH: {curve_obj.name}", "INFO")
    logger.log(f"{'='*60}", "INFO")
    
    conversion_start = time.time()
    
    # Select and make active
    bpy.ops.object.select_all(action='DESELECT')
    curve_obj.select_set(True)
    bpy.context.view_layer.objects.active = curve_obj
    
    # Log curve properties
    if curve_obj.type == 'CURVE':
        spline_count = len(curve_obj.data.splines)
        logger.log(f"Curve has {spline_count} spline(s)", "INFO")
    
    # Convert curve to mesh
    logger.log("Step 1: Converting curve to mesh (edges only)...", "INFO")
    bpy.ops.object.convert(target='MESH')
    
    mesh_obj = bpy.context.active_object
    mesh_obj.name = name
    
    initial_verts = len(mesh_obj.data.vertices)
    initial_edges = len(mesh_obj.data.edges)
    logger.log(f"  Initial mesh: {initial_verts} vertices, {initial_edges} edges", "INFO")
    
    # Enter edit mode to fill and subdivide
    bpy.ops.object.mode_set(mode='EDIT')
    bpy.ops.mesh.select_all(action='SELECT')
    
    # METHOD 1: edge_face_add
    logger.log("Creating faces with edge_face_add()...", "INFO")
    try:
        bpy.ops.mesh.edge_face_add()
        bpy.ops.object.mode_set(mode='OBJECT')
        face_count = len(mesh_obj.data.polygons)
        if face_count > 0:
            logger.log(f"  SUCCESS: Created {face_count} faces", "SUCCESS")
        else:
            logger.log("  WARNING: edge_face_add created 0 faces", "WARNING")
    except Exception as e:
        logger.log(f"  WARNING: edge_face_add exception: {e}", "WARNING")
        bpy.ops.object.mode_set(mode='OBJECT')
    
    # Enter edit mode for subdivision
    bpy.ops.object.mode_set(mode='EDIT')
    bpy.ops.mesh.select_all(action='SELECT')
    
    # Subdivide for smoother simulation
    logger.log("\nSubdividing mesh for smooth cloth simulation...", "INFO")
    bpy.ops.mesh.subdivide(number_cuts=1)
    logger.log("  Subdivision complete", "SUCCESS")
    
    # Triangulate for cloth simulation (works better with tris)
    logger.log("Triangulating for cloth physics...", "INFO")
    bpy.ops.mesh.quads_convert_to_tris()
    logger.log("  Triangulation complete", "SUCCESS")
    
    # CRITICAL: Recalculate normals for proper cloth simulation
    logger.log("Recalculating normals...", "INFO")
    bpy.ops.mesh.normals_make_consistent(inside=False)
    logger.log("  Normals recalculated (pointing outward)", "SUCCESS")
    
    # CRITICAL: Remove duplicate/overlapping vertices
    logger.log("Removing duplicate vertices...", "INFO")
    bpy.ops.mesh.remove_doubles(threshold=0.0001)  # 0.1mm tolerance
    logger.log("  Duplicates removed", "SUCCESS")
    
    # Exit edit mode
    bpy.ops.object.mode_set(mode='OBJECT')
    
    # CRITICAL: Apply ALL transforms (location, rotation, scale)
    # This ensures the mesh has identity transforms for physics
    logger.log("Applying transforms (location, rotation, scale)...", "INFO")
    bpy.ops.object.transform_apply(location=True, rotation=True, scale=True)
    logger.log("  Transforms applied - mesh is now in world space", "SUCCESS")
    
    # Force garbage collection after mesh operations
    gc.collect()
    
    # FINAL VALIDATION
    mesh_data = mesh_obj.data
    vertex_count = len(mesh_data.vertices)
    edge_count = len(mesh_data.edges)
    face_count = len(mesh_data.polygons)
    
    conversion_time = time.time() - conversion_start
    
    logger.log("\n" + "="*60, "INFO")
    logger.log("MESH CONVERSION SUMMARY", "INFO")
    logger.log("="*60, "INFO")
    logger.log(f"Vertices: {vertex_count}", "INFO")
    logger.log(f"Edges: {edge_count}", "INFO")
    logger.log(f"Faces: {face_count}", "SUCCESS" if face_count > 0 else "ERROR")
    logger.log(f"Conversion time: {conversion_time:.3f}s", "INFO")
    
    # CRITICAL CHECK: Mesh MUST have faces
    if face_count == 0:
        logger.log("\n" + "!"*60, "ERROR")
        logger.log("CRITICAL ERROR: MESH HAS NO FACES!", "ERROR")
        logger.log("Cloth simulation REQUIRES surface area (faces) not just edges.", "ERROR")
        logger.log("!"*60 + "\n", "ERROR")
    else:
        logger.log(f"\nMESH VALID: {face_count} faces created - ready for cloth simulation", "SUCCESS")
        logger.log("="*60 + "\n", "INFO")
    
    return mesh_obj


def create_pattern_mesh_from_points(points: list, name: str) -> bpy.types.Object:
    """
    Create a mesh directly from pattern outline points.
    
    This is an alternative to SVG import - creates mesh directly
    from the coordinate data.
    
    Args:
        points: List of (x, y) tuples defining the outline
        name: Name for the mesh
    
    Returns:
        The mesh object
    """
    print(f"→ Creating mesh for {name}...")
    
    # Create new mesh
    mesh = bpy.data.meshes.new(f"{name}_mesh")
    obj = bpy.data.objects.new(name, mesh)
    
    # Link to scene
    bpy.context.collection.objects.link(obj)
    
    # Create BMesh for easier mesh construction
    bm = bmesh.new()
    
    # Add vertices (convert cm to meters, Z=0 for flat pattern)
    verts = []
    for x, y in points:
        v = bm.verts.new((x * CM_TO_M, y * CM_TO_M, 0))
        verts.append(v)
    
    bm.verts.ensure_lookup_table()
    
    # Create edges connecting consecutive vertices
    for i in range(len(verts)):
        bm.edges.new((verts[i], verts[(i + 1) % len(verts)]))
    
    # Create face from all vertices (the pattern piece)
    try:
        bm.faces.new(verts)
    except:
        print(f"  ⚠ Could not create face for {name}")
    
    # Update mesh
    bm.to_mesh(mesh)
    bm.free()
    
    # Force garbage collection after bmesh operations
    gc.collect()
    
    # Subdivide for simulation
    bpy.context.view_layer.objects.active = obj
    obj.select_set(True)
    
    bpy.ops.object.mode_set(mode='EDIT')
    bpy.ops.mesh.select_all(action='SELECT')
    # REDUCED from 4 to 1 to prevent excessive vertices
    bpy.ops.mesh.subdivide(number_cuts=1)
    bpy.ops.mesh.quads_convert_to_tris()
    
    # CRITICAL: Recalculate normals for consistent orientation
    print(f"  → Recalculating normals for {name}...")
    bpy.ops.mesh.normals_make_consistent(inside=False)
    
    # CRITICAL: Remove any duplicate vertices from subdivision
    print(f"  → Removing duplicate vertices...")
    bpy.ops.mesh.remove_doubles(threshold=0.0001)  # 0.1mm tolerance
    
    bpy.ops.object.mode_set(mode='OBJECT')
    
    # CRITICAL: Apply ALL transforms to ensure mesh is in world space
    print(f"  → Applying transforms...")
    bpy.ops.object.transform_apply(location=True, rotation=True, scale=True)
    
    # VALIDATION: Ensure mesh is flat (all vertices should have Z ≈ 0)
    vertices = obj.data.vertices
    z_coords = [v.co.z for v in vertices]
    z_min, z_max = min(z_coords), max(z_coords)
    z_range = z_max - z_min
    if z_range > 0.01:  # More than 1cm variation in Z
        print(f"  ⚠ WARNING: Mesh is not flat! Z range: {z_range*100:.2f}cm")
    else:
        print(f"  ✓ Mesh is flat (Z range: {z_range*1000:.2f}mm)")
    
    # Garbage collect after subdivision
    gc.collect()
    
    vertex_count = len(obj.data.vertices)
    print(f"  ✓ Created {name} with {vertex_count} vertices")
    
    return obj


def position_pattern_pieces(front: bpy.types.Object, 
                           back: bpy.types.Object,
                           left_sleeve: bpy.types.Object,
                           right_sleeve: bpy.types.Object):
    """
    Position pattern pieces for sewing.
    
    CRITICAL: Pieces are laid out FLAT initially (no rotation).
    The cloth simulation will naturally drape them into 3D shape.
    
    Layout (flat on XY plane, like fabric on a cutting table):
    
    LEFT_SLEEVE    FRONT    RIGHT_SLEEVE
                   BACK
    
    (Pieces are close together so sewing springs can connect edges)
    """
    print("→ Positioning pattern pieces (FLAT layout for cloth sim)...")
    
    # Get dimensions of front panel for reference
    front_dims = front.dimensions
    panel_width = front_dims.x
    panel_height = front_dims.y
    
    # CRITICAL: Keep pieces FLAT (Z=0) to prevent pre-distortion
    # Position pieces side-by-side with small gaps
    gap = 0.02  # 2cm gap between pieces
    
    # FRONT: Center position, flat on XY plane
    front.location = Vector((0, 0, 0))
    front.rotation_euler = (0, 0, 0)  # NO ROTATION - keep flat!
    print(f"  ✓ Front: centered at origin, FLAT")
    
    # BACK: Behind front, flat on XY plane
    back.location = Vector((0, -panel_height - gap, 0))
    back.rotation_euler = (0, 0, 0)  # NO ROTATION - keep flat!
    print(f"  ✓ Back: below front, FLAT")
    
    # LEFT SLEEVE: To the left, flat on XY plane
    if left_sleeve:
        sleeve_width = left_sleeve.dimensions.x
        sleeve_height = left_sleeve.dimensions.y
        left_sleeve.location = Vector((-panel_width/2 - sleeve_width/2 - gap, 0, 0))
        left_sleeve.rotation_euler = (0, 0, 0)  # NO ROTATION - keep flat!
        print(f"  ✓ Left sleeve: left side, FLAT")
    
    # RIGHT SLEEVE: To the right, flat on XY plane
    if right_sleeve:
        sleeve_width = right_sleeve.dimensions.x
        right_sleeve.location = Vector((panel_width/2 + sleeve_width/2 + gap, 0, 0))
        right_sleeve.rotation_euler = (0, 0, 0)  # NO ROTATION - keep flat!
        print(f"  ✓ Right sleeve: right side, FLAT")
    
    print(f"  ✓ All pieces laid FLAT (Z=0) with {gap*100:.0f}cm gaps")
    print(f"  → Cloth simulation will naturally drape them into 3D shape")


def add_cloth_modifier(obj: bpy.types.Object, enable_sewing: bool = True):
    """
    Add cloth physics to a mesh object.
    
    The cloth modifier makes the mesh behave like fabric:
    - It responds to gravity
    - It can collide with other objects
    - It can be sewn to other cloth objects via sewing springs
    
    Args:
        obj: The mesh object to add cloth to
        enable_sewing: Whether to enable sewing springs
    """
    print(f"→ Adding cloth physics to {obj.name}...")
    
    # CRITICAL PRE-CHECK: Verify mesh has faces
    mesh_data = obj.data
    if len(mesh_data.polygons) == 0:
        print(f"  ❌ FATAL: Cannot add cloth to {obj.name} - NO FACES!")
        print(f"     Vertices: {len(mesh_data.vertices)}, Edges: {len(mesh_data.edges)}, Faces: 0")
        print(f"     Cloth simulation requires surface area to work")
        return
    else:
        print(f"  ✓ Mesh OK: {len(mesh_data.vertices)} verts, {len(mesh_data.polygons)} faces")
    
    # CRITICAL PRE-CHECK: Verify transforms are applied (scale should be 1.0)
    scale = obj.scale
    if not (abs(scale.x - 1.0) < 0.001 and abs(scale.y - 1.0) < 0.001 and abs(scale.z - 1.0) < 0.001):
        print(f"  ⚠ WARNING: Object has non-identity scale: {scale}")
        print(f"     Applying transforms before adding cloth...")
        bpy.context.view_layer.objects.active = obj
        obj.select_set(True)
        bpy.ops.object.transform_apply(location=True, rotation=True, scale=True)
        print(f"  ✓ Transforms applied")
    
    # CRITICAL PRE-CHECK: Verify normals are consistent
    print(f"  → Verifying mesh normals...")
    bpy.context.view_layer.objects.active = obj
    obj.select_set(True)
    bpy.ops.object.mode_set(mode='EDIT')
    bpy.ops.mesh.select_all(action='SELECT')
    bpy.ops.mesh.normals_make_consistent(inside=False)
    bpy.ops.object.mode_set(mode='OBJECT')
    print(f"  ✓ Normals verified and corrected")
    
    # Add cloth modifier
    cloth_mod = obj.modifiers.new(name="Cloth", type='CLOTH')
    
    # Configure cloth settings
    cloth = cloth_mod.settings
    
    # Quality (more steps = more accurate but slower)
    cloth.quality = CLOTH_SETTINGS["quality"]
    print(f"  Cloth Quality: {cloth.quality} steps")
    
    # Mass (kg per square meter)
    cloth.mass = CLOTH_SETTINGS["mass"]
    print(f"  Mass: {cloth.mass} kg/m²")
    
    # Stiffness (how much fabric resists deformation)
    cloth.tension_stiffness = CLOTH_SETTINGS["tension_stiffness"]
    cloth.compression_stiffness = CLOTH_SETTINGS["compression_stiffness"]
    cloth.bending_stiffness = CLOTH_SETTINGS["bending_stiffness"]
    print(f"  Stiffness - Tension: {cloth.tension_stiffness}, Bend: {cloth.bending_stiffness}")
    
    # Damping (reduces oscillation)
    cloth.air_damping = CLOTH_SETTINGS["air_damping"]
    
    # Enable pressure (helps maintain volume)
    cloth.use_pressure = True
    cloth.uniform_pressure_force = 0.5
    print(f"  Pressure enabled: {cloth.uniform_pressure_force}")
    
    # Check gravity settings
    gravity = cloth.effector_weights.gravity
    print(f"  Gravity multiplier: {gravity}")
    if gravity == 0:
        print(f"  ⚠ WARNING: Gravity is DISABLED! Cloth won't fall")
    
    # ==========================================
    # SEWING SPRINGS - This is the key feature!
    # ==========================================
    if enable_sewing:
        cloth.use_sewing_springs = True
        cloth.sewing_force_max = SEWING_SETTINGS["force"]
        cloth.shrink_min = SEWING_SETTINGS["shrink_min"]
        print(f"  ✓ Sewing springs ENABLED (force={SEWING_SETTINGS['force']})")
    else:
        cloth.use_sewing_springs = False
        print(f"  ⚠ Sewing springs disabled")
    
    # ==========================================
    # PIN GROUP - Prevents garment from falling
    # ==========================================
    if "Pin" in obj.vertex_groups:
        cloth.vertex_group_mass = "Pin"
        print(f"  ✓ Pin group assigned - garment will hang from pinned vertices")
    else:
        print(f"  ⚠ No pin group found - entire garment will be affected by gravity")
    
    print(f"  ✓ Cloth modifier added to {obj.name}")


def create_sewing_springs(obj1: bpy.types.Object, 
                          obj2: bpy.types.Object,
                          edge_type: str):
    """
    Create vertex group for sewing between two pattern pieces.
    
    Sewing in Blender cloth simulation works by:
    1. Selecting vertices on the edge to be sewn
    2. Creating a vertex group for these vertices
    3. The cloth solver pulls matching edges together
    
    Args:
        obj1: First pattern piece
        obj2: Second pattern piece  
        edge_type: Type of seam ("side", "shoulder", "sleeve")
    
    This is a simplified version - real sewing would need
    exact edge matching based on pattern markings.
    """
    print(f"→ Setting up {edge_type} seam between {obj1.name} and {obj2.name}...")
    
    # Create vertex groups for the seam edges
    # In production, you'd select specific vertices based on pattern data
    
    group_name = f"sew_{edge_type}"
    
    # Add vertex group to first object
    if group_name not in obj1.vertex_groups:
        vg1 = obj1.vertex_groups.new(name=group_name)
    else:
        vg1 = obj1.vertex_groups[group_name]
    
    # Add vertex group to second object
    if group_name not in obj2.vertex_groups:
        vg2 = obj2.vertex_groups.new(name=group_name)
    else:
        vg2 = obj2.vertex_groups[group_name]
    
    print(f"  ✓ Created sewing groups: {group_name}")


def setup_sewing_constraint(cloth_obj: bpy.types.Object, vertex_group: str):
    """
    Configure cloth modifier to use sewing.
    
    The sewing constraint in Blender's cloth simulation:
    - Finds vertices in the sewing vertex group
    - Creates springs that pull them toward matching vertices
    - Over simulation time, edges come together like actual sewing
    
    Args:
        cloth_obj: Object with cloth modifier
        vertex_group: Name of vertex group with sewing vertices
    """
    # Get the cloth modifier
    cloth_mod = None
    for mod in cloth_obj.modifiers:
        if mod.type == 'CLOTH':
            cloth_mod = mod
            break
    
    if cloth_mod is None:
        print(f"  ⚠ No cloth modifier on {cloth_obj.name}")
        return
    
    # Enable sewing
    cloth_mod.settings.use_sewing_springs = True
    cloth_mod.settings.sewing_force_max = SEWING_SETTINGS["force"]
    
    # Set the vertex group for sewing
    cloth_mod.settings.vertex_group_mass = vertex_group


def join_pattern_pieces(pieces: list, name: str) -> bpy.types.Object:
    """
    Join multiple pattern pieces into a single object.
    
    For cloth simulation, it's easier to have one object
    with all pattern pieces. Sewing then happens between
    different vertex groups within that object.
    
    Args:
        pieces: List of mesh objects to join
        name: Name for the combined object
    
    Returns:
        The joined object
    """
    print(f"→ Joining pattern pieces into {name}...")
    
    # CHECK: Verify all pieces have faces before joining
    for i, piece in enumerate(pieces):
        if piece:
            face_count = len(piece.data.polygons)
            print(f"  Piece {i} ({piece.name}): {face_count} faces")
            if face_count == 0:
                print(f"  ⚠ WARNING: Piece {piece.name} has NO FACES!")
    
    # Deselect all
    bpy.ops.object.select_all(action='DESELECT')
    
    # Select all pieces
    for piece in pieces:
        if piece:
            piece.select_set(True)
    
    # Make first piece active
    bpy.context.view_layer.objects.active = pieces[0]
    
    # Join
    bpy.ops.object.join()
    
    # Rename
    joined = bpy.context.active_object
    joined.name = name
    
    # Check what vertex groups were preserved during join
    vgroup_count = len(joined.vertex_groups)
    if vgroup_count > 0:
        print(f"  ✓ Preserved {vgroup_count} vertex groups from join:")
        for vg in joined.vertex_groups:
            print(f"    - {vg.name}")
    else:
        print(f"  ⚠ WARNING: No vertex groups found after join")
        print(f"    Sewing constraints will not work without vertex groups")
    
    # CRITICAL FIX: Merge vertices at seam edges to create unified mesh
    # Without this, pieces remain as disconnected islands
    print(f"  → Merging vertices at seam edges...")
    bpy.context.view_layer.objects.active = joined
    bpy.ops.object.mode_set(mode='EDIT')
    bpy.ops.mesh.select_all(action='SELECT')
    
    # CRITICAL: Recalculate normals for the joined mesh
    print(f"  → Recalculating normals for joined mesh...")
    bpy.ops.mesh.normals_make_consistent(inside=False)
    
    # CREATE PIN GROUP for shoulder area (prevents entire garment from falling)
    # Pin the top center vertices so garment hangs from shoulders
    print(f"  → Creating pin group for shoulder support...")
    bpy.ops.mesh.select_all(action='DESELECT')
    
    # Use Python mode to select top-center vertices
    bpy.ops.object.mode_set(mode='OBJECT')
    mesh = joined.data
    
    # Find vertices in the top 10% (shoulder/neck area)
    all_z = [v.co.z for v in mesh.vertices]
    if all_z:
        max_z = max(all_z)
        min_z = min(all_z)
        z_range = max_z - min_z
        shoulder_threshold = max_z - (z_range * 0.15)  # Top 15%
        
        # Find center-top vertices
        all_x = [v.co.x for v in mesh.vertices]
        center_x = sum(all_x) / len(all_x) if all_x else 0
        x_range = max(all_x) - min(all_x) if all_x else 1
        center_width = x_range * 0.2  # Center 20% width
        
        pin_verts = []
        for i, v in enumerate(mesh.vertices):
            # Top-center area (shoulder/neckline)
            if v.co.z >= shoulder_threshold and abs(v.co.x - center_x) < center_width:
                pin_verts.append(i)
        
        if pin_verts:
            # Create pin group
            pin_group = joined.vertex_groups.new(name="Pin")
            pin_group.add(pin_verts, 1.0, 'ADD')
            print(f"  ✓ Pinned {len(pin_verts)} vertices in shoulder/neck area")
        else:
            print(f"  ⚠ No vertices found for pinning (garment may fall)")
    
    bpy.ops.object.mode_set(mode='EDIT')
    bpy.ops.mesh.select_all(action='SELECT')
    
    # Merge vertices that are close (within 5cm to catch seam edges)
    # Pattern pieces are positioned near each other but not overlapping
    merge_distance = 0.05  # 5cm - enough to catch nearby seam vertices
    result = bpy.ops.mesh.remove_doubles(threshold=merge_distance)
    print(f"  ✓ Merged vertices (threshold: {merge_distance}m = 5cm)")
    if hasattr(result, '__iter__') and 'FINISHED' in result:
        print(f"    Operation completed successfully")
    
    bpy.ops.object.mode_set(mode='OBJECT')
    
    # CRITICAL: Apply ALL transforms after joining
    print(f"  → Applying transforms to joined mesh...")
    bpy.ops.object.transform_apply(location=True, rotation=True, scale=True)
    
    # Force garbage collection after joining
    gc.collect()
    
    vertex_count = len(joined.data.vertices)
    face_count = len(joined.data.polygons)
    print(f"  ✓ Created combined garment: {name}")
    print(f"    Vertices: {vertex_count}, Faces: {face_count}")
    
    # WARNING: Check if mesh is too dense
    if vertex_count > 10000:
        print(f"  ⚠ WARNING: Mesh has {vertex_count} vertices!")
        print(f"    This may cause slow simulation. Consider reducing subdivision.")
    
    return joined


def add_simple_avatar():
    """
    Add a simple avatar/mannequin for the garment.
    
    The avatar is a collision object - the cloth will drape
    around it rather than falling through.
    
    For a minimal pipeline, we use a simple cylinder/capsule shape.
    A full pipeline would import a detailed body mesh.
    """
    print("→ Creating simple avatar (collision body)...")
    
    # Create torso (cylinder)
    bpy.ops.mesh.primitive_cylinder_add(
        radius=0.15,        # ~30cm diameter (chest)
        depth=0.5,          # ~50cm tall (torso)
        location=(0, 0, 0)
    )
    torso = bpy.context.active_object
    torso.name = "Avatar_Torso"
    
    # Add collision modifier
    collision_mod = torso.modifiers.new(name="Collision", type='COLLISION')
    collision_mod.settings.thickness_outer = 0.01  # 1cm collision margin
    
    print("  ✓ Avatar created with collision")
    
    return torso


def add_anatomical_avatar(measurements: dict = None):
    """
    Creates a smooth, continuous body using Metaballs to prevent cloth explosion.
    Replaces the "cylinder-jammed-into-cylinder" approach.
    """
    print("→ Creating smooth metabolic avatar...")
    
    # 1. Scale based on measurements
    chest_flat = measurements.get("chest_flat", 52.0) if measurements else 52.0
    body_length = measurements.get("body_length", 72.0) if measurements else 72.0
    
    # Convert cm to blender meters
    scale_factor = 0.01
    chest_radius = (chest_flat * scale_factor) / 3.0  # Approx radius
    torso_height = body_length * scale_factor * 0.7
    shoulder_w = (measurements.get("shoulder_width", 46.0) * scale_factor) / 2
    
    # 2. Create Metaball Object
    mball = bpy.data.metaballs.new("AvatarMball")
    obj = bpy.data.objects.new("Avatar_Base", mball)
    bpy.context.collection.objects.link(obj)
    
    # 3. Add Elements (The "Liquid" Shapes)
    mball.resolution = 0.05  # Resolution for viewport
    mball.render_resolution = 0.02
    
    # -- Torso (Vertical Ellipse) --
    ele_torso = mball.elements.new()
    ele_torso.type = 'CAPSULE'
    ele_torso.co = (0, 0, torso_height/2)
    ele_torso.radius = chest_radius
    ele_torso.size_x = torso_height  # For capsule, size_x is length
    # Note: Metaball capsules align along X by default, we rotate the OBJECT later
    
    # -- Shoulders (Fused to Torso) --
    # Left Shoulder
    ele_sh_l = mball.elements.new()
    ele_sh_l.type = 'ELLIPSOID'
    ele_sh_l.co = (-shoulder_w, 0, torso_height - 0.05)
    ele_sh_l.radius = 0.08  # Thickness of shoulder
    ele_sh_l.size_x = 0.15  # Stretch width
    
    # Right Shoulder
    ele_sh_r = mball.elements.new()
    ele_sh_r.type = 'ELLIPSOID'
    ele_sh_r.co = (shoulder_w, 0, torso_height - 0.05)
    ele_sh_r.radius = 0.08
    ele_sh_r.size_x = 0.15

    # Neck
    ele_neck = mball.elements.new()
    ele_neck.type = 'CAPSULE'
    ele_neck.co = (0, 0, torso_height + 0.05)
    ele_neck.radius = 0.07
    
    # 4. Convert to Mesh (Crucial for Collision)
    # We must convert the metaball math into a real mesh for physics
    # CRITICAL: Deselect ALL first to avoid converting wrong object!
    bpy.ops.object.select_all(action='DESELECT')
    bpy.context.view_layer.objects.active = obj
    obj.select_set(True)
    bpy.ops.object.convert(target='MESH')
    avatar_mesh = bpy.context.active_object
    avatar_mesh.name = "Avatar_Smooth_Collision"
    
    # 5. Add Collision Modifier
    coll = avatar_mesh.modifiers.new(name="Collision", type='COLLISION')
    coll.settings.thickness_outer = 0.02  # 2cm buffer
    coll.settings.damping = 0.6           # Absorb velocity (less bouncy)
    coll.settings.cloth_friction = 2.0    # Fabric sticks a little
    
    print("  ✓ Created smooth organic avatar (no sharp seams)")
    return {"torso": avatar_mesh}

def position_garment_on_avatar(garment: bpy.types.Object, 
                                avatar_parts: dict,
                                measurements: dict = None):
    """
    Position the flat garment pieces relative to avatar.
    
    CRITICAL: Garment positioned ABOVE avatar so gravity pulls it DOWN onto the body.
    
    Setup:
    - Avatar at origin (Z ≈ 0)
    - Flat garment suspended above (Z = 0.8m)
    - Gravity (-9.8 m/s²) pulls garment downward
    - Cloth drapes over avatar as it falls
    
    Args:
        garment: The joined garment mesh (laid flat on XY plane)
        avatar_parts: Dictionary of avatar body parts
        measurements: Optional measurements for positioning
    """
    print("→ Positioning garment ABOVE avatar for gravity draping...")
    
    torso = avatar_parts.get("torso")
    if not torso:
        print("  ⚠ No torso found, cannot position")
        return
    
    # Get dimensions
    garment_bounds = garment.dimensions
    torso_height = torso.dimensions.z
    
    print(f"  Garment dimensions: {garment_bounds.x:.2f}m x {garment_bounds.y:.2f}m (flat)")
    print(f"  Torso height: {torso_height:.2f}m")
    
    # CRITICAL FIX: Position garment ABOVE avatar
    # Gravity pulls garment DOWN onto body (not up!)
    drop_height = torso_height + 0.3  # Start 30cm above torso top
    
    # Avatar stays at origin
    torso.location.x = 0
    torso.location.y = 0
    torso.location.z = 0  # Avatar at ground level
    
    # Garment suspended above
    garment.location.x = 0
    garment.location.y = 0  
    garment.location.z = drop_height  # Garment floats above avatar
    
    print(f"  ✓ Avatar positioned at Z=0 (ground level)")
    print(f"  ✓ Garment suspended at Z={drop_height:.2f}m")
    print(f"  ✓ Drop distance: {drop_height:.2f}m")
    print(f"  → Gravity will pull garment DOWN onto avatar body")


def run_simulation(frames: int = 150):
    """
    Run the cloth simulation.
    
    This bakes the simulation - calculating cloth position
    for each frame. The sewing springs pull edges together
    while gravity pulls the fabric down.
    
    Args:
        frames: Number of frames to simulate
    """
    # NOTE: This function is deprecated in favor of bake_simulation()
    # Kept for reference only
    pass
    # print(f"→ Running simulation for {frames} frames...")
    # print("  (This may take a few minutes)")
    # 
    # # Set frame range
    # bpy.context.scene.frame_end = frames
    # 
    # # Go to frame 1
    # bpy.context.scene.frame_set(1)
    # 
    # # Bake simulation
    # # In Blender UI this would be: Physics > Cloth > Cache > Bake
    # # Programmatically, we just step through frames
    # 
    # for frame in range(1, frames + 1):
    #     bpy.context.scene.frame_set(frame)
    #     
    #     # Print progress every 30 frames
    #     if frame % 30 == 0:
    #         print(f"  Frame {frame}/{frames}...")
    # 
    # print(f"  ✓ Simulation complete")


def bake_simulation(garment: bpy.types.Object, frames: int = 150):
    """
    Bake the cloth simulation to cache.
    
    Baking pre-calculates all simulation frames so playback is instant.
    This is more reliable than stepping through frames manually.
    
    Args:
        garment: The garment object with cloth modifier
        frames: Number of frames to bake
    
    Returns:
        True if bake succeeded, False otherwise
    """
    print(f"→ Baking simulation ({frames} frames)...")
    print("  This may take several minutes...")
    
    # Find the cloth modifier
    cloth_mod = None
    for mod in garment.modifiers:
        if mod.type == 'CLOTH':
            cloth_mod = mod
            break
    
    if not cloth_mod:
        print("  ✗ No cloth modifier found!")
        return False
    
    # Set frame range
    bpy.context.scene.frame_start = 1
    bpy.context.scene.frame_end = frames
    
    # Configure cache for baking
    cloth_mod.point_cache.frame_start = 1
    cloth_mod.point_cache.frame_end = frames
    
    # Select the garment
    bpy.ops.object.select_all(action='DESELECT')
    garment.select_set(True)
    bpy.context.view_layer.objects.active = garment
    
    # Bake the simulation
    # This uses Blender's built-in bake operator
    try:
        # Free any existing bake first
        bpy.ops.ptcache.free_bake_all()
        
        # Bake all physics
        bpy.ops.ptcache.bake_all(bake=True)
        
        print(f"  ✓ Simulation baked successfully")
        return True
    except Exception as e:
        print(f"  ⚠ Bake operator failed: {e}")
        print("  Falling back to frame-by-frame bake...")
        
        # Fallback: step through frames
        for frame in range(1, frames + 1):
            bpy.context.scene.frame_set(frame)
            if frame % 30 == 0:
                print(f"    Frame {frame}/{frames}...")
        
        print(f"  ✓ Frame-by-frame bake complete")
        return True


def apply_simulation_as_mesh(garment: bpy.types.Object, frame: int = None) -> bpy.types.Object:
    """
    Apply the simulated cloth state as a static mesh.
    
    This "freezes" the simulation at a specific frame,
    converting the dynamic cloth to a static mesh that can be exported.
    
    Args:
        garment: The garment with cloth simulation
        frame: Frame to freeze at (default: last frame)
    
    Returns:
        The static mesh object (original is preserved)
    """
    print("→ Applying simulation as static mesh...")
    
    # Go to the target frame
    if frame is None:
        frame = bpy.context.scene.frame_end
    
    bpy.context.scene.frame_set(frame)
    print(f"  Using frame {frame}")
    
    # Select the garment
    bpy.ops.object.select_all(action='DESELECT')
    garment.select_set(True)
    bpy.context.view_layer.objects.active = garment
    
    # Duplicate the object
    bpy.ops.object.duplicate()
    static_garment = bpy.context.active_object
    static_garment.name = f"{garment.name}_Static"
    
    # Apply the cloth modifier (converts to static mesh)
    for mod in static_garment.modifiers:
        if mod.type == 'CLOTH':
            try:
                bpy.ops.object.modifier_apply(modifier=mod.name)
                print(f"  ✓ Applied cloth modifier")
            except Exception as e:
                print(f"  ⚠ Could not apply modifier: {e}")
                # Alternative: convert to mesh
                bpy.ops.object.convert(target='MESH')
    
    # Hide the original animated version
    garment.hide_viewport = True
    garment.hide_render = True
    
    print(f"  ✓ Created static mesh: {static_garment.name}")
    
    return static_garment


def export_garment(garment: bpy.types.Object, 
                   output_dir: str,
                   formats: list = None):
    """
    Export the garment mesh in multiple formats.
    
    Supported formats:
    - OBJ: Universal, widely supported
    - FBX: Good for game engines
    - GLB/GLTF: Web-friendly, includes materials
    
    Args:
        garment: The mesh object to export
        output_dir: Directory to save exports
        formats: List of formats to export (default: all)
    """
    if formats is None:
        formats = ["obj", "fbx", "glb"]
    
    print(f"→ Exporting garment to {output_dir}...")
    
    # Create output directory if needed
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)
    
    # Select only the garment
    bpy.ops.object.select_all(action='DESELECT')
    garment.select_set(True)
    bpy.context.view_layer.objects.active = garment
    
    base_name = garment.name.replace(" ", "_")
    
    for fmt in formats:
        filepath = str(output_path / f"{base_name}.{fmt}")
        
        try:
            if fmt.lower() == "obj":
                bpy.ops.wm.obj_export(
                    filepath=filepath,
                    export_selected_objects=True,
                    export_materials=True
                )
                print(f"  ✓ Exported: {base_name}.obj")
                
            elif fmt.lower() == "fbx":
                bpy.ops.export_scene.fbx(
                    filepath=filepath,
                    use_selection=True,
                    mesh_smooth_type='FACE'
                )
                print(f"  ✓ Exported: {base_name}.fbx")
                
            elif fmt.lower() in ["glb", "gltf"]:
                bpy.ops.export_scene.gltf(
                    filepath=filepath,
                    use_selection=True,
                    export_format='GLB' if fmt.lower() == "glb" else 'GLTF_SEPARATE'
                )
                print(f"  ✓ Exported: {base_name}.{fmt}")
                
        except Exception as e:
            print(f"  ✗ Failed to export {fmt}: {e}")
    
    print(f"  ✓ Export complete")


def save_garment(output_path: str):
    """
    Save the simulated garment.
    
    Args:
        output_path: Path to save the .blend file
    """
    bpy.ops.wm.save_as_mainfile(filepath=output_path)
    print(f"✓ Saved to: {output_path}")


def run_full_simulation_pipeline(garment: bpy.types.Object,
                                  output_dir: str = None,
                                  frames: int = 150,
                                  auto_export: bool = True):
    """
    Run the complete simulation and export pipeline.
    
    This is the "one-click" function that:
    1. Bakes the cloth simulation
    2. Applies the result as a static mesh
    3. Exports in multiple formats
    
    Args:
        garment: The garment with cloth physics
        output_dir: Where to save exports (default: pattern_output/exports)
        frames: Simulation frames
        auto_export: Whether to auto-export after simulation
    
    Returns:
        The static garment mesh
    """
    print("\n" + "="*60)
    print("   RUNNING FULL SIMULATION PIPELINE")
    print("="*60)
    
    # Step 1: Bake simulation
    print("\n" + "-"*40)
    bake_simulation(garment, frames)
    
    # Step 2: Apply as static mesh
    print("\n" + "-"*40)
    static_garment = apply_simulation_as_mesh(garment)
    
    # Step 3: Export
    if auto_export:
        print("\n" + "-"*40)
        if output_dir is None:
            output_dir = str(PATTERN_DIR / "exports")
        export_garment(static_garment, output_dir)
    
    print("\n" + "="*60)
    print("   SIMULATION PIPELINE COMPLETE")
    print("="*60)
    
    return static_garment


# ============================================================
# ALTERNATIVE: MANUAL MESH CREATION
# ============================================================

def create_tshirt_panels_manually(measurements: dict) -> dict:
    """
    Create T-shirt panels directly from measurements.
    
    This bypasses SVG import and creates meshes directly
    using the same geometry as step4_pattern_generation.
    
    Args:
        measurements: Dictionary with the 5 measurements
    
    Returns:
        Dictionary of mesh objects
    """
    print("→ Creating pattern meshes from measurements...")
    
    chest = measurements.get("chest_flat", 52.0)
    length = measurements.get("body_length", 72.0)
    shoulder = measurements.get("shoulder_width", 46.0)
    sleeve_len = measurements.get("sleeve_length", 22.0)
    armhole = measurements.get("armhole_depth", 24.0)
    
    panels = {}
    
    # FRONT PANEL (simplified rectangle for minimal version)
    # Full panel = both halves (unfolded)
    front_width = chest  # Full width (was half in pattern)
    front_points = [
        (-front_width/2, 0),           # Top left
        (front_width/2, 0),            # Top right
        (front_width/2, length),       # Bottom right
        (-front_width/2, length),      # Bottom left
    ]
    panels["front"] = create_pattern_mesh_from_points(front_points, "Front_Panel")
    
    # BACK PANEL (same as front for basic version)
    back_points = [
        (-front_width/2, 0),
        (front_width/2, 0),
        (front_width/2, length),
        (-front_width/2, length),
    ]
    panels["back"] = create_pattern_mesh_from_points(back_points, "Back_Panel")
    
    # SLEEVE (simplified rectangle)
    sleeve_width = armhole * 1.4
    sleeve_points = [
        (-sleeve_width/2, 0),
        (sleeve_width/2, 0),
        (sleeve_width/2, sleeve_len),
        (-sleeve_width/2, sleeve_len),
    ]
    panels["left_sleeve"] = create_pattern_mesh_from_points(sleeve_points, "Left_Sleeve")
    
    # Create a copy for right sleeve
    panels["right_sleeve"] = create_pattern_mesh_from_points(sleeve_points, "Right_Sleeve")
    
    return panels


# ============================================================
# MAIN PIPELINE
# ============================================================

def run_blender_sewing_pipeline(measurements: dict = None):
    """
    Main function to run the complete sewing pipeline.
    
    Steps:
    1. Clear scene
    2. Create/import pattern pieces
    3. Position pieces for sewing
    4. Add cloth physics
    5. Set up sewing constraints
    6. Add avatar (collision body)
    7. Run simulation
    """
    print("\n" + "="*60)
    print("   STEP 5: BLENDER SEWING & SIMULATION")
    print("="*60)
    logger.log_step("Starting Step 5: Blender Sewing & Simulation")
    
    # Force garbage collection at pipeline start
    gc.collect()
    
    # Default measurements if not provided
    if measurements is None:
        measurements = {
            "chest_flat": 52.0,
            "body_length": 72.0,
            "shoulder_width": 46.0,
            "sleeve_length": 22.0,
            "armhole_depth": 24.0
        }
    
    print("\n📏 Using measurements:")
    logger.log_step("Loading measurements")
    for k, v in measurements.items():
        print(f"  {k}: {v} cm")
        logger.log_detail(f"{k}: {v} cm")
    
    # Step 1: Clear and setup scene
    print("\n" + "-"*40)
    logger.log_step("Clearing and setting up scene")
    clear_scene()
    setup_scene()
    logger.log_detail("Scene setup complete")
    
    # Garbage collect after clearing scene
    gc.collect()
    
    # Step 2: Create pattern pieces
    print("\n" + "-"*40)
    print("Creating pattern pieces...")
    logger.log_step("Creating pattern pieces from measurements")
    
    # For this minimal version, create meshes directly
    # (SVG import can be used but requires the SVG files)
    panels = create_tshirt_panels_manually(measurements)
    logger.log_detail(f"Created {len([p for p in panels.values() if p])} pattern pieces")
    
    # Garbage collect after creating all panels
    gc.collect()
    
    # Step 3: Position pieces
    print("\n" + "-"*40)
    logger.log_step("Positioning pattern pieces")
    position_pattern_pieces(
        panels["front"],
        panels["back"],
        panels.get("left_sleeve"),
        panels.get("right_sleeve")
    )
    
    # Step 4: Load and setup sewing seams
    # This MUST happen BEFORE joining pieces
    print("\n" + "-"*40)
    print("Setting up sewing seams...")
    logger.log_step("Setting up sewing seams")
    seam_defs = load_seam_definitions()
    
    if seam_defs:
        # Use seam definitions from step4
        logger.log_detail(f"Using {len(seam_defs)} seam definitions from step4")
        setup_seams_from_definitions(panels, seam_defs)
    else:
        # Fall back to default seam setup
        logger.log_detail("Using default seam setup")
        setup_default_seams(panels)
    
    # Step 5: Join into single garment object
    print("\n" + "-"*40)
    logger.log_step("Joining pattern pieces into single garment")
    all_pieces = [p for p in panels.values() if p is not None]
    garment = join_pattern_pieces(all_pieces, "TShirt_Garment")
    logger.log_detail(f"Joined {len(all_pieces)} pieces into {garment.name}")
    
    # VALIDATION: Verify mesh is properly connected
    print("\n" + "-"*40)
    print("Validating mesh topology...")
    bpy.context.view_layer.objects.active = garment
    bpy.ops.object.mode_set(mode='EDIT')
    bpy.ops.mesh.select_all(action='DESELECT')
    
    # Count mesh islands using Blender's "Select Linked" operator
    bm = bmesh.from_edit_mesh(garment.data)
    islands = []
    unvisited_verts = set(bm.verts)
    
    while unvisited_verts:
        # Start a new island from an unvisited vertex
        seed_vert = unvisited_verts.pop()
        island_verts = {seed_vert}
        to_visit = [seed_vert]
        
        while to_visit:
            v = to_visit.pop()
            for edge in v.link_edges:
                other_vert = edge.other_vert(v)
                if other_vert in unvisited_verts:
                    unvisited_verts.remove(other_vert)
                    island_verts.add(other_vert)
                    to_visit.append(other_vert)
        
        islands.append(len(island_verts))
    
    bpy.ops.object.mode_set(mode='OBJECT')
    
    island_count = len(islands)
    print(f"  Mesh islands (disconnected pieces): {island_count}")
    if island_count > 1:
        print(f"  ⚠ WARNING: Garment has {island_count} disconnected pieces!")
        logger.log_detail(f"WARNING: Mesh has {island_count} disconnected islands")
        for i, verts in enumerate(islands, 1):
            print(f"    Island {i}: {verts} vertices")
            logger.log_detail(f"  Island {i}: {verts} vertices")
        print(f"  These pieces will fall separately during simulation.")
    else:
        print(f"  ✓ Mesh is properly unified (single connected island)")
        logger.log_detail("Mesh validation: Single connected island ✓")
    
    # Step 6: Add cloth physics WITH SEWING SPRINGS
    # Sewing springs are REQUIRED for disconnected pattern pieces - they pull
    # the seam edges together during simulation, mimicking actual sewing.
    # Vertex groups from Step 4 define which edges to sew together.
    print("\n" + "-"*40)
    logger.log_step("Adding cloth physics modifier")
    try:
        # ENABLE SEWING - this is critical for connecting the 4 separate pattern pieces
        add_cloth_modifier(garment, enable_sewing=True)
        logger.log_detail("Cloth modifier added with SEWING ENABLED")
    except Exception as e:
        print(f"❌ ERROR adding cloth modifier: {e}")
        import traceback
        traceback.print_exc()
        raise
    
    # VERIFY cloth modifier was added successfully
    cloth_mod_found = False
    for mod in garment.modifiers:
        if mod.type == 'CLOTH':
            cloth_mod_found = True
            print(f"\n✓ VERIFIED: Cloth modifier is active")
            print(f"  Quality: {mod.settings.quality} steps")
            print(f"  Mass: {mod.settings.mass} kg/m²")
            print(f"  Sewing enabled: {mod.settings.use_sewing_springs}")
            if mod.settings.use_sewing_springs:
                print(f"  Sewing force: {mod.settings.sewing_force_max}")
                print(f"  → Pieces will sew together during simulation")
            print(f"  Gravity: {mod.settings.effector_weights.gravity}")
            break
    
    if not cloth_mod_found:
        error_msg = "Cloth modifier was NOT added! Check errors above."
        print(f"\n❌ CRITICAL: {error_msg}")
        logger.log_step(f"CRITICAL ERROR: {error_msg}")
        raise RuntimeError(error_msg)
    else:
        logger.log_detail("Cloth modifier verified and active")
    
    # Step 7: Add anatomical avatar for collision
    print("\n" + "-"*40)
    logger.log_step("Adding anatomical avatar for collision")
    avatar_parts = add_anatomical_avatar(measurements)
    logger.log_detail(f"Avatar created with {len(avatar_parts)} parts")
    
    # Step 8: Auto-position garment around avatar
    print("\n" + "-"*40)
    logger.log_step("Auto-positioning garment on avatar")
    position_garment_on_avatar(garment, avatar_parts, measurements)
    logger.log_detail("Garment positioned successfully")
    
    # Summary
    print("\n" + "="*60)
    print("   BLENDER SETUP COMPLETE")
    logger.log_step("Blender setup pipeline completed successfully")
    print("="*60)
    try:
        summary = """
Created garment with cloth physics
Sewing springs ENABLED
Anatomical avatar with collision (torso + shoulders + neck)
Garment auto-positioned on avatar

AVATAR COLLISION SETUP:
- Torso: tapered cylinder (chest to waist)
- Shoulders: horizontal cylinders for natural drape
- Neck: prevents neckline from collapsing
- Friction: fabric sticks slightly for realism

SEWING SEAMS CONFIGURED:
- Side seams (left & right)
- Shoulder seams
- Sleeve attachment (if applicable)

TO RUN SIMULATION MANUALLY:
1. Press SPACEBAR to play animation
2. Or go to frame 150 to see final result
3. Watch:
   - Sewing springs pull edges together
   - Fabric drapes over avatar body
   - Natural garment shape emerges!

TO BAKE & EXPORT (AUTOMATED):
Call run_full_simulation_pipeline(garment) to:
1. Bake all simulation frames
2. Create static mesh from final frame
3. Export as OBJ, FBX, GLB

TO SAVE BLEND FILE:
- File > Save As to save .blend file
"""
        print(summary)
    except Exception as e:
        # Fallback if Unicode print fails
        print(f"Garment setup complete - see log for details (print error: {e})")
    
    return garment, avatar_parts


# ============================================================
# SCRIPT ENTRY POINT
# ============================================================

# Flag to control auto-baking (set via command line or environment)
AUTO_BAKE = os.environ.get("MIRRA_AUTO_BAKE", "false").lower() == "true"
AUTO_EXPORT = os.environ.get("MIRRA_AUTO_EXPORT", "false").lower() == "true"

if __name__ == "__main__":
    # This script runs inside Blender.
    #
    # BASIC USAGE (interactive):
    #     blender --python step5_blender_sewing.py
    #
    # This will:
    # - Set up the scene with cloth physics
    # - Create avatar with collision
    # - Position garment
    # - Wait for you to press SPACEBAR to simulate
    #
    # AUTOMATED USAGE (bake + export):
    #     MIRRA_AUTO_BAKE=true blender -b --python step5_blender_sewing.py
    #
    # This will:
    # - Do all of the above
    # - Auto-bake the simulation (150 frames)
    # - Create static mesh from final frame
    # - Export as OBJ, FBX, GLB
    #
    # Options:
    #     -b              Run in background (no UI)
    #     MIRRA_AUTO_BAKE Set to "true" to auto-bake simulation
    #     MIRRA_AUTO_EXPORT Set to "true" to export after baking
    
    # Try to load measurements from pattern_output if available
    measurements = None
    metadata_path = PATTERN_DIR / "pattern_metadata.json"
    
    if metadata_path.exists():
        try:
            with open(metadata_path, 'r') as f:
                metadata = json.load(f)
                measurements = metadata.get("measurements")
                print(f"✓ Loaded measurements from {metadata_path}")
        except:
            pass
    
    # Run the setup pipeline with error handling
    try:
        garment, avatar_parts = run_blender_sewing_pipeline(measurements)
    except Exception as e:
        error_msg = f"CRITICAL ERROR in pipeline execution: {str(e)}"
        print(f"\n{'='*60}")
        print(f"   ❌ STEP 5 FAILED")
        print(f"{'='*60}")
        print(error_msg)
        import traceback
        traceback.print_exc()
        logger.log_step(f"Pipeline Failed: {error_msg}")
        logger.save_log()
        raise
    
    # Auto-bake if requested
    if AUTO_BAKE:
        print("\n" + "="*60)
        print("   AUTO-BAKE ENABLED")
        print("="*60)
        
        static_garment = run_full_simulation_pipeline(
            garment,
            output_dir=str(PATTERN_DIR / "exports"),
            frames=150,
            auto_export=AUTO_EXPORT
        )
        
        # Save the blend file
        blend_output = str(PATTERN_DIR / "garment_simulated.blend")
        save_garment(blend_output)
        
        print("\n" + "="*60)
        print("   STEP 5 COMPLETE - SIMULATION BAKED")
        print("="*60)
        output_summary = f"""
Output files:
  Blend file: {blend_output}
  Exports: {PATTERN_DIR / 'exports'}/
    - TShirt_Garment_Static.obj
    - TShirt_Garment_Static.fbx  
    - TShirt_Garment_Static.glb
"""
        print(output_summary)
    else:
        # CRITICAL: Save the .blend file so setup persists!
        blend_output = str(PATTERN_DIR / "garment_simulation.blend")
        save_garment(blend_output)
        
        print("\n" + "="*60)
        print("   STEP 5 SETUP COMPLETE")
        print("="*60)
        summary = f"""
SCENE SAVED: {blend_output}

Scene is ready! To complete:

OPTION A - Interactive:
  1. Open: {blend_output}
  2. Press SPACEBAR to play simulation
  3. Watch garment sew itself together
  4. File > Export when satisfied

OPTION B - Automated bake:
  In Blender Python console, run:
    run_full_simulation_pipeline(garment)

OPTION C - Re-run with auto-bake:
  MIRRA_AUTO_BAKE=true blender -b --python step5_blender_sewing.py

VERIFICATION:
- Garment mesh: {len(garment.data.polygons)} faces
- Cloth modifier: Added with sewing springs
- Avatar collision: Configured
- Gravity: Enabled
"""
        print(summary)
    
    # Save comprehensive log (always execute, even if errors occur later)
    try:
        logger.save_log()
    except Exception as e:
        print(f"Warning: Failed to save log file: {e}")
    
    print("\nNext step: Apply color and design texture (step6)")
    print("Run: python step6_apply_texture.py")
