"""Default seam map for the 4-piece t-shirt pattern set."""

DEFAULT_SEAMS = [
    {"name": "side-right", "a": 0, "la": 1, "b": 1, "lb": 1, "da": True, "db": True},
    {"name": "side-left", "a": 0, "la": 18, "b": 1, "lb": 17, "da": True, "db": True},
    {"name": "shoulder-right", "a": 0, "la": 8, "b": 1, "lb": 8, "da": True, "db": True},
    {"name": "shoulder-left", "a": 0, "la": 11, "b": 1, "lb": 10, "da": True, "db": True},
    {"name": "sleeve-L-tube", "a": 2, "la": 1, "b": 2, "lb": 12, "da": True, "db": False},
    {"name": "sleeve-R-tube", "a": 3, "la": 1, "b": 3, "lb": 12, "da": True, "db": False},
    {"name": "arm-R-fr-0", "a": 0, "la": 2, "b": 3, "lb": 2, "da": True, "db": True},
    {"name": "arm-R-fr-1", "a": 0, "la": 3, "b": 3, "lb": 3, "da": True, "db": True},
    {"name": "arm-R-fr-2", "a": 0, "la": 4, "b": 3, "lb": 4, "da": True, "db": True},
    {"name": "arm-R-fr-3", "a": 0, "la": 5, "b": 3, "lb": 5, "da": True, "db": True},
    {"name": "arm-R-fr-4", "a": 0, "la": 6, "b": 3, "lb": 6, "da": True, "db": True},
    {"name": "arm-R-bk-0", "a": 1, "la": 2, "b": 3, "lb": 11, "da": True, "db": True},
    {"name": "arm-R-bk-1", "a": 1, "la": 3, "b": 3, "lb": 10, "da": True, "db": True},
    {"name": "arm-R-bk-2", "a": 1, "la": 4, "b": 3, "lb": 9, "da": True, "db": True},
    {"name": "arm-R-bk-3", "a": 1, "la": 5, "b": 3, "lb": 8, "da": True, "db": True},
    {"name": "arm-R-bk-4", "a": 1, "la": 6, "b": 3, "lb": 7, "da": True, "db": True},
    {"name": "arm-L-fr-0", "a": 0, "la": 13, "b": 2, "lb": 11, "da": True, "db": True},
    {"name": "arm-L-fr-1", "a": 0, "la": 14, "b": 2, "lb": 10, "da": True, "db": True},
    {"name": "arm-L-fr-2", "a": 0, "la": 15, "b": 2, "lb": 9, "da": True, "db": True},
    {"name": "arm-L-fr-3", "a": 0, "la": 16, "b": 2, "lb": 8, "da": True, "db": True},
    {"name": "arm-L-fr-4", "a": 0, "la": 17, "b": 2, "lb": 7, "da": True, "db": True},
    {"name": "arm-L-bk-0", "a": 1, "la": 12, "b": 2, "lb": 2, "da": True, "db": True},
    {"name": "arm-L-bk-1", "a": 1, "la": 13, "b": 2, "lb": 3, "da": True, "db": True},
    {"name": "arm-L-bk-2", "a": 1, "la": 14, "b": 2, "lb": 4, "da": True, "db": True},
    {"name": "arm-L-bk-3", "a": 1, "la": 15, "b": 2, "lb": 5, "da": True, "db": True},
    {"name": "arm-L-bk-4", "a": 1, "la": 16, "b": 2, "lb": 6, "da": True, "db": True},
]
