#pragma once

// Auto-generated by build_plugin.py. Do not edit by hand.

#define MIRRA_PLUGIN_NAME "CLO REST Automation"
#define MIRRA_PLUGIN_VERSION "1.1.0"
#define MIRRA_PLUGIN_API_VERSION "v1"
#define MIRRA_PLUGIN_RELEASE_DATE "2026-03-31"
#define MIRRA_PLUGIN_RELEASE_STATUS "unstable"
#define MIRRA_PLUGIN_PLATFORM "mac"
#define MIRRA_PLUGIN_PLATFORM_SYNC_STATE "pending"
#define MIRRA_PLUGIN_CONTRACT_NAME "clo-rest-plugin"
#define MIRRA_PLUGIN_CONTRACT_VERSION "v1"
#define MIRRA_PLUGIN_BUILD_TIME "2026-04-01T13:42:51Z"
