#pragma once

// Auto-generated by build_plugin.py. Do not edit by hand.

#define MIRRA_PLUGIN_NAME "CLO REST Automation"
#define MIRRA_PLUGIN_VERSION "1.3.2"
#define MIRRA_PLUGIN_API_VERSION "v1"
#define MIRRA_PLUGIN_RELEASE_DATE "2026-08-22"
#define MIRRA_PLUGIN_RELEASE_STATUS "unstable"
#define MIRRA_PLUGIN_PLATFORM "windows"
#define MIRRA_PLUGIN_PLATFORM_SYNC_STATE "in_sync"
#define MIRRA_PLUGIN_CONTRACT_NAME "clo-rest-plugin"
#define MIRRA_PLUGIN_CONTRACT_VERSION "v1"
#define MIRRA_PLUGIN_BUILD_TIME "2026-08-22T19:19:52Z"
#define MIRRA_PLUGIN_LOG_DIR "C:/D-drive-data/mirra-mvp/clo_workspace/logs"
