#pragma once

// Auto-generated by build_plugin.py. Do not edit by hand.

#define MIRRA_PLUGIN_NAME "CLO REST Automation"
#define MIRRA_PLUGIN_VERSION "1.1.1"
#define MIRRA_PLUGIN_API_VERSION "v1"
#define MIRRA_PLUGIN_RELEASE_DATE "2026-05-17"
#define MIRRA_PLUGIN_RELEASE_STATUS "unstable"
#define MIRRA_PLUGIN_PLATFORM "windows"
#define MIRRA_PLUGIN_PLATFORM_SYNC_STATE "in_sync"
#define MIRRA_PLUGIN_CONTRACT_NAME "clo-rest-plugin"
#define MIRRA_PLUGIN_CONTRACT_VERSION "v1"
#define MIRRA_PLUGIN_BUILD_TIME "2026-05-17T07:38:32Z"
