"""
Export STAR mesh to CLO3D-compatible formats.

Adds OBJ export capability to existing GLB export for CLO3D integration.
"""
import numpy as np
import trimesh
from typing import Dict, Any, Optional, Tuple
from pathlib import Path


def export_mesh_to_obj(
    vertices: np.ndarray,
    faces: np.ndarray,
    output_obj_path: str,
    include_normals: bool = True,
    include_uvs: bool = False,
    uv_coords: Optional[np.ndarray] = None,
    metadata: Optional[Dict[str, Any]] = None,
    scale_to_cm: bool = True
) -> None:
    """
    Export mesh to OBJ format for CLO3D.
    
    OBJ is CLO3D's preferred avatar import format.
    
    Args:
        vertices: Nx3 array of vertex positions (meters, Y-up)
        faces: Mx3 array of face indices (0-based)
        output_obj_path: Output file path (.obj)
        include_normals: Compute and export vertex normals
        include_uvs: Include UV coordinates (texture mapping)
        uv_coords: Optional Nx2 UV coordinates (if include_uvs=True)
        metadata: Optional metadata (measurements, etc.)
        scale_to_cm: If True, scale from meters to centimeters (multiply by 100)
                     CLO3D expects centimeter scale for proper display
    
    Raises:
        ValueError: If vertices/faces have wrong shape
        RuntimeError: If export fails
    
    Example:
        >>> vertices = star_mesh['vertices']  # Nx3
        >>> faces = star_mesh['faces']  # Mx3
        >>> export_mesh_to_obj(
        ...     vertices, faces,
        ...     "output/avatar.obj",
        ...     include_normals=True
        ... )
    """
    # Validation
    if vertices.shape[1] != 3:
        raise ValueError(
            f"Vertices must be Nx3, got {vertices.shape}"
        )
    
    if faces.shape[1] != 3:
        raise ValueError(
            f"Faces must be Mx3, got {faces.shape}"
        )
    
    # Scale vertices to centimeters for CLO3D
    # STAR exports in meters, CLO3D expects centimeters
    if scale_to_cm:
        vertices = vertices * 100.0
    
    # Ensure output directory exists
    output_path = Path(output_obj_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    # Create trimesh object
    mesh = trimesh.Trimesh(
        vertices=vertices,
        faces=faces,
        process=False  # Don't modify mesh
    )
    
    # Add UV coordinates if provided
    if include_uvs:
        if uv_coords is not None:
            if uv_coords.shape[0] != vertices.shape[0]:
                raise ValueError(
                    f"UV coords must match vertex count: "
                    f"{uv_coords.shape[0]} != {vertices.shape[0]}"
                )
            mesh.visual = trimesh.visual.TextureVisuals(uv=uv_coords)
        else:
            # Generate simple spherical UV mapping
            mesh.visual = _generate_spherical_uvs(mesh)
    
    # Export to OBJ
    try:
        with open(output_obj_path, 'w') as f:
            # Write header comment
            f.write(f"# MIRRA Avatar Export\n")
            f.write(f"# Generated by pipeline_star\n")
            f.write(f"# Units: Centimeters (scaled for CLO3D)\n")
            if metadata:
                f.write(f"# User ID: {metadata.get('user_id', 'unknown')}\n")
                f.write(f"# Gender: {metadata.get('gender', 'unknown')}\n")
                f.write(f"# Height: {metadata.get('height_cm', 'unknown')} cm\n")
            f.write(f"# Vertices: {len(vertices)}\n")
            f.write(f"# Faces: {len(faces)}\n\n")
        
        # Use trimesh to append OBJ data
        mesh.export(
            output_obj_path,
            file_type='obj',
            include_normals=include_normals,
            include_texture=include_uvs
        )
        
        print(f"✓ Exported OBJ to {output_obj_path}")
        print(f"  Vertices: {len(vertices):,}")
        print(f"  Faces: {len(faces):,}")
        if scale_to_cm:
            print(f"  Scale: Centimeters (100x for CLO3D)")
        
    except Exception as e:
        raise RuntimeError(f"OBJ export failed: {e}")


def _generate_spherical_uvs(mesh: trimesh.Trimesh) -> trimesh.visual.TextureVisuals:
    """
    Generate spherical UV mapping for avatar.
    
    Useful for simple texture application in CLO3D.
    """
    vertices = mesh.vertices
    
    # Compute spherical coordinates
    # Center at mesh centroid
    centroid = vertices.mean(axis=0)
    centered = vertices - centroid
    
    # Compute theta (azimuthal) and phi (polar) angles
    r = np.linalg.norm(centered, axis=1)
    theta = np.arctan2(centered[:, 2], centered[:, 0])  # 0 to 2π
    phi = np.arccos(np.clip(centered[:, 1] / (r + 1e-8), -1, 1))  # 0 to π
    
    # Map to [0, 1]
    u = (theta + np.pi) / (2 * np.pi)
    v = phi / np.pi
    
    uv_coords = np.column_stack([u, v])
    
    return trimesh.visual.TextureVisuals(uv=uv_coords)


def export_avatar_for_clo(
    vertices: np.ndarray,
    faces: np.ndarray,
    measurements: Dict[str, float],
    output_directory: str,
    user_id: str,
    run_number: int
) -> Dict[str, Any]:
    """
    Export avatar in CLO3D-ready format with full metadata.
    
    Creates:
    - avatar.obj (geometry)
    - avatar_measurements.json (body measurements)
    - avatar_info.txt (human-readable info)
    
    Args:
        vertices: Vertex array (Nx3, meters, Y-up)
        faces: Face array (Mx3, 0-based indices)
        measurements: Body measurements dict
        output_directory: Output directory path
        user_id: User identifier
        run_number: Run number
    
    Returns:
        Dict with paths to created files and statistics
    """
    import json
    from datetime import datetime
    
    output_dir = Path(output_directory)
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Create filename base
    base_name = f"{user_id}_{run_number:03d}"
    
    # Export OBJ
    obj_path = output_dir / f"{base_name}_avatar.obj"
    metadata = {
        'user_id': user_id,
        'run_number': run_number,
        'gender': measurements.get('gender', 'unknown'),
        'height_cm': measurements.get('height_cm', 0)
    }
    
    export_mesh_to_obj(
        vertices,
        faces,
        str(obj_path),
        include_normals=True,
        include_uvs=True,
        metadata=metadata
    )
    
    # Export measurements JSON
    json_path = output_dir / f"{base_name}_measurements.json"
    
    # Sanitize measurements dict: remove MongoDB-specific fields and convert datetime to string
    sanitized_measurements = {}
    for key, value in measurements.items():
        # Skip MongoDB internal fields
        if key.startswith('_'):
            continue
        # Convert datetime objects to ISO format strings
        if hasattr(value, 'isoformat'):
            sanitized_measurements[key] = value.isoformat()
        else:
            sanitized_measurements[key] = value
    
    measurement_data = {
        'user_id': user_id,
        'run_number': run_number,
        'export_date': datetime.now().isoformat(),
        'units': 'centimeters',
        'scale_factor': 100.0,
        'note': 'Vertices scaled 100x from meters to centimeters for CLO3D compatibility',
        'measurements': sanitized_measurements,
        'mesh_stats': {
            'vertex_count': int(len(vertices)),
            'face_count': int(len(faces)),
            'bounds_min_cm': (vertices.min(axis=0) * 100).tolist(),
            'bounds_max_cm': (vertices.max(axis=0) * 100).tolist()
        }
    }
    
    with open(json_path, 'w') as f:
        json.dump(measurement_data, f, indent=2)
    
    print(f"✓ Exported measurements to {json_path}")
    
    # Export info text
    info_path = output_dir / f"{base_name}_info.txt"
    with open(info_path, 'w') as f:
        f.write("MIRRA Avatar Export Information\n")
        f.write("=" * 50 + "\n\n")
        f.write(f"User ID: {user_id}\n")
        f.write(f"Run Number: {run_number}\n")
        f.write(f"Export Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n")
        
        f.write("Units & Scale:\n")
        f.write("-" * 50 + "\n")
        f.write(f"  Original: Meters (STAR model)\n")
        f.write(f"  Exported: Centimeters (scaled 100x for CLO3D)\n")
        f.write(f"  CLO Import Setting: Use 'Centimeters' or scale 1.0\n\n")
        
        f.write("Body Measurements:\n")
        f.write("-" * 50 + "\n")
        for key, value in measurements.items():
            if isinstance(value, float):
                f.write(f"  {key}: {value:.2f}\n")
            else:
                f.write(f"  {key}: {value}\n")
        
        f.write("\nMesh Statistics:\n")
        f.write("-" * 50 + "\n")
        f.write(f"  Vertices: {len(vertices):,}\n")
        f.write(f"  Faces: {len(faces):,}\n")
        f.write(f"  Bounds (cm): [{(vertices.min()*100):.1f}, {(vertices.max()*100):.1f}]\n")
        
        f.write("\nFiles Created:\n")
        f.write("-" * 50 + "\n")
        f.write(f"  Geometry: {obj_path.name}\n")
        f.write(f"  Measurements: {json_path.name}\n")
        f.write(f"  Info: {info_path.name}\n")
    
    print(f"✓ Exported info to {info_path}")
    
    return {
        'obj_file': str(obj_path),
        'json_file': str(json_path),
        'info_file': str(info_path),
        'vertex_count': int(len(vertices)),
        'face_count': int(len(faces))
    }


# Backwards compatibility with existing code
def export_mesh_to_glb(
    vertices: np.ndarray,
    faces: np.ndarray,
    output_glb_path: str,
    material_config: Optional[Dict[str, Any]] = None
) -> None:
    """
    Export mesh to GLB format (existing function).
    
    Kept for backwards compatibility with current pipeline.
    """
    try:
        import trimesh
    except ImportError:
        raise ImportError(
            "trimesh library is required for GLB export. "
            "Install it with: pip install trimesh"
        )
    
    if vertices.shape[1] != 3:
        raise ValueError(f"Vertices must have shape (N, 3), got {vertices.shape}")
    
    if faces.shape[1] != 3:
        raise ValueError(f"Faces must have shape (M, 3), got {faces.shape}")
    
    mesh = trimesh.Trimesh(vertices=vertices, faces=faces, process=False)
    
    if material_config is not None:
        material = trimesh.visual.material.PBRMaterial(
            baseColorFactor=material_config.get('baseColorFactor', [1.0, 1.0, 1.0, 1.0]),
            metallicFactor=material_config.get('metallicFactor', 0.0),
            roughnessFactor=material_config.get('roughnessFactor', 1.0),
            doubleSided=material_config.get('doubleSided', False)
        )
        mesh.visual = trimesh.visual.TextureVisuals(material=material)
    
    try:
        mesh.export(output_glb_path, file_type='glb')
    except Exception as e:
        raise RuntimeError(f"Failed to export GLB to {output_glb_path}: {e}")


if __name__ == "__main__":
    # Test with dummy data
    print("Testing OBJ exporter...")
    print("=" * 60)
    
    # Create simple test mesh (cube)
    vertices = np.array([
        [0, 0, 0], [1, 0, 0], [1, 1, 0], [0, 1, 0],  # Bottom
        [0, 0, 1], [1, 0, 1], [1, 1, 1], [0, 1, 1],  # Top
    ], dtype=np.float32)
    
    faces = np.array([
        [0, 1, 2], [0, 2, 3],  # Bottom
        [4, 5, 6], [4, 6, 7],  # Top
        [0, 1, 5], [0, 5, 4],  # Front
        [2, 3, 7], [2, 7, 6],  # Back
        [0, 3, 7], [0, 7, 4],  # Left
        [1, 2, 6], [1, 6, 5],  # Right
    ], dtype=np.int32)
    
    measurements = {
        'user_id': 'test_user',
        'gender': 'male',
        'height_cm': 175.0,
        'chest_circumference_cm': 95.0,
        'waist_circumference_cm': 85.0
    }
    
    result = export_avatar_for_clo(
        vertices,
        faces,
        measurements,
        output_directory="test_output/avatars",
        user_id="test_user",
        run_number=1
    )
    
    print("\n" + "=" * 60)
    print("✓ Test completed successfully!")
    print("=" * 60)
    print("\nCreated files:")
    for key, value in result.items():
        if isinstance(value, str):
            print(f"  {key}: {value}")
        else:
            print(f"  {key}: {value}")
